if(JUPITER_USE_MPI AND MPI_AINT_SIZE)
  math(EXPR _B "${MPI_AINT_SIZE} * 8")
  set(_T0N INT${_B})
  set(_T0R INT${_B})
  set(_T1N INT${_B})
  set(_T1R INT${_B})
  set(_T0M INT${_B})
  set(_T1M INT${_B})
else()
  set(_T0N PTRDIFF_T)
  set(_T0R PTRDIFF_T)
  set(_T1N PTRDIFF_T)
  set(_T1R PTRDIFF_T)
  set(_T0M PTRDIFF_T)
  set(_T1M PTRDIFF_T)
endif()
