#ifndef JUPITER_CONTROL_FIELD_FUNCTION_H
#define JUPITER_CONTROL_FIELD_FUNCTION_H

#include "defs.h"
#include "shared_object.h"

JUPITER_CONTROL_DECL_BEGIN

JUPITER_CONTROL_DECL
JCNTRL_SHARED_METADATA_INIT_DECL(jcntrl_field_function);

JUPITER_CONTROL_DECL_END

#endif
