#ifndef JUPITER_CONTROL_LOGICAL_VARIABLE_H
#define JUPITER_CONTROL_LOGICAL_VARIABLE_H

#include "defs.h"
#include "shared_object.h"

JUPITER_CONTROL_DECL_BEGIN

JUPITER_CONTROL_DECL
JCNTRL_SHARED_METADATA_INIT_DECL(jcntrl_logical_variable);

JUPITER_CONTROL_DECL_END

#endif
