/**
 * @ingroup Geometry
 * @file   shape.h
 * @brief  Shape functions
 */

#ifndef JUPITER_GEOMETRY_SHAPE_H
#define JUPITER_GEOMETRY_SHAPE_H

#include "defs.h"
#include "vector.h"
#include "svector.h"

JUPITER_GEOMETRY_DECL_START

/**
 * @memberof geom_shape_data
 * @brief Create new shape data
 * @param parent Parent data element
 * @param e If not NULL set detailed errors here
 * @return Created new shape data, NULL if failed.
 */
JUPITER_GEOMETRY_DECL
geom_shape_data *geom_shape_data_new(geom_data_element *parent, geom_error *e);

/**
 * @memberof geom_shape_data
 * @brief Delete shape data and all shapes contains in it
 * @param data
 */
JUPITER_GEOMETRY_DECL
void geom_shape_data_delete(geom_shape_data *data);

/**
 * @memberof geom_shape_data
 * @brief Get parent data element of shape data
 * @param data shape data to get for
 * @return Parent data element
 */
JUPITER_GEOMETRY_DECL
geom_data_element *geom_shape_data_parent(geom_shape_data *data);

/**
 * @memberof geom_shape_data
 * @brief Get master data of shape data
 * @param data shape data to get for
 * @return Master data
 */
JUPITER_GEOMETRY_DECL
geom_data *geom_shape_data_master(geom_shape_data *data);

JUPITER_GEOMETRY_DECL
void geom_shape_data_add_element(geom_shape_element *el);

JUPITER_GEOMETRY_DECL
void geom_shape_data_set_offsetv(geom_shape_data *data, geom_vec3 offset);

JUPITER_GEOMETRY_DECL
void geom_shape_data_set_originv(geom_shape_data *data, geom_vec3 origin);

JUPITER_GEOMETRY_DECL
void geom_shape_data_set_repeatv(geom_shape_data *data, geom_svec3 repeat);

JUPITER_GEOMETRY_DECL
void geom_shape_data_set_nsub_cell(geom_shape_data *data, int nsub_cell);

/**
 * @memberof geom_shape_data
 * @brief Delete all copy generated elements.
 * @param data Shape data to process
 *
 * Remove all elements which are created by
 * geom_shape_data_update_all_transform().
 */
JUPITER_GEOMETRY_DECL
void geom_shape_data_delete_copied_elements(geom_shape_data *data);

/**
 * @memberof geom_shape_data
 * @brief error callback function prototype
 *
 * @param err      Occured error value will be passed
 * @param data     Shape data which error_el belongs.
 * @param error_el Element which the error occured will be passed
 * @param extp The user provided data will be passed if you specified
 *             it for the parent function.
 *
 * The meaning of \p error_el depends the error and what function
 * called the callback function. See the documentation of each
 * functions for details.
 *
 * NULL will be passed for \p error_el if there is no corresponding
 * element for occured error.
 *
 * @retval 0     Continue the calculation
 * @retval non-0 Abort the calculation
 */
typedef int geom_shape_data_error_callback(geom_error err,
                                           geom_shape_data *data,
                                           geom_shape_element *error_el,
                                           void *extp);

/**
 * @memberof geom_shape_data
 *
 * @brief Compute all transformation and create transformation copies
 *        specified in each elements.
 *
 * @param data Shape data to compute transformation
 * @param callback Callback function to process all errors, give NULL
 *        if not required.
 * @param ext_data Extra data to be passed for callback
 * @param error_element Sets corresponding element for returned error,
 *        if given.
 *
 * @return Lastly occured error, the first 'unclosed' error will
 *         return if there are multiple 'unclosed' errors found, or
 *         ::GEOM_ERR_NOMEM if allocation failures occured in
 *         processing on any element.
 *
 * @retval ::GEOM_SUCCESS No errors occured
 * @retval ::GEOM_ERR_NOMEM Could not create transformation copies.
 * @retval ::GEOM_ERR_SHAPE_STACK_OVERFLOW Too many PUSHs used.
 * @retval ::GEOM_ERR_SHAPE_STACK_UNDERFLOW Too many COMBs used.
 * @retval ::GEOM_ERR_SHAPE_STACK_UNCLOSED There are unclosed PUSHs.
 * @retval ::GEOM_ERR_GROUP_STACK_OVERFLOW Too many GSTs used.
 * @retval ::GEOM_ERR_GROUP_STACK_UNDERFLOW Too many GEDs used.
 * @retval ::GEOM_ERR_GROUP_STACK_UNCLOSED There are unclosed GEDs.
 * @retval ::GEOM_ERR_COMB_WITHOUT_PUSH COMB found without PUSH.
 * @retval ::GEOM_ERR_INVALID_STRUCTURE Structure that cannot insert copies
 * @retval ::GEOM_ERR_SHAPE_NOT_SET Shape is not set.
 * @retval ::GEOM_ERR_NO_SHAPES_TO_TRANSFORM There is no bodies to transform.
 * @retval ::GEOM_ERR_SINGULAR_TRANSFORM Transformation matrix is
 *                                       singular; \f$|\det(M)| < 10^{-10}\f$.
 *
 * This function uses top-down algorithm to compute transformations,
 * and create copied elements specified by transformations.
 *
 * This function deletes copied elements which is generated by this
 * function first, and then compute matrices and regenerate copies
 * again.
 *
 * If overflow or underflow is occured, that element and
 * transformations for its group are ignored.
 *
 * If level mismatch is occured, the calculation of matrix and the
 * copy generation will not be done any more, but stack checking
 * continues.
 *
 * If multiple unclose errors are occured, callback function will be
 * called for each errors with corresponding start element (GST/PUSH),
 * but returns first unclose error (If ::GEOM_ERR_NOMEM is not
 * occured.), and \p error_element will be last element.
 *
 * Before calculate any in-body tests, you must call this function to
 * update transformation matrices. Otherwise you will get wrong
 * result, because it relies on the matrix computed by this
 * function. (Note that geom_shape_data_inbody_test_at() function is
 * thread safe to calculate multiple points in parallel, but the
 * calculation in this function is not thread safe. This is an another
 * reason that these functions are separeted.)
 *
 * After you change the number of copies by transformations, you must
 * call this function to update transformation matrices (and create
 * copied elements)
 *
 * After you add body elements without PUSH or SET operation, or if
 * you need matrix for transformation elements, you can use
 * geom_shape_data_check_stack() function to update transformation
 * matrices.
 *
 * After you add special elements such as bodies with PUSH or SET
 * operation, GST, GED, and COMB, you should use this function to
 * update transformation matrix. This function can also check stack
 * operation errors.
 *
 * To get transformation matrix after calling this function, use
 * geom_shape_element_get_transform() to get updated matrix, which
 * just returns the matrix contained by the element.
 *
 * If you return non-0 value from callback function, the operation
 * will stop on the error, and the remaining data will be unchanged.
 *
 * If ::GEOM_ERR_NOMEM occured, the check operation will continue (if
 * you return 0 from callback function), and the callback function
 * will be called for another error if occured, but no more elements
 * will be created.
 *
 * For each transformation elements, this function does:
 *
 *  a. If number of copies to generate is 0 (do not create copies),
 *     multply its transformation matrix into each all body elements.
 *
 *  b. If number of copies to generate is 1 or greater,
 *     copies each bodies in the target region by specific way
 *     (explain later), and multiply its transformation matrix
 *     into copied elements.
 *
 * From now, 'body' means the body elements or COMB on the stack level
 * same as the target region to transform. So, a PUSH --- COMB pair
 * will be counted as 1 body.
 *
 *     SET GST
 *       ADD BOX    --- 1
 *       PUSH BOX   -.
 *          ...      |- 2
 *       SUB COMB   -'
 *       MUL RCC    --- 3
 *     SET GED
 *     ADD TRA      --- There are 3 bodies to transform.
 *
 * We allows only one unclosed PUSH in the transformation region. And,
 * this unclosed PUSH is counted as 1 body. This is required to specify
 * the transformation from the beginning of the element list.
 *
 *     SET GST
 *       ADD BOX    --- 1
 *       PUSH BOX   -.
 *       SUB BOX     |- 2
 *       ADD BOX    -'
 *     SET GED
 *
 * But the two or more unclosed PUSHs' present, you will get an errror
 * ::GEOM_ERR_INVALID_STRUCTURE. This condition will be explicitly
 * error only if the transformation with copy, but for integrity,
 * this condition will be an error even if transformation does not
 * copy elements.
 *
 *     SET GST
 *       ADD BOX    --- This element will be a body
 *       PUSH BOX   -.
 *         SUB BOX   |- These elements may be counted as a body,
 *         PUSH BOX  |  but we cannot insert copies in reasonable ways.
 *         ADD BOX  -'
 *     SET GED
 *
 * If the copy region includes COMB without PUSH, you will get an error
 * ::GEOM_ERR_COMB_WITHOUT_PUSH.
 *
 *     SET GST
 *       ADD COMB   --- Error.
 *     SET GED
 *
 * When copy elements by transformations, this function does following
 * operations to each bodies.
 *
 *  a. If the body is a simple body (consists of one element), and
 *     it uses PUSH operation, we use the new group created by the
 *     target element. For example,
 *
 *         PUSH BOX
 *         ADD  TRA matrix M (copy by 3)
 *
 *     will be transformed into
 *
 *         PUSH BOX
 *         ADD  BOX (copy 1; transformed by M)
 *         ADD  BOX (copy 2; transformed by M*M)
 *         ADD  BOX (copy 3; transformed by M*M*M)
 *
 *  b. If the body is a simple body, and it uses an operation other
 *     than PUSH operation, we create the new group by changing the
 *     operation into PUSH and add COMB element.
 *
 *         SUB  BOX
 *         ADD  TRA matrix M (copy by 3)
 *
 *     will be transformed into
 *
 *         PUSH BOX  (original)
 *         ADD  BOX  (copy 1; transformed by M)
 *         ADD  BOX  (copy 2; transformed by M*M)
 *         ADD  BOX  (copy 3; transformed by M*M*M)
 *         SUB  COMB (added COMB)
 *
 *  c. If the body is a combined body, and there is no corresponding
 *     COMB in the target region to transform, adds COMB at the end
 *     of each copies, but adding like case (a).
 *
 *         SET GST
 *         PUSH BOX    -.
 *          ADD BOX     |- 1 body
 *          ADD BOX    -'
 *         SET GED
 *         ADD TRA
 *
 *     will be transformed into
 *
 *         PUSH BOX    -.
 *          ADD BOX     |- (Original)
 *          ADD BOX    -'
 *          PUSH BOX   -.
 *           ADD BOX    |- (copy 1; transfromed by M)
 *           ADD BOX   -'
 *          ADD COMB   --- (added COMB)
 *          PUSH BOX   -.
 *           ADD BOX    |- (copy 2; transfromed by M*M)
 *           ADD BOX   -'
 *          ADD COMB   --- (added COMB)
 *          PUSH BOX   -.
 *           ADD BOX    |- (copy 3; transfromed by M*M*M)
 *           ADD BOX   -'
 *          ADD COMB   --- (added COMB)
 *
 *  d. If the body is a combined body, and there is corresponding
 *     COMB in the target region to transform, copies will be inserted
 *     **before** the last COMB to use the group,
 *
 *         PUSH BOX    -.
 *          ADD BOX     |- 1 body
 *          ADD BOX     |
 *         SUB COMB    -'
 *         ADD TRA
 *
 *     will be transformed into
 *
 *         PUSH BOX    -.
 *          ADD BOX     |- (Original)
 *          ADD BOX    -'
 *          PUSH BOX   -.
 *           ADD BOX    |- (copy 1; transfromed by M)
 *           ADD BOX   -'
 *          ADD COMB   --- (added COMB)
 *          PUSH BOX   -.
 *           ADD BOX    |- (copy 2; transfromed by M*M)
 *           ADD BOX   -'
 *          ADD COMB   --- (added COMB)
 *          PUSH BOX   -.
 *           ADD BOX    |- (copy 3; transfromed by M*M*M)
 *           ADD BOX   -'
 *          ADD COMB   --- (added COMB)
 *         SUB COMB    --- (COMB in original)
 */
JUPITER_GEOMETRY_DECL
geom_error geom_shape_data_update_all_transform(
  geom_shape_data *data, geom_shape_data_error_callback *callback,
  void *ext_data, geom_shape_element **error_element);

JUPITER_GEOMETRY_DECL
geom_vec3 geom_shape_data_get_offset(geom_shape_data *data);

JUPITER_GEOMETRY_DECL
geom_vec3 geom_shape_data_get_origin(geom_shape_data *data);

JUPITER_GEOMETRY_DECL
geom_svec3 geom_shape_data_get_repeat(geom_shape_data *data);

JUPITER_GEOMETRY_DECL
int geom_shape_data_get_nsub_cell(geom_shape_data *data);

JUPITER_GEOMETRY_DECL
int geom_shape_data_inbody_test_at(geom_shape_data *data, double x, double y,
                                   double z);

/**
 * @brief Obtain if any element supports surface
 * @param data Data set to check
 * @return 1 if any shape element support surfaces, 0 otherwise.
 */
JUPITER_GEOMETRY_DECL
int geom_shape_data_has_surface(geom_shape_data *data);

/**
 * @brief Obtain if any element supports surface and they are enabled
 * @param data Data set to check
 * @return 1 if any shape element has least one enabled surfaces, 0 otherwise.
 */
JUPITER_GEOMETRY_DECL
int geom_shape_data_has_enabled_surface(geom_shape_data *data);

/**
 * @brief Returns the default maximum iteration count for iteration in
 *        geom_shape_data_nearest_surface()
 */
JUPITER_GEOMETRY_DECL
int geom_shape_data_nearest_surface_default_iter_count(void);

/**
 * @brief Returns the default criteria for iteration in
 *        geom_shape_data_nearest_surface()
 */
double geom_shape_data_nearest_surface_default_iter_criterion(void);

/**
 * @brief Obtain the nearest point on the surface
 * @param data Data shape data set to compute
 * @param xyz Point to compute
 * @param iter_count Iteration count in some cases
 * @param iter_crit Stopping iteration criteria
 * @param surface_element If given, sets the element that @p surfp is on
 * @param uv If given, return UV world coordinate on the surface
 * @param surfp If given, return 3D world coordinate on the surface
 * @param normv If given, return normal vector at the surface
 * @return Errors, if any
 *
 * If @p iter_count is less than 0, this function uses the internal
 * default for iteration count. You can set @p iter_count to 0 for
 * disallowing iteration.
 *
 * If @p iter_crit is less than or equal to 0, this function uses the
 * internal default for iteration criterion. This criterion value is
 * absolute. For example, if you are using metre for the unit of
 * length, the criterion of 1e-6 will mean 1 micrometre.
 *
 * The iteration method is used when the nearest surface points in
 * both shape element branches are invalid (not on the final surface).
 *
 * @note Shapes which do not support their surfaces are ignored. If no
 *       shapes support their surface, sets @p surface_element to NULL
 *       and return GEOM_SUCCESS. The values in @p uv, @p surfp and @p
 *       normv are undefined.
 *
 * @note geom_shape_data_inbody_test_at(data, *surfp) is undefined.
 *       Most shapes are programmed to return 1, but may return 0 if
 *       not or for calculation errors.
 */
JUPITER_GEOMETRY_DECL
geom_error geom_shape_data_nearest_surface(geom_shape_data *data, geom_vec3 xyz,
                                           int iter_count, double iter_crit,
                                           geom_shape_element **surface_element,
                                           geom_vec2 *uv, geom_vec3 *surfp,
                                           geom_vec3 *normv);

JUPITER_GEOMETRY_DECL
geom_shape_element *geom_shape_data_get_element(geom_shape_data *data);

JUPITER_GEOMETRY_DECL
geom_shape_element *geom_shape_element_new(geom_shape_data *data,
                                           geom_error *e);

JUPITER_GEOMETRY_DECL
geom_shape_data *geom_shape_element_parent(geom_shape_element *e);

JUPITER_GEOMETRY_DECL
geom_data *geom_shape_element_master(geom_shape_element *e);

JUPITER_GEOMETRY_DECL
void geom_shape_element_delete(geom_shape_element *e);

/**
 * @memberof geom_shape_element
 * @brief Get next element
 * @param e Element to get next for
 * @return Next element
 * @retval e    \p e is not added to the data yet.
 * @retval NULL \p e is the last element.
 */
JUPITER_GEOMETRY_DECL
geom_shape_element *geom_shape_element_next(geom_shape_element *e);

/**
 * @memberof geom_shape_element
 * @brief Get previous element
 * @param e Element to get previous for
 * @return Previous element
 * @retval e    \p e is not added to the data yet.
 * @retval NULL \p e is the first element.
 */
JUPITER_GEOMETRY_DECL
geom_shape_element *geom_shape_element_prev(geom_shape_element *e);

JUPITER_GEOMETRY_DECL
int geom_shape_element_is_head(geom_shape_element *e);

JUPITER_GEOMETRY_DECL
geom_shape_args_builder *geom_shape_args_builder_new(geom_shape shape,
                                                     geom_error *e);

JUPITER_GEOMETRY_DECL
void geom_shape_args_builder_delete(geom_shape_args_builder *builder);

JUPITER_GEOMETRY_DECL
geom_args_builder *geom_shape_args_get_builder(geom_shape_args_builder *b);

JUPITER_GEOMETRY_DECL
geom_error geom_shape_element_set_shape(geom_shape_element *e,
                                        geom_shape_operator op,
                                        geom_shape_args_builder *shape);

/**
 * @memberof geom_shape_element
 * @brief Get effective operator
 * @param e Element to get
 * @return Effective (i.e. used for in-body test calculation) operator.
 *
 * Effective operator may different to original. It may change on
 * processing transformation copies.
 */
JUPITER_GEOMETRY_DECL
geom_shape_operator
geom_shape_element_effective_operator(geom_shape_element *e);

/**
 * @memberof geom_shape_element
 * @brief Get original operator
 * @param e Element to get
 * @return Original (i.e. given at geom_shape_element_set_shape()) oprerator
 */
JUPITER_GEOMETRY_DECL
geom_shape_operator geom_shape_element_original_operator(geom_shape_element *e);

JUPITER_GEOMETRY_DECL
geom_shape geom_shape_element_get_shape(geom_shape_element *e);

JUPITER_GEOMETRY_DECL
geom_shape_type geom_shape_element_get_shape_type(geom_shape_element *e);

/**
 * @memberof geom_shape_element
 * @brief Get transformation matrix
 * @param e Element to get from.
 * @return pointer to matrix.
 *
 * Just to avoid inclusion of 'mat43.h' from 'shape.h', this function
 * returns pointer to the matrix. It is guaranteed to return non-NULL
 * pointer.
 * (FYI if \p e is NULL, you will be an assertion failure)
 *
 * The shape element does not store the transformation status, the
 * content of returning matrix is undefined, unless it is ensured that
 * geom_shape_data_update_all_transform() were ran.
 */
JUPITER_GEOMETRY_DECL
const geom_mat43 *geom_shape_element_get_transform(geom_shape_element *e);

/**
 * @memberof geom_shape_type
 * @brief Get shape type from shape enum.
 * @param shape shape to get for.
 * @return shape type of shape
 *
 * geom_shape_element_get_shape_type() is faster than this function,
 * if a ::geom_shape_element is in question.
 *
 * This function costs \f$ O(\log N)\f$ (\f$N\f$ is number of shapes
 * registerd to the library) where geom_shape_element_get_shape_type()
 * is \f$O(1)\f$.
 */
JUPITER_GEOMETRY_DECL
geom_shape_type geom_shape_type_for_shape(geom_shape shape);

/**
 * @memberof geom_shape_element
 * @brief Get whether the shape element is copy generated by update
 * @param e Element to copy
 * @retval 0 Given element
 * @retval non-0 Internally generated element
 */
JUPITER_GEOMETRY_DECL
int geom_shape_element_is_copied(geom_shape_element *e);

JUPITER_GEOMETRY_DECL
int geom_shape_element_get_transformation_copy_n(geom_shape_element *e);

/**
 * @memberof geom_shape_element
 * @brief Generate information map for specified element
 * @param e Element to generate
 * @return Generated information map, NULL if failed
 */
JUPITER_GEOMETRY_DECL
geom_info_map *geom_shape_element_shape_info(geom_shape_element *e);

/**
 * @memberof geom_shape_element
 * @brief Set Number of Array transformations
 * @param e Element to set
 * @param ncopy number of copies to make
 * @retval ::GEOM_SUCCESS No error
 * @retval ::GEOM_ERR_SHAPE_NOT_SET Shape is not set
 * @retval ::GEOM_ERR_INVALID_SHAPE Specified shape is not transformation
 *
 * You must call geom_shape_data_update_all_transform() to take effect.
 */
JUPITER_GEOMETRY_DECL
geom_error geom_shape_element_set_transformation_copy_n(geom_shape_element *e,
                                                        int ncopy);

/**
 * @memberof geom_shape_element
 * @brief Modify shape specific parameter
 * @param e Shape element to set
 * @param index Parameter index to set.
 * @param var Value to set
 * @param einfo Sets error information if error occurs.
 * @retval GEOM_SUCCESS no error
 * @retval GEOM_ERR_RANGE @p index or value out-of-range
 * @retval GEOM_ERR_NOMEM Allocation failed (some parameters may allocate
 *                        memory to set the parameter)
 * @retval GEOM_ERR_DEPENDENCY Some of parameters are missing to check
 *                             or set the given parameter.
 * @retval ...
 *
 * Some shapes may set @p einfo even if it return GEOM_SUCCESS.
 */
JUPITER_GEOMETRY_DECL
geom_error geom_shape_element_set_parameter(geom_shape_element *e,
                                            geom_size_type index,
                                            const geom_variant *var,
                                            geom_variant *einfo);

/**
 * @memberof geom_shape_element
 * @brief Retrieve shape specific parameter
 * @param e Shape element to get
 * @param index Parameter index to get.
 * @param var Denstination variant to get
 * @retval GEOM_SUCCESS no error
 * @retval GEOM_ERR_NOMEM Allocation failed (some parameters may allocate
 *                        memory to get the parameter)
 */
JUPITER_GEOMETRY_DECL
geom_error geom_shape_element_get_parameter(geom_shape_element *e,
                                            geom_size_type index,
                                            geom_variant *out_variable);

/**
 * @brief Return number of surfaces in a shape
 * @param e Shape element to get
 * @return result.
 */
JUPITER_GEOMETRY_DECL
int geom_shape_element_n_surface(geom_shape_element *e);

/**
 * @brief Return number of enabled surfaces in a shape
 * @param e Shape element to get
 * @return result.
 */
JUPITER_GEOMETRY_DECL
int geom_shape_element_n_enabled_surface(geom_shape_element *e);

/**
 * @brief Return number of enabled surfaces in a shape
 * @param e Shape element to get
 * @param surfid Surface ID to tset
 * @return 0 if not enabled, otherwise enabled
 */
JUPITER_GEOMETRY_DECL
int geom_shape_element_is_surface_enabled(geom_shape_element *e, int surfid);

JUPITER_GEOMETRY_DECL
geom_error geom_shape_element_set_extra_data(geom_shape_element *e, void *data,
                                             geom_deallocator *dealloc);

JUPITER_GEOMETRY_DECL
const geom_user_defined_data *
geom_shape_element_get_extra_data(geom_shape_element *e);

JUPITER_GEOMETRY_DECL_END

#endif
