
#ifndef JUPITER_GEOMETRY_SHP_PL3_H
#define JUPITER_GEOMETRY_SHP_PL3_H

#include "defs.h"

JUPITER_GEOMETRY_DECL_START

JUPITER_GEOMETRY_DECL
geom_error geom_install_shape_pl3(void);

JUPITER_GEOMETRY_DECL_END

#endif
