
#ifndef JUPITER_GEOMETRY_SHP_PL2_H
#define JUPITER_GEOMETRY_SHP_PL2_H

#include "defs.h"

JUPITER_GEOMETRY_DECL_START

JUPITER_GEOMETRY_DECL
geom_error geom_install_shape_pl2(void);

JUPITER_GEOMETRY_DECL_END

#endif
