/* Generated by re2c 4.5 */
/* This is -*- c -*- source. */
/* This is vim: set ft=c: source. */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <stddef.h>
#include <ctype.h>
#include <limits.h>
#include <math.h>    /* Used in formatter. */

#include "geometry/list.h"
#include "geometry/alloc_list.h"
#include "csv.h"
#include "csvutil.h"

#include <jupiter/re2c_lparser/re2c_lparser.h>

#ifdef JUPITER_MPI
#include <mpi.h>
#endif

enum csv_constants {
  hashsize = 256,
};

struct csv_column
{
  csv_row *parent;
  char *value;
  long line;
  long cols;
  struct geom_list list;
};
#define csv_column_entry(p) geom_list_entry(p, struct csv_column, list)

struct csv_row
{
  struct geom_list list;
  struct geom_list hash_list;
  csv_data *parent;
  csv_column column_head;
};
#define csv_row_entry(p) geom_list_entry(p, struct csv_row, list)
#define csv_row_hash_entry(p) geom_list_entry(p, struct csv_row, hash_list)

struct csv_data
{
  geom_alloc_list *allocs;
  csv_row row_head;
  struct geom_list rowtable[hashsize];
};

struct csv_token
{
  struct geom_list list;
  char *start;
  const char *end;
  long line;
  long col;
};
#define csv_token_entry(p) \
  geom_list_entry(p, struct csv_token, list)

struct csv_parser
{
  csv_data *data;
  struct re2c_lparser lp;
  struct csv_token token_head;
  csv_row *row;
  long cs_line;
  long cs_column;
  enum quotestate { in_quote, out_quote, quote_notset } use_quote;
};
typedef struct csv_parser csv_parser;

static unsigned long
hashCSVKey(const char *string, int len)
{
  unsigned long i, r, c;

  CSVASSERT(string);
  CSVASSERT(len >= 0);

  i = 0;
  r = 0;
  c = len;
  while (*string != '\0' && i < c) {
    r = r * 97 + (unsigned long)*string;
    string++;
  }
  c = 0;
  for (i = 0; i < sizeof(unsigned long); ++i) {
    c = c * 11 + ((r >> (i * CHAR_BIT)) & 0xff);
  }
  return c % hashsize;
}

static void
initCSVColumn(csv_column *col, csv_row *row)
{
  CSVASSERT(col);
  CSVASSERT(row);

  geom_list_init(&col->list);
  col->cols = 0;
  col->line = 0;
  col->parent = row;
  col->value = NULL;
}

static void
initCSVRow(csv_row *row, csv_data *d)
{
  CSVASSERT(row);
  CSVASSERT(d);

  row->parent = d;
  initCSVColumn(&row->column_head, row);
  geom_list_init(&row->list);
  geom_list_init(&row->hash_list);
}

static csv_error initCSV(csv_data *d)
{
  int i;

  CSVASSERT(d);

  d->allocs = geom_alloc_list_new();
  if (!d->allocs) {
    return CSV_ERR_NOMEM;
  }
  initCSVRow(&d->row_head, d);
  for (i = 0; i < hashsize; ++i) {
    geom_list_init(&d->rowtable[i]);
  }
  return 0;
}

csv_data *allocateCSV(void)
{
  csv_data *p;
  int ret;

  p = (csv_data*)malloc(sizeof(csv_data));
  if (!p) {
    return NULL;
  }
  ret = initCSV(p);
  if (ret != CSV_ERR_SUCC) {
    free(p);
    return NULL;
  }

  return p;
}

void freeCSV(csv_data *d)
{
  if (!d) return;
  if (d->allocs) {
    geom_alloc_free_all(d->allocs);
  }
  free(d);
}

csv_row *newCSVRow(csv_data *d)
{
  csv_row *t;

  CSVASSERT(d);
  CSVASSERT(d->allocs);

  t = (csv_row*)malloc(sizeof(csv_row));
  if (!t) return NULL;

  if (geom_alloc_add(d->allocs, t, free) != GEOM_SUCCESS) {
    free(t);
    return NULL;
  }

  initCSVRow(t, d);
  return t;
}

csv_column *newCSVColumn(csv_row *r)
{
  csv_data *d;
  csv_column *t;

  CSVASSERT(r);

  d = r->parent;

  CSVASSERT(d);
  CSVASSERT(d->allocs);

  t = (csv_column*)malloc(sizeof(csv_column));
  if (!t) return NULL;

  if (geom_alloc_add(d->allocs, t, free) != GEOM_SUCCESS) {
    free(t);
    return NULL;
  }

  initCSVColumn(t, r);
  return t;
}

static const char *getCSVRowKey(csv_row *row)
{
  struct geom_list *lp;

  CSVASSERT(row);

  lp = geom_list_next(&row->column_head.list);
  if (lp != &row->column_head.list) {
    csv_column *c;

    c = csv_column_entry(lp);
    return c->value;
  }
  return NULL;
}

int appendCSVRow(csv_data *d, csv_row *row)
{
  const char *keystr;
  unsigned long l;

  CSVASSERT(d);
  CSVASSERT(row);
  CSVASSERT(d == row->parent);

  geom_list_insert_prev(&d->row_head.list, &row->list);

  keystr = getCSVRowKey(row);
  if (keystr) {
    l = hashCSVKey(keystr, strlen(keystr));
    geom_list_insert_prev(&d->rowtable[l], &row->hash_list);
  }

  return 0;
}

int appendCSVColumn(csv_row *row, csv_column *col)
{
  CSVASSERT(row);
  CSVASSERT(col);
  CSVASSERT(row == col->parent);

  geom_list_insert_prev(&row->column_head.list, &col->list);
  return 0;
}

#define YYDEBUG(i, c)

/**
 * This function resolves escapes of "", \" and \\.
 */
static char *unescapeCSVCellString(const char *stp, const char *endp, int *n)
{
  const char *tok;
  const char *cur;
  /* const char *mrk; */
  char *buf;
  char *dst;
  char *dlim;

  CSVASSERT(stp);
  CSVASSERT(endp);
  CSVASSERT(n);
  CSVASSERT(stp <= endp);

  *n = endp - stp + 1;
  buf = (char *)malloc(sizeof(char) * (*n));
  if (!buf) {
    *n = 0;
    return NULL;
  }

  tok = stp;
  cur = tok;
  dst = buf;
  dlim = buf + *n;

  while (cur < endp && dst < dlim) {
    tok = cur;
    
    {
      unsigned char yych;
      yych = *cur;
      if (yych == '"') goto yy2;
      if (yych == '\\') goto yy3;
      ++cur;
yy1:
      { *(dst++) = *tok; continue; }
yy2:
      yych = *++cur;
      if (yych == '"') goto yy4;
      goto yy1;
yy3:
      yych = *++cur;
      if (yych == '"') goto yy5;
      if (yych == '\\') goto yy6;
      goto yy1;
yy4:
      ++cur;
      { *(dst++) = '"'; continue; }
yy5:
      ++cur;
      { *(dst++) = '"'; continue; }
yy6:
      ++cur;
      { *(dst++) = '\\'; continue; }
    }


    CSVUNREACHABLE();
  }
  *dst = '\0';
  return buf;
}

static int
csvAddToken(csv_parser *p, const char *startp, const char *endp,
            char *allocp, long line, long col, csv_error *err)
{
  struct csv_token *token;
  ptrdiff_t n;

  CSVASSERT(p);
  CSVASSERT(startp);
  CSVASSERT(endp);

  token = (struct csv_token *)malloc(sizeof(struct csv_token));
  if (!token) {
    if (err) *err = CSV_ERR_NOMEM;
    return 1;
  }

  n = endp - startp;
  if (!allocp) {
    allocp = (char *)malloc(sizeof(char) * n);
    memcpy(allocp, startp, n);
  } else {
    if (allocp != startp) {
      memmove(allocp, startp, n);
    }
  }

  geom_list_insert_prev(&p->token_head.list, &token->list);
  token->start = allocp;
  token->end = endp - startp + allocp;
  token->line = line;
  token->col = col;

  return 0;
}

enum csv_add_mode {
  ADD_CELL = 0x1,
  ADD_ROW  = 0x2,
  ADD_CELL_ROW = ADD_CELL | ADD_ROW,
};

static int
csvAddCellSupport(csv_parser *p, enum csv_add_mode mode, csv_error *err)
{
  struct geom_list *lp, *ln, *lh;
  char *buf;
  char *dst;
  csv_column *col;
  csv_row *row;
  ptrdiff_t n;
  long l, c;

  CSVASSERT(p);
  CSVASSERT(p->data);

  row = p->row;

  if (mode & ADD_CELL) {
    lh = &p->token_head.list;
    n = 0;

    if (!geom_list_empty(lh)) {
      geom_list_foreach(lp, lh) {
        struct csv_token *tok;
        tok = csv_token_entry(lp);
        n += tok->end - tok->start;
        if (n < 0) {
          if (err) *err = CSV_ERR_2BIG;
          return 1;
        }
      }
      if (n + 1 < 0) {
        if (err) *err = CSV_ERR_2BIG;
        return 1;
      }

      buf = (char *)malloc(sizeof(char) * (n + 1));
      if (!buf) {
        if (err) *err = CSV_ERR_NOMEM;
        return 1;
      }

      if (geom_alloc_add(p->data->allocs, buf, free) != GEOM_SUCCESS) {
        if (err) *err = CSV_ERR_NOMEM;
        free(buf);
        return 1;
      }

      dst = buf;
      l = -1;
      c = -1;
      geom_list_foreach_safe(lp, ln, lh) {
        struct csv_token *tok;
        tok = csv_token_entry(lp);

        if (l < 0) {
          l = tok->line;
          c = tok->col;
        }
        n = tok->end - tok->start;
        memcpy(dst, tok->start, n);
        dst += n;

        geom_list_delete(lp);
        free(tok->start);
        free(tok);
      }
      *dst = '\0';

      if (!row) {
        row = newCSVRow(p->data);
        if (!row) {
          if (err) *err = CSV_ERR_NOMEM;
          return 1;
        }
        p->row = row;
      }
      col = newCSVColumn(row);
      if (!col) {
        if (err) *err = CSV_ERR_NOMEM;
        return 1;
      }
      col->value = buf;
      col->line = l;
      col->cols = c;
      appendCSVColumn(row, col);
    }
  }
  if (mode & ADD_ROW) {
    if (row) {
      appendCSVRow(p->data, row);
    }
    row = NULL;
  }
  p->row = row;

  return 0;
}

static int
csv_fill(csv_parser *p, FILE *stream, int n)
{
  ptrdiff_t off;
  int ret;

  off = 0;
  ret = re2c_lparser_fill(&p->lp, stream, NULL, n, &off);
  return ret;
}

csv_error
readCSV(FILE *stream, csv_data **data, long *error_line, long *error_col)
{
  csv_parser parser;
  char *tmp;
  int n;
  csv_error ret;

  CSVASSERT(stream);
  CSVASSERT(data);

  *data = NULL;

  parser.data = allocateCSV();
  if (!parser.data) return CSV_ERR_NOMEM;

  parser.row = NULL;
  parser.cs_line = -1;
  parser.cs_column = -1;
  geom_list_init(&parser.token_head.list);
  parser.token_head.start = NULL;
  parser.token_head.end   = NULL;
  parser.use_quote = quote_notset;

  ret = CSV_ERR_SUCC;
  re2c_lparser_init(&parser.lp);
  if (re2c_lparser_fill(&parser.lp, stream, NULL, 1, NULL) < 0) goto error;

start:
  re2c_lparser_start_token(&parser.lp);
  
  {
    unsigned char yych;
    if ((parser.lp.lim - parser.lp.cur) < 2) { if (csv_fill(&parser, stream, 2) < 0) goto error; }
    yych = *parser.lp.cur;
    switch (yych) {
      case 0x00: goto yy8;
      case '\t':
      case ' ': goto yy11;
      case '\n': goto yy13;
      case '\r': goto yy15;
      case '"': goto yy16;
      case '&': goto yy17;
      case ',': goto yy18;
      case '-': goto yy19;
      case '/': goto yy20;
      default: goto yy9;
    }
yy8:
    ++parser.lp.cur;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      if (parser.lp.lexeme && parser.lp.lexeme < parser.lp.tok) {
        if (csvAddToken(&parser, parser.lp.lexeme, parser.lp.tok, NULL,
                        parser.cs_line, parser.cs_column, &ret)) goto error;
      }
      parser.lp.lexeme = NULL;
      if (csvAddCellSupport(&parser, ADD_CELL_ROW, &ret)) goto error;
      parser.use_quote = quote_notset;
      goto end;
    }
yy9:
    ++parser.lp.cur;
yy10:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      if (!parser.lp.lexeme) {
        if (parser.use_quote == in_quote) {
          ret = CSV_ERR_MIX_QUOTE;
          goto error;
        }
        parser.use_quote = out_quote;
        parser.lp.lexeme = parser.lp.tok;
        parser.cs_line = parser.lp.tokline;
        parser.cs_column = parser.lp.tokcol;
      }
      goto start;
    }
yy11:
    parser.lp.mrk = ++parser.lp.cur;
    if ((parser.lp.lim - parser.lp.cur) < 2) { if (csv_fill(&parser, stream, 2) < 0) goto error; }
    yych = *parser.lp.cur;
    switch (yych) {
      case '\t':
      case ' ': goto yy11;
      case '\n': goto yy13;
      case '\r': goto yy15;
      case '&': goto yy17;
      case ',': goto yy18;
      case '-': goto yy21;
      case '/': goto yy23;
      default: goto yy12;
    }
yy12:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto start;
    }
yy13:
    ++parser.lp.cur;
yy14:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      if (parser.lp.lexeme && parser.lp.lexeme < parser.lp.tok) {
        if (csvAddToken(&parser, parser.lp.lexeme, parser.lp.tok, NULL,
                        parser.cs_line, parser.cs_column, &ret)) goto error;
      }
      parser.lp.lexeme = NULL;
      if (csvAddCellSupport(&parser, ADD_CELL_ROW, &ret)) goto error;
      parser.use_quote = quote_notset;
      goto start;
    }
yy15:
    yych = *++parser.lp.cur;
    if (yych == '\n') goto yy13;
    goto yy14;
yy16:
    ++parser.lp.cur;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      if (parser.use_quote == out_quote) {
        ret = CSV_ERR_MIX_QUOTE;
        goto error;
      }
      parser.use_quote = in_quote;
      parser.lp.lexeme = parser.lp.cur;
      parser.cs_line = parser.lp.line;
      parser.cs_column = parser.lp.col;
      goto instring;
    }
yy17:
    ++parser.lp.cur;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      if (parser.lp.lexeme && parser.lp.lexeme < parser.lp.tok) {
        if (csvAddToken(&parser, parser.lp.lexeme, parser.lp.tok, NULL,
                        parser.cs_line, parser.cs_column, &ret)) goto error;
      }
      parser.lp.lexeme = NULL;
      goto continuing;
    }
yy18:
    ++parser.lp.cur;
    if (parser.lp.lim <= parser.lp.cur) { if (csv_fill(&parser, stream, 1) < 0) goto error; }
    yych = *parser.lp.cur;
    if (yych == '\t') goto yy18;
    if (yych == ' ') goto yy18;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      if (parser.lp.lexeme && parser.lp.lexeme < parser.lp.tok) {
        if (csvAddToken(&parser, parser.lp.lexeme, parser.lp.tok, NULL,
                        parser.cs_line, parser.cs_column, &ret)) goto error;
        parser.lp.lexeme = NULL;
      }
      if (csvAddCellSupport(&parser, ADD_CELL, &ret)) goto error;
      parser.use_quote = quote_notset;
      goto start;
    }
yy19:
    yych = *++parser.lp.cur;
    if (yych == '-') goto yy24;
    goto yy10;
yy20:
    yych = *++parser.lp.cur;
    if (yych == '*') goto yy25;
    goto yy10;
yy21:
    yych = *++parser.lp.cur;
    if (yych == '-') goto yy24;
yy22:
    parser.lp.cur = parser.lp.mrk;
    goto yy12;
yy23:
    yych = *++parser.lp.cur;
    if (yych == '*') goto yy25;
    goto yy22;
yy24:
    ++parser.lp.cur;
    parser.lp.cur -= 2;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      if (parser.lp.lexeme && parser.lp.tok == parser.lp.cur) {
        parser.lp.cur++;
        goto start;
      }
      if (parser.lp.lexeme && parser.lp.lexeme < parser.lp.tok) {
        if (csvAddToken(&parser, parser.lp.lexeme, parser.lp.tok, NULL,
                        parser.cs_line, parser.cs_column, &ret)) goto error;
      }
      parser.lp.lexeme = NULL;
      if (csvAddCellSupport(&parser, ADD_CELL_ROW, &ret)) goto error;
      parser.use_quote = quote_notset;
      goto line_comment;
    }
yy25:
    ++parser.lp.cur;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      if (parser.lp.lexeme && parser.lp.lexeme < parser.lp.tok) {
        if (csvAddToken(&parser, parser.lp.lexeme, parser.lp.tok, NULL,
                        parser.cs_line, parser.cs_column, &ret)) goto error;
      }
      parser.lp.lexeme = NULL;
      goto block_comment;
    }
  }


  CSVUNREACHABLE();

instring:
  re2c_lparser_start_token(&parser.lp);
  
  {
    unsigned char yych;
    if ((parser.lp.lim - parser.lp.cur) < 3) { if (csv_fill(&parser, stream, 3) < 0) goto error; }
    yych = *parser.lp.cur;
    if (yych <= '\r') {
      if (yych <= '\t') {
        if (yych <= 0x00) goto yy27;
        if (yych <= 0x08) goto yy28;
        goto yy30;
      } else {
        if (yych <= '\n') goto yy31;
        if (yych <= '\f') goto yy28;
        goto yy33;
      }
    } else {
      if (yych <= '!') {
        if (yych == ' ') goto yy30;
        goto yy28;
      } else {
        if (yych <= '"') goto yy34;
        if (yych == '\\') goto yy35;
        goto yy28;
      }
    }
yy27:
    ++parser.lp.cur;
    {
      ret = CSV_ERR_EOF;
      goto error;
    }
yy28:
    ++parser.lp.cur;
yy29:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto instring;
    }
yy30:
    yych = *(parser.lp.mrk = ++parser.lp.cur);
    if (yych <= '\f') {
      if (yych <= 0x08) goto yy29;
      if (yych <= '\n') goto yy37;
      goto yy29;
    } else {
      if (yych <= '\r') goto yy37;
      if (yych == ' ') goto yy37;
      goto yy29;
    }
yy31:
    ++parser.lp.cur;
yy32:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto instring;
    }
yy33:
    yych = *++parser.lp.cur;
    if (yych == '\n') goto yy31;
    goto yy32;
yy34:
    yych = *++parser.lp.cur;
    if (yych == '"') goto yy39;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      tmp = unescapeCSVCellString(parser.lp.lexeme, parser.lp.tok, &n);
      if (!tmp) {
        ret = CSV_ERR_NOMEM;
        goto error;
      }
      parser.lp.lexeme = NULL;
      if (n > 0) {
        n--;
        if (csvAddToken(&parser, tmp, tmp + n, tmp,
                        parser.cs_line, parser.cs_column, &ret)) goto error;
      }
      goto start;
    }
yy35:
    yych = *++parser.lp.cur;
    if (yych == '"') goto yy39;
    goto yy29;
yy36:
    ++parser.lp.cur;
    if ((parser.lp.lim - parser.lp.cur) < 2) { if (csv_fill(&parser, stream, 2) < 0) goto error; }
    yych = *parser.lp.cur;
yy37:
    if (yych <= '\f') {
      if (yych <= 0x08) goto yy38;
      if (yych <= '\t') goto yy36;
      if (yych <= '\n') goto yy31;
    } else {
      if (yych <= '\r') goto yy33;
      if (yych == ' ') goto yy36;
    }
yy38:
    parser.lp.cur = parser.lp.mrk;
    goto yy29;
yy39:
    ++parser.lp.cur;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto instring;
    }
  }


  CSVUNREACHABLE();

line_comment:
  re2c_lparser_start_token(&parser.lp);
  
  {
    unsigned char yych;
    if ((parser.lp.lim - parser.lp.cur) < 3) { if (csv_fill(&parser, stream, 3) < 0) goto error; }
    yych = *parser.lp.cur;
    if (yych <= '\n') {
      if (yych <= 0x00) goto yy41;
      if (yych <= 0x08) goto yy42;
      if (yych <= '\t') goto yy44;
      goto yy45;
    } else {
      if (yych <= '\r') {
        if (yych <= '\f') goto yy42;
        goto yy47;
      } else {
        if (yych == ' ') goto yy44;
        goto yy42;
      }
    }
yy41:
    ++parser.lp.cur;
    {
      goto end;
    }
yy42:
    ++parser.lp.cur;
yy43:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto line_comment;
    }
yy44:
    yych = *(parser.lp.mrk = ++parser.lp.cur);
    if (yych <= '\f') {
      if (yych <= 0x08) goto yy43;
      if (yych <= '\n') goto yy49;
      goto yy43;
    } else {
      if (yych <= '\r') goto yy49;
      if (yych == ' ') goto yy49;
      goto yy43;
    }
yy45:
    ++parser.lp.cur;
yy46:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto start;
    }
yy47:
    yych = *++parser.lp.cur;
    if (yych == '\n') goto yy45;
    goto yy46;
yy48:
    ++parser.lp.cur;
    if ((parser.lp.lim - parser.lp.cur) < 2) { if (csv_fill(&parser, stream, 2) < 0) goto error; }
    yych = *parser.lp.cur;
yy49:
    if (yych <= '\f') {
      if (yych <= 0x08) goto yy50;
      if (yych <= '\t') goto yy48;
      if (yych <= '\n') goto yy45;
    } else {
      if (yych <= '\r') goto yy47;
      if (yych == ' ') goto yy48;
    }
yy50:
    parser.lp.cur = parser.lp.mrk;
    goto yy43;
  }


  CSVUNREACHABLE();

block_comment:
  re2c_lparser_start_token(&parser.lp);
  
  {
    unsigned char yych;
    if ((parser.lp.lim - parser.lp.cur) < 2) { if (csv_fill(&parser, stream, 2) < 0) goto error; }
    yych = *parser.lp.cur;
    if (yych <= 0x00) goto yy52;
    if (yych == '*') goto yy55;
    goto yy53;
yy52:
    ++parser.lp.cur;
    {
      ret = CSV_ERR_EOF;
      goto error;
    }
yy53:
    ++parser.lp.cur;
yy54:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto block_comment;
    }
yy55:
    yych = *++parser.lp.cur;
    if (yych != '/') goto yy54;
    ++parser.lp.cur;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto start;
    }
  }


  CSVUNREACHABLE();

continuing:
  re2c_lparser_start_token(&parser.lp);

  
  {
    unsigned char yych;
    if ((parser.lp.lim - parser.lp.cur) < 3) { if (csv_fill(&parser, stream, 3) < 0) goto error; }
    yych = *parser.lp.cur;
    if (yych <= '\r') {
      if (yych <= '\t') {
        if (yych <= 0x00) goto yy57;
        if (yych <= 0x08) goto yy58;
        goto yy60;
      } else {
        if (yych <= '\n') goto yy62;
        if (yych <= '\f') goto yy58;
        goto yy64;
      }
    } else {
      if (yych <= ',') {
        if (yych == ' ') goto yy60;
        goto yy58;
      } else {
        if (yych <= '-') goto yy65;
        if (yych == '/') goto yy66;
        goto yy58;
      }
    }
yy57:
    ++parser.lp.cur;
    {
      ret = CSV_ERR_EOF;
      goto error;
    }
yy58:
    ++parser.lp.cur;
yy59:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      ret = CSV_ERR_DATA_AFTER_CONT;
      goto error;
    }
yy60:
    yych = *(parser.lp.mrk = ++parser.lp.cur);
    if (yych <= '\f') {
      if (yych <= 0x08) goto yy61;
      if (yych <= '\n') goto yy68;
    } else {
      if (yych <= '\r') goto yy68;
      if (yych == ' ') goto yy68;
    }
yy61:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto continuing;
    }
yy62:
    ++parser.lp.cur;
yy63:
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto start;
    }
yy64:
    yych = *++parser.lp.cur;
    if (yych == '\n') goto yy62;
    goto yy63;
yy65:
    yych = *++parser.lp.cur;
    if (yych == '-') goto yy70;
    goto yy59;
yy66:
    yych = *++parser.lp.cur;
    if (yych == '*') goto yy71;
    goto yy59;
yy67:
    ++parser.lp.cur;
    if ((parser.lp.lim - parser.lp.cur) < 2) { if (csv_fill(&parser, stream, 2) < 0) goto error; }
    yych = *parser.lp.cur;
yy68:
    if (yych <= '\f') {
      if (yych <= 0x08) goto yy69;
      if (yych <= '\t') goto yy67;
      if (yych <= '\n') goto yy62;
    } else {
      if (yych <= '\r') goto yy64;
      if (yych == ' ') goto yy67;
    }
yy69:
    parser.lp.cur = parser.lp.mrk;
    goto yy61;
yy70:
    ++parser.lp.cur;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      goto line_comment;
    }
yy71:
    ++parser.lp.cur;
    {
      re2c_lparser_loc_upd_utf8(&parser.lp);
      ret = CSV_ERR_BLOCK_COMMENT_AFTER_CONT;
      goto error;
    }
  }


  CSVUNREACHABLE();

end:
  *data = parser.data;
  ret = CSV_ERR_SUCC;
  goto clean;

clean:
  re2c_lparser_clean(&parser.lp);
  {
    struct geom_list *lp, *ln, *lh;
    lh = &parser.token_head.list;
    geom_list_foreach_safe(lp, ln, lh) {
      struct csv_token *t;
      t = csv_token_entry(lp);
      free(t->start);
      free(t);
    }
  }
  return ret;

error:
  if (error_line) *error_line = parser.lp.tokline;
  if (error_col)  *error_col = parser.lp.tokcol;
  if (parser.lp.readerr) {
    ret = parser.lp.readerr;
  }
  freeCSV(parser.data);
  goto clean;
}

csv_column *getNextColumn(csv_column *c)
{
  struct geom_list *lp;

  if (!c) return NULL;

  lp = geom_list_next(&c->list);
  c = csv_column_entry(lp);
  if (!c->parent || c == &c->parent->column_head) return NULL;
  return c;
}

csv_row *getNextRow(csv_row *r)
{
  struct geom_list *lp;

  if (!r) return NULL;

  lp = geom_list_next(&r->list);
  r = csv_row_entry(lp);
  if (!r->parent || r == &r->parent->row_head) return NULL;
  return r;
}

csv_column *getPrevColumn(csv_column *c)
{
  struct geom_list *lp;

  if (!c) return NULL;

  lp = geom_list_prev(&c->list);
  c = csv_column_entry(lp);
  if (!c->parent || c == &c->parent->column_head) return NULL;
  return c;
}

csv_row *getPrevRow(csv_row *r)
{
  struct geom_list *lp;

  if (!r) return NULL;

  lp = geom_list_prev(&r->list);
  r = csv_row_entry(lp);
  if (!r->parent || r == &r->parent->row_head) return NULL;
  return r;
}

csv_row *getRowOfCSV(csv_data *d, int index)
{
  struct geom_list *lp;
  csv_row *r;

  CSVASSERT(d);

  r = &d->row_head;
  lp = &r->list;
  if (index >= 0) {
    lp = geom_list_next(lp);
    while (--index >= 0) {
      lp = geom_list_next(lp);
      if (lp == &r->list) break;
    }
  } else if (index < 0) {
    lp = geom_list_prev(lp);
    while (++index < 0) {
      lp = geom_list_prev(lp);
      if (lp == &r->list) break;
    }
  }
  if (lp == &r->list) return NULL;
  return csv_row_entry(lp);
}

csv_column *getColumnOfCSV(csv_row *d, int index)
{
  struct geom_list *lp;
  csv_column *r;

  CSVASSERT(d);

  r = &d->column_head;
  lp = &r->list;
  if (index >= 0) {
    lp = geom_list_next(lp);
    while (--index >= 0) {
      lp = geom_list_next(lp);
      if (lp == &r->list) break;
    }
  } else if (index < 0) {
    lp = geom_list_prev(lp);
    while (++index < 0) {
      lp = geom_list_prev(lp);
      if (lp == &r->list) break;
    }
  }
  if (lp == &r->list) return NULL;
  return csv_column_entry(lp);
}

const char *getCSVValue(csv_column *c)
{
  CSVASSERT(c);
  return c->value;
}

csv_error setCSVValue(csv_column *c, const char *text, size_t len)
{
  csv_data *data;
  char *t;

  CSVASSERT(c);
  CSVASSERT(c->parent);

  data = c->parent->parent;
  CSVASSERT(data);
  CSVASSERT(data->allocs);

  t = (char *)malloc(sizeof(char) * (len + 1));
  if (!t) return CSV_ERR_NOMEM;

  if (geom_alloc_add(data->allocs, t, free) != GEOM_SUCCESS) {
    return CSV_ERR_NOMEM;
  }

  strncpy(t, text, len);
  t[len] = '\0';

  c->value = t;

  return CSV_ERR_SUCC;
}

long getCSVTextLineOrigin(csv_column *c)
{
  if (!c) return -1;
  return c->line;
}

long getCSVTextColumnOrigin(csv_column *c)
{
  if (!c) return -1;
  return c->cols;
}

void setCSVTextOrigin(csv_column *col, long l, long c)
{
  if (!col) return;
  col->line = l;
  col->cols = c;
}

csv_row *findCSVRow(csv_data *d, const char *keystr, int len)
{
  unsigned long l;
  struct geom_list *lp, *lh;
  csv_row *r;
  const char *c;

  CSVASSERT(d);
  CSVASSERT(keystr);
  CSVASSERT(len >= 0);

  l = hashCSVKey(keystr, len);
  lp = &d->rowtable[l];
  lh = lp;
  geom_list_foreach(lp, lh) {
    r = csv_row_hash_entry(lp);
    c = getCSVRowKey(r);
    if (c) {
      if (strncmp(c, keystr, len) == 0) {
        return r;
      }
    }
  }
  return NULL;
}

csv_row *findCSVRowNext(csv_row *o)
{
  unsigned long l;
  csv_data *d;
  csv_row *r;
  const char *c;
  const char *keystr;
  struct geom_list *lp, *ls, *lh;
  int len;

  CSVASSERT(o);

  d = o->parent;

  CSVASSERT(d);

  keystr = getCSVRowKey(o);

  CSVASSERT(keystr);

  len = strlen(keystr) + 1;
  l = hashCSVKey(keystr, len);

  lh = &d->rowtable[l];
  ls = geom_list_next(&o->hash_list);
  geom_list_foreach_range(lp, ls, lh) {
    r = csv_row_hash_entry(lp);
    c = getCSVRowKey(o);
    if (c) {
      if (strncmp(c, keystr, len) == 0) {
        return r;
      }
    }
  }
  return NULL;
}

void dumpCSV(FILE *stream, csv_data *t) {
  csv_row *r;
  csv_column *c;
  const char *cc;
  int ir, ic;

  ir = 1;
  r = getRowOfCSV(t, 0);
  while (r) {
    ic = 1;
    c = getColumnOfCSV(r, 0);
    fprintf(stream, "# -------------------------------------------------\n");
    fprintf(stream, "# CSVRow:CSVCol:TxtLno:TxtCol:HV:Cell\n");
    fprintf(stream, "# -------------------------------------------------\n");
    while (c) {
      cc = getCSVValue(c);
      fprintf(stream, "# %6d:%6d:%6ld:%6ld:%02lx:%s:\n",
              ir, ic,
              getCSVTextLineOrigin(c),
              getCSVTextColumnOrigin(c),
              hashCSVKey(cc, strlen(cc)), cc);
      c = getNextColumn(c);
      ic++;
    }
    r = getNextRow(r);
    ir++;
  }
  fprintf(stream, "# -------------------------------------------------\n");
}

