/* Generated by re2c 4.5 */
/* This is -*- c -*- source */
/* This is vim: set ft=c: source */

#ifdef JUPITER_MPI
#include <mpi.h>
#endif

#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <ctype.h>
#include <stdarg.h>

#include "csv.h"
#include "geometry/bitarray.h"
#include "optparse.h"
#include "csvutil.h"
#include "os/asprintf.h"



static int accept_decimal(int v, int digit, int errval)
{
  if (v < 0 || v == errval)
    return errval;
  if (v < INT_MAX / 10)
    return v * 10 + digit;
  if (v <= INT_MAX / 10) {
    v *= 10;
    if (v <= INT_MAX - digit)
      return v + digit;
  }
  return errval;
}

static int accept_decimalc(int v, char ch, int errval)
{
  char buf[2] = { ch, '\0' };
  const char *cursor = buf;
  
  {
    unsigned char yych;
    yych = *cursor;
    switch (yych) {
      case '0': goto yy2;
      case '1': goto yy3;
      case '2': goto yy4;
      case '3': goto yy5;
      case '4': goto yy6;
      case '5': goto yy7;
      case '6': goto yy8;
      case '7': goto yy9;
      case '8': goto yy10;
      case '9': goto yy11;
      default: goto yy1;
    }
yy1:
    ++cursor;
    { return errval; }
yy2:
    ++cursor;
    { return accept_decimal(v, 0, errval); }
yy3:
    ++cursor;
    { return accept_decimal(v, 1, errval); }
yy4:
    ++cursor;
    { return accept_decimal(v, 2, errval); }
yy5:
    ++cursor;
    { return accept_decimal(v, 3, errval); }
yy6:
    ++cursor;
    { return accept_decimal(v, 4, errval); }
yy7:
    ++cursor;
    { return accept_decimal(v, 5, errval); }
yy8:
    ++cursor;
    { return accept_decimal(v, 6, errval); }
yy9:
    ++cursor;
    { return accept_decimal(v, 7, errval); }
yy10:
    ++cursor;
    { return accept_decimal(v, 8, errval); }
yy11:
    ++cursor;
    { return accept_decimal(v, 9, errval); }
  }

  CSVUNREACHABLE();
  return errval;
}

/**
 * @brief Makes plural form of `noun` (in English)
 * @param buf pointer to store result
 * @param noun Noun to make singular (a/an -) or plural (-s)
 * @param num Number for `noun`
 * @param cap 0 to leave the first charactor in lower case. Otherwise
 *        capiterlize.
 * @return number of bytes written, or -1 if error (allocation failed).
 *
 * Genereted string must be freed by `free()`.
 *
 * Nouns which transform illegally (such as 'datum', 'phenomenon',
 * 'mouse', etc.) are not supported.
 *
 * If the leading charactor of noun is ASCII symbols or numerals (such
 * as '!', '$'), the usage of 'a' or 'an' is determined its reading.
 * (for example, '!' (exclamation mark) will be 'an !', ':' (colon)
 * will be 'a :', '0' (zero) will be 'a 0')
 *
 * Non-ASCII charactors are considered non-vowel.
 *
 * Examples:
 * - (&buf, "cake", 1, 1) // -> "A cake"
 * - (&buf, "cake", 1, 0) // -> "a cake"
 * - (&buf, "cake", 2, 1) // -> "2 cakes"
 * - (&buf, "cake", 2, 0) // -> "2 cakes"
 * - (&buf, "cake", 100, 0) // -> "100 cakes"
 * - (&buf, "apple", 1, 1) // -> "An apple"
 * - (&buf, "apple", 0, 1) // -> "No apples"
 * - (&buf, "  apple", 0, 0) // -> "no apples" (leading spaces will be removed)
 * - (&buf, "city", 10, 0)  // -> "10 cities"
 */
static int jupiter_make_nplural(char **buf, const char *noun, int num, int cap)
{
  int is_vowel = 0;
  const char *cursor;
  const char *token;
  const char *tail;
  const char *lim;
  const char *marker;
  const char *ctx_marker;
  ptrdiff_t ns;

  CSVASSERT(num >= 0);

  cursor = noun;
  for (;;) {
    token = cursor;
    
    {
      unsigned char yych;
      yych = *cursor;
      if (yych <= '\f') {
        if (yych <= 0x08) goto yy13;
        if (yych <= '\n') goto yy14;
      } else {
        if (yych <= '\r') goto yy14;
        if (yych == ' ') goto yy14;
      }
yy13:
      ++cursor;
      { break; }
yy14:
      ++cursor;
      { continue; }
    }

    CSVUNREACHABLE();
  }

  if (num != 1) {
    noun = token;
    cursor = noun;
    for (;;) {
      token = cursor;
      lim = cursor;
      
      {
        unsigned char yych;
        yych = *cursor;
        if (yych <= 'U') {
          if (yych <= 'C') {
            if (yych <= '\r') {
              if (yych <= 0x08) {
                if (yych >= 0x01) goto yy17;
              } else {
                if (yych <= '\n') goto yy19;
                if (yych <= '\f') goto yy17;
                goto yy19;
              }
            } else {
              if (yych <= ' ') {
                if (yych <= 0x1F) goto yy17;
                goto yy19;
              } else {
                if (yych <= 'A') goto yy17;
                if (yych <= 'B') goto yy20;
                goto yy21;
              }
            }
          } else {
            if (yych <= 'I') {
              if (yych <= 'E') {
                if (yych <= 'D') goto yy20;
                goto yy17;
              } else {
                if (yych <= 'F') goto yy22;
                if (yych <= 'H') goto yy20;
                goto yy17;
              }
            } else {
              if (yych <= 'R') {
                if (yych == 'O') goto yy17;
                goto yy20;
              } else {
                if (yych <= 'S') goto yy23;
                if (yych <= 'T') goto yy20;
                goto yy17;
              }
            }
          }
        } else {
          if (yych <= 'h') {
            if (yych <= 'b') {
              if (yych <= 'X') {
                if (yych <= 'W') goto yy20;
                goto yy24;
              } else {
                if (yych <= 'Z') goto yy20;
                if (yych <= 'a') goto yy17;
                goto yy20;
              }
            } else {
              if (yych <= 'd') {
                if (yych <= 'c') goto yy21;
                goto yy20;
              } else {
                if (yych <= 'e') goto yy17;
                if (yych <= 'f') goto yy22;
                goto yy20;
              }
            }
          } else {
            if (yych <= 's') {
              if (yych <= 'n') {
                if (yych <= 'i') goto yy17;
                goto yy20;
              } else {
                if (yych <= 'o') goto yy17;
                if (yych <= 'r') goto yy20;
                goto yy23;
              }
            } else {
              if (yych <= 'w') {
                if (yych == 'u') goto yy17;
                goto yy20;
              } else {
                if (yych <= 'x') goto yy24;
                if (yych <= 'z') goto yy20;
                goto yy17;
              }
            }
          }
        }
yy16:
        ++cursor;
        { tail = "s"; break; }
yy17:
        ++cursor;
yy18:
        { continue; }
yy19:
        yych = *(marker = ++cursor);
        if (yych <= '\f') {
          if (yych <= 0x00) goto yy16;
          if (yych <= 0x08) goto yy18;
          if (yych <= '\n') goto yy25;
          goto yy18;
        } else {
          if (yych <= '\r') goto yy25;
          if (yych == ' ') goto yy25;
          goto yy18;
        }
yy20:
        yych = *(marker = ++cursor);
        if (yych <= 'Y') {
          if (yych == 'O') goto yy27;
          if (yych <= 'X') goto yy18;
          goto yy28;
        } else {
          if (yych <= 'o') {
            if (yych <= 'n') goto yy18;
            goto yy27;
          } else {
            if (yych == 'y') goto yy28;
            goto yy18;
          }
        }
yy21:
        yych = *(marker = ++cursor);
        if (yych <= 'Y') {
          if (yych <= 'N') {
            if (yych == 'H') goto yy29;
            goto yy18;
          } else {
            if (yych <= 'O') goto yy27;
            if (yych <= 'X') goto yy18;
            goto yy28;
          }
        } else {
          if (yych <= 'n') {
            if (yych == 'h') goto yy29;
            goto yy18;
          } else {
            if (yych <= 'o') goto yy27;
            if (yych == 'y') goto yy28;
            goto yy18;
          }
        }
yy22:
        yych = *(marker = ++cursor);
        if (yych <= 'N') {
          if (yych <= '\r') {
            if (yych <= 0x08) {
              if (yych <= 0x00) {
                ctx_marker = cursor;
                goto yy30;
              }
              goto yy18;
            } else {
              if (yych <= '\n') {
                ctx_marker = cursor;
                goto yy31;
              }
              if (yych <= '\f') goto yy18;
              ctx_marker = cursor;
              goto yy31;
            }
          } else {
            if (yych <= ' ') {
              if (yych <= 0x1F) goto yy18;
              ctx_marker = cursor;
              goto yy31;
            } else {
              if (yych == 'E') {
                ctx_marker = cursor;
                goto yy31;
              }
              goto yy18;
            }
          }
        } else {
          if (yych <= 'e') {
            if (yych <= 'X') {
              if (yych <= 'O') goto yy27;
              goto yy18;
            } else {
              if (yych <= 'Y') goto yy28;
              if (yych <= 'd') goto yy18;
              ctx_marker = cursor;
              goto yy31;
            }
          } else {
            if (yych <= 'o') {
              if (yych <= 'n') goto yy18;
              goto yy27;
            } else {
              if (yych == 'y') goto yy28;
              goto yy18;
            }
          }
        }
yy23:
        yych = *(marker = ++cursor);
        if (yych <= 'N') {
          if (yych <= '\r') {
            if (yych <= 0x08) {
              if (yych <= 0x00) {
                ctx_marker = cursor;
                goto yy32;
              }
              goto yy18;
            } else {
              if (yych <= '\n') {
                ctx_marker = cursor;
                goto yy33;
              }
              if (yych <= '\f') goto yy18;
              ctx_marker = cursor;
              goto yy33;
            }
          } else {
            if (yych <= ' ') {
              if (yych <= 0x1F) goto yy18;
              ctx_marker = cursor;
              goto yy33;
            } else {
              if (yych == 'H') goto yy29;
              goto yy18;
            }
          }
        } else {
          if (yych <= 'h') {
            if (yych <= 'X') {
              if (yych <= 'O') goto yy27;
              goto yy18;
            } else {
              if (yych <= 'Y') goto yy28;
              if (yych <= 'g') goto yy18;
              goto yy29;
            }
          } else {
            if (yych <= 'o') {
              if (yych <= 'n') goto yy18;
              goto yy27;
            } else {
              if (yych == 'y') goto yy28;
              goto yy18;
            }
          }
        }
yy24:
        yych = *(marker = ++cursor);
        if (yych <= 'N') {
          if (yych <= '\f') {
            if (yych <= 0x00) {
              ctx_marker = cursor;
              goto yy32;
            }
            if (yych <= 0x08) goto yy18;
            if (yych <= '\n') {
              ctx_marker = cursor;
              goto yy33;
            }
            goto yy18;
          } else {
            if (yych <= '\r') {
              ctx_marker = cursor;
              goto yy33;
            }
            if (yych == ' ') {
              ctx_marker = cursor;
              goto yy33;
            }
            goto yy18;
          }
        } else {
          if (yych <= 'n') {
            if (yych <= 'O') goto yy27;
            if (yych == 'Y') goto yy28;
            goto yy18;
          } else {
            if (yych <= 'o') goto yy27;
            if (yych == 'y') goto yy28;
            goto yy18;
          }
        }
yy25:
        yych = *++cursor;
        if (yych <= '\f') {
          if (yych <= 0x00) goto yy16;
          if (yych <= 0x08) goto yy26;
          if (yych <= '\n') goto yy25;
        } else {
          if (yych <= '\r') goto yy25;
          if (yych == ' ') goto yy25;
        }
yy26:
        cursor = marker;
        goto yy18;
yy27:
        yych = *++cursor;
        if (yych <= '\f') {
          if (yych <= 0x00) {
            ctx_marker = cursor;
            goto yy34;
          }
          if (yych <= 0x08) goto yy26;
          if (yych <= '\n') {
            ctx_marker = cursor;
            goto yy35;
          }
          goto yy26;
        } else {
          if (yych <= '\r') {
            ctx_marker = cursor;
            goto yy35;
          }
          if (yych == ' ') {
            ctx_marker = cursor;
            goto yy35;
          }
          goto yy26;
        }
yy28:
        yych = *++cursor;
        if (yych <= '\f') {
          if (yych <= 0x00) {
            ctx_marker = cursor;
            goto yy36;
          }
          if (yych <= 0x08) goto yy26;
          if (yych <= '\n') {
            ctx_marker = cursor;
            goto yy37;
          }
          goto yy26;
        } else {
          if (yych <= '\r') {
            ctx_marker = cursor;
            goto yy37;
          }
          if (yych == ' ') {
            ctx_marker = cursor;
            goto yy37;
          }
          goto yy26;
        }
yy29:
        yych = *++cursor;
        if (yych <= '\f') {
          if (yych <= 0x00) {
            ctx_marker = cursor;
            goto yy38;
          }
          if (yych <= 0x08) goto yy26;
          if (yych <= '\n') {
            ctx_marker = cursor;
            goto yy39;
          }
          goto yy26;
        } else {
          if (yych <= '\r') {
            ctx_marker = cursor;
            goto yy39;
          }
          if (yych == ' ') {
            ctx_marker = cursor;
            goto yy39;
          }
          goto yy26;
        }
yy30:
        ++cursor;
        cursor = ctx_marker;
        { tail = "ves"; lim = cursor - 1; break; }
yy31:
        yych = *++cursor;
        if (yych <= '\f') {
          if (yych <= 0x00) goto yy30;
          if (yych <= 0x08) goto yy26;
          if (yych <= '\n') goto yy31;
          goto yy26;
        } else {
          if (yych <= '\r') goto yy31;
          if (yych == ' ') goto yy31;
          goto yy26;
        }
yy32:
        ++cursor;
        cursor = ctx_marker;
        { tail = "es"; lim = cursor; break; }
yy33:
        yych = *++cursor;
        if (yych <= '\f') {
          if (yych <= 0x00) goto yy32;
          if (yych <= 0x08) goto yy26;
          if (yych <= '\n') goto yy33;
          goto yy26;
        } else {
          if (yych <= '\r') goto yy33;
          if (yych == ' ') goto yy33;
          goto yy26;
        }
yy34:
        ++cursor;
        cursor = ctx_marker;
        { tail = "es"; lim = cursor; break; }
yy35:
        yych = *++cursor;
        if (yych <= '\f') {
          if (yych <= 0x00) goto yy34;
          if (yych <= 0x08) goto yy26;
          if (yych <= '\n') goto yy35;
          goto yy26;
        } else {
          if (yych <= '\r') goto yy35;
          if (yych == ' ') goto yy35;
          goto yy26;
        }
yy36:
        ++cursor;
        cursor = ctx_marker;
        { tail = "ies"; lim = cursor - 1; break; }
yy37:
        yych = *++cursor;
        if (yych <= '\f') {
          if (yych <= 0x00) goto yy36;
          if (yych <= 0x08) goto yy26;
          if (yych <= '\n') goto yy37;
          goto yy26;
        } else {
          if (yych <= '\r') goto yy37;
          if (yych == ' ') goto yy37;
          goto yy26;
        }
yy38:
        ++cursor;
        cursor = ctx_marker;
        { tail = "es"; lim = cursor; break; }
yy39:
        yych = *++cursor;
        if (yych <= '\f') {
          if (yych <= 0x00) goto yy38;
          if (yych <= 0x08) goto yy26;
          if (yych <= '\n') goto yy39;
          goto yy26;
        } else {
          if (yych <= '\r') goto yy39;
          if (yych == ' ') goto yy39;
          goto yy26;
        }
      }

    }
    ns = lim - noun;

    if (num == 0) {
      return jupiter_asprintf(buf, "%s %.*s%s",
                              cap ? "No" : "no", ns, noun, tail);
    } else {
      return jupiter_asprintf(buf, "%d %.*s%s",
                              num, ns, noun, tail);
    }
  } else {
    cursor = noun;
    for (;;) {
      
      {
        unsigned char yych;
        yych = *cursor;
        if (yych <= 'N') {
          if (yych <= '7') {
            if (yych <= '&') {
              if (yych <= ' ') {
                if (yych >= 0x01) goto yy41;
              } else {
                if (yych <= '!') goto yy42;
                if (yych <= '%') goto yy43;
                goto yy42;
              }
            } else {
              if (yych <= ')') {
                if (yych <= '\'') goto yy41;
                goto yy43;
              } else {
                if (yych <= '+') goto yy41;
                if (yych <= '/') goto yy43;
                goto yy44;
              }
            }
          } else {
            if (yych <= 'A') {
              if (yych <= '9') {
                if (yych <= '8') goto yy45;
                goto yy44;
              } else {
                if (yych <= '?') goto yy43;
                if (yych <= '@') goto yy42;
                goto yy46;
              }
            } else {
              if (yych <= 'E') {
                if (yych <= 'D') goto yy47;
                goto yy46;
              } else {
                if (yych == 'I') goto yy46;
                goto yy47;
              }
            }
          }
        } else {
          if (yych <= 'd') {
            if (yych <= ']') {
              if (yych <= 'T') {
                if (yych <= 'O') goto yy46;
                goto yy47;
              } else {
                if (yych <= 'U') goto yy46;
                if (yych <= 'Z') goto yy47;
                goto yy48;
              }
            } else {
              if (yych <= '_') {
                if (yych <= '^') goto yy43;
                goto yy42;
              } else {
                if (yych <= '`') goto yy43;
                if (yych <= 'a') goto yy46;
                goto yy47;
              }
            }
          } else {
            if (yych <= 'o') {
              if (yych <= 'h') {
                if (yych <= 'e') goto yy46;
                goto yy47;
              } else {
                if (yych <= 'i') goto yy46;
                if (yych <= 'n') goto yy47;
                goto yy46;
              }
            } else {
              if (yych <= 'u') {
                if (yych <= 't') goto yy47;
                goto yy46;
              } else {
                if (yych <= 'z') goto yy47;
                if (yych <= '~') goto yy43;
                goto yy41;
              }
            }
          }
        }
        ++cursor;
        { is_vowel = 0; break; }
yy41:
        ++cursor;
        { is_vowel = 0; break; }
yy42:
        ++cursor;
        { is_vowel = 1; break; }
yy43:
        ++cursor;
        { is_vowel = 0; break; }
yy44:
        ++cursor;
        { is_vowel = 0; break; }
yy45:
        ++cursor;
        { is_vowel = 1; break; }
yy46:
        ++cursor;
        { is_vowel = 1; break; }
yy47:
        ++cursor;
        { is_vowel = 0; break; }
yy48:
        ++cursor;
        { is_vowel = 0; break; }
      }

      CSVUNREACHABLE();
    }
    return jupiter_asprintf(buf, "%c%s %s",
                            cap ? 'A' : 'a',
                            is_vowel ? "n" : "", noun);
  }
  CSVUNREACHABLE();
}

/**
 * @brief Parses integer value
 * @param ret Pointer to the memory where should be stored the result
 * @param string Parsing string
 * @param argflg Command line flag name which is being parsed
 */
static int jupiter_parse_int(int *ret, const char *string, const char *argflg)
{
  const char *token;
  const char *cursor;

  unsigned int intv;
  unsigned int intm;
  int sint;
  int neg;

  CSVASSERT(ret);
  CSVASSERT(string);

  cursor = string;

  neg = 0;
  for (;;) {
    token = cursor;
    
      {
        unsigned char yych;
        yych = *cursor;
        if (yych <= 0x1F) {
          if (yych <= '\n') {
            if (yych <= 0x00) goto yy50;
            if (yych <= 0x08) goto yy51;
            goto yy52;
          } else {
            if (yych == '\r') goto yy52;
            goto yy51;
          }
        } else {
          if (yych <= '+') {
            if (yych <= ' ') goto yy52;
            if (yych <= '*') goto yy51;
            goto yy53;
          } else {
            if (yych == '-') goto yy54;
            goto yy51;
          }
        }
yy50:
        ++cursor;
        { goto empty; }
yy51:
        ++cursor;
        { cursor = token; break; }
yy52:
        ++cursor;
        { continue; }
yy53:
        ++cursor;
        { neg = 0; break; }
yy54:
        ++cursor;
        { neg = 1; break; }
      }

    CSVUNREACHABLE();
  }

  for (;;) {
    token = cursor;
    
      {
        unsigned char yych;
        yych = *cursor;
        if (yych <= 0x1F) {
          if (yych <= 0x00) goto yy56;
          if (yych == '\t') goto yy58;
          goto yy57;
        } else {
          if (yych <= ' ') goto yy58;
          if (yych <= '/') goto yy57;
          if (yych <= '9') goto yy59;
          goto yy57;
        }
yy56:
        ++cursor;
        { goto empty; }
yy57:
        ++cursor;
        { goto invalid_int; }
yy58:
        ++cursor;
        { continue; }
yy59:
        ++cursor;
        { cursor = token; break; }
      }

  }

  string = token;
  intv = 0;
  for (;;) {
    token = cursor;
    
      {
        unsigned char yych;
        yych = *cursor;
        if (yych <= 0x00) goto yy61;
        if (yych <= '/') goto yy62;
        if (yych <= '9') goto yy63;
        goto yy62;
yy61:
        ++cursor;
        { break; }
yy62:
        ++cursor;
        { goto invalid_int; }
yy63:
        ++cursor;
        { goto decimal_token; }
      }

    CSVUNREACHABLE();

  decimal_token:
    intv = accept_decimalc(intv, *token, -1);
    if (intv < 0)
      goto int_overflow;
    sint = intv;
    if (sint < 0 || (unsigned int)sint != intv) goto int_overflow;
    continue;

  invalid_int:
    if (isprint(*token)) {
      csvperrorf("<command line>", 0, 0, CSV_EL_ERROR,
                 argflg, "Invalid integer charactor: '%c' of `%s`",
                 *token, string);
    } else {
      csvperrorf("<command line>", 0, 0, CSV_EL_ERROR,
                 argflg, "Invalid integer charactor: '\\x%02x'", *token);
    }
    return -1;

  int_overflow:
    csvperrorf("<command line>", 0, 0, CSV_EL_ERROR,
               argflg, "Too large integer value: %s", string);
    return -1;

  empty:
    csvperrorf("<command line>", 0, 0, CSV_EL_ERROR,
               argflg, "No decimal value found");
    return -1;
  }

  if (neg) {
    sint = -sint;
  }

  *ret = sint;
  return 0;
}

/**
 * @brief Parses integers on command line
 * @param argflg Command line flag name which is being parsed
 * @param argc size of argv
 * @param argv array of command line argument
 * @param num number of integers (must be constant)
 * @param ... pointer to int where store the result
 * @return number of arguments consumed on argv, 0 when error.
 *
 * argv must point the first element which will be parsed,
 * and argc must be number of available number of arguments.
 *
 * For example, if original argv is
 * ```
 *   argv[0]  =  "../jupiter/run";
 *   argv[1]  =  "-input";
 *   argv[2]  =  "params.txt";
 *   argv[3]  =  "-post";
 *   argv[4]  =  "2";
 *   argv[5]  =  "5";
 *   argv[6]  =  "-flags";
 *   argv[7]  =  "flags.txt";
 * ```
 * and argc == 8, argument of this function will be for "-post" argument
 * will be 4 for argc and &argv[4] for argv.
 * ```
 *   jupiter_parse_int_array("-post", 4, &argv[4], 2,
 *                           &opts->post_s, &opts->post_e);
 * ```
 */
static int jupiter_parse_int_array(const char *argflg, int argc, char **argv,
                                   int num, ...)
{
  int r;
  int *retp;
  int i;
  va_list ap;
  char *buf;
  const char *msg;

  r = 0;

  va_start(ap, num);
  for (i = 0; i < num && i < argc; ++i) {
    retp = va_arg(ap, int*);
    CSVASSERT(retp);
    r = jupiter_parse_int(retp, argv[i], argflg);
    if (r != 0) break;
  }
  va_end(ap);

  if (r == 0 && i != num) {
    r = jupiter_make_nplural(&buf, "integer value", num, 1);
    if (r >= 0) {
      msg = buf;
    } else {
      buf = NULL;
      msg = "Integer value(s)";
    }
    csvperrorf("<command line>", 0, 0, CSV_EL_ERROR,
               NULL, "%s required after `%s`", msg, argflg);
    free(buf);
    r = 1;
  }
  if (r != 0) {
    return 0;
  }
  return i;
}

/**
 * Examples:
 *
 * - `0`: print on rank 0, no print on others, by default levels
 *
 * - `all`: print on all ranks by default levels
 *
 * - `*`  : print on all ranks by defualt levels
 *
 * - `0:+all`:
 *   - print on rank 0 with all levels, not print on others
 *
 * - `0:-warn`
 *   - print on rank 0 by default levels but not warnings, no print on others
 *
 * - `0:-all+fatal,1:all`
 *   - print on rank 0 with fatals only, print on rank 1 with all levels,
 *     no print on others
 *
 * - `all:-all,0:+all-debug`
 *   - print on rank 0 without debugs, no print on others
 *     (explicitly specified, equivalent to default)
 *
 * - `2..5`
 *   - print on rank 2 to 5 by default levels.
 */
static csv_error jupiter_parse_print_rank(const char *arg,
                                          const char *flg, int *print_my_rank,
                                          jupiter_print_levels *levels)
{
  const char *t1, *t2;
  const char *cursor;
  const char *marker;
  csv_error_level lvl = CSV_EL_MAX;
  int ret;
  int srank;
  int erank;
  int print_rank = 0;
  int apply_rank = 0;
  int myrank = 0;
#ifdef JUPITER_MPI
  int inited = 0;
#endif
  const int rankerrval = -2;

#ifdef JUPITER_MPI
  MPI_Initialized(&inited);
  if (inited)
    MPI_Comm_rank(MPI_COMM_WORLD, &myrank);
#endif

  cursor = arg;
  for (;;) {
    lvl = CSV_EL_MAX;
    srank = rankerrval;
    erank = rankerrval;
    ret = 1;
    /* parse start rank */
    for (;;) {
      t1 = cursor;
      
      {
        unsigned char yych;
        yych = *cursor;
        if (yych <= '/') {
          if (yych <= '*') {
            if (yych <= 0x00) goto yy65;
            if (yych <= ')') goto yy66;
            goto yy68;
          } else {
            if (yych == '.') goto yy69;
            goto yy66;
          }
        } else {
          if (yych <= '@') {
            if (yych <= '0') goto yy70;
            if (yych <= '9') goto yy71;
            goto yy66;
          } else {
            if (yych <= 'A') goto yy72;
            if (yych == 'a') goto yy72;
            goto yy66;
          }
        }
yy65:
        ++cursor;
        { goto end; }
yy66:
        ++cursor;
yy67:
        { goto invalid_rank; }
yy68:
        yych = *++cursor;
        if (yych == ':') goto yy73;
        goto yy67;
yy69:
        yych = *++cursor;
        if (yych == '.') goto yy74;
        goto yy67;
yy70:
        yych = *(marker = ++cursor);
        if (yych <= '.') {
          if (yych <= 0x00) goto yy75;
          if (yych <= '-') goto yy67;
          goto yy76;
        } else {
          if (yych == ':') goto yy78;
          goto yy67;
        }
yy71:
        ++cursor;
        { cursor = t1; srank = 0; goto nums; }
yy72:
        yych = *(marker = ++cursor);
        if (yych == 'L') goto yy79;
        if (yych == 'l') goto yy79;
        goto yy67;
yy73:
        ++cursor;
        { srank = -1; erank = -1; goto parse_levels; }
yy74:
        ++cursor;
        { srank = -1; break; }
yy75:
        ++cursor;
        cursor -= 1;
        { srank = 0; erank = 0; goto parse_levels; }
yy76:
        yych = *++cursor;
        if (yych == '.') goto yy80;
yy77:
        cursor = marker;
        goto yy67;
yy78:
        ++cursor;
        { srank = 0; erank = 0; goto parse_levels; }
yy79:
        yych = *++cursor;
        if (yych == 'L') goto yy81;
        if (yych == 'l') goto yy81;
        goto yy77;
yy80:
        ++cursor;
        { srank = 0; break; }
yy81:
        yych = *++cursor;
        if (yych == ':') goto yy73;
        goto yy77;
      }

      CSVUNREACHABLE();

    nums:
      for (;;) {
        t2 = cursor;
        
        {
          unsigned char yych;
          yych = *cursor;
          if (yych <= '.') {
            if (yych <= 0x00) goto yy83;
            if (yych <= '-') goto yy84;
            goto yy86;
          } else {
            if (yych <= '/') goto yy84;
            if (yych <= '9') goto yy87;
            if (yych <= ':') goto yy88;
            goto yy84;
          }
yy83:
          ++cursor;
          { cursor = t2; break; }
yy84:
          ++cursor;
yy85:
          { goto invalid_rank; }
yy86:
          yych = *++cursor;
          if (yych == '.') goto yy89;
          goto yy85;
yy87:
          ++cursor;
          { goto digit_s; }
yy88:
          ++cursor;
          { erank = srank; goto parse_levels; }
yy89:
          ++cursor;
          { break; }
        }

        CSVUNREACHABLE();

      digit_s:
        srank = accept_decimalc(srank, *t2, -2);
        if (srank < 0)
          goto int_overflow;
        continue;
      }
      break;
    }
    /* parse end rank */
    for (;;) {
      t1 = cursor;
      
      {
        unsigned char yych;
        yych = *cursor;
        if (yych <= '0') {
          if (yych <= 0x00) goto yy91;
          if (yych <= '/') goto yy92;
          goto yy94;
        } else {
          if (yych <= '9') goto yy95;
          if (yych <= ':') goto yy96;
          goto yy92;
        }
yy91:
        ++cursor;
        { if (erank < -1) erank = srank; cursor = t1; break; }
yy92:
        ++cursor;
yy93:
        { goto invalid_rank; }
yy94:
        yych = *++cursor;
        if (yych <= 0x00) goto yy97;
        if (yych == ':') goto yy98;
        goto yy93;
yy95:
        ++cursor;
        { cursor = t1; erank = 0; goto nume; }
yy96:
        ++cursor;
        { if (erank < -1) erank = srank; break; }
yy97:
        ++cursor;
        cursor -= 1;
        { erank = 0; break; }
yy98:
        ++cursor;
        { erank = 0; break; }
      }

      CSVUNREACHABLE();

    nume:
      for (;;) {
        t2 = cursor;
        
        {
          unsigned char yych;
          yych = *cursor;
          if (yych <= 0x00) goto yy100;
          if (yych <= '/') goto yy101;
          if (yych <= '9') goto yy102;
          if (yych <= ':') goto yy103;
          goto yy101;
yy100:
          ++cursor;
          { cursor = t2; break; }
yy101:
          ++cursor;
          { goto invalid_rank; }
yy102:
          ++cursor;
          { goto digit_e; }
yy103:
          ++cursor;
          { goto parse_levels; }
        }

        CSVUNREACHABLE();

      digit_e:
        erank = accept_decimalc(erank, *t2, -2);
        if (erank < 0)
          goto int_overflow;
        continue;
      }
    }
  parse_levels:
    if (srank < -1 || erank < -1)
      goto invalid_rank;
    apply_rank = 0;
    if (srank <= -1 && myrank <= erank) {
      apply_rank = 1;
    } else if (erank <= -1 && myrank >= srank) {
      apply_rank = 1;
    } else if (srank <= myrank && myrank <= erank) {
      apply_rank = 1;
    }
    if (apply_rank)
      print_rank = 1;
    for (;;) {
      t1 = cursor;
      
      {
        unsigned char yych;
        yych = *cursor;
        if (yych <= '+') {
          if (yych <= 0x00) goto yy105;
          if (yych <= '*') goto yy106;
          goto yy108;
        } else {
          if (yych <= ',') goto yy109;
          if (yych <= '-') goto yy110;
          goto yy106;
        }
yy105:
        ++cursor;
        { cursor = t1; break; }
yy106:
        ++cursor;
yy107:
        { goto invalid_level; }
yy108:
        yych = *(marker = ++cursor);
        if (yych <= 'I') {
          if (yych <= '@') {
            if (yych <= '*') {
              if (yych <= 0x00) goto yy111;
              if (yych <= ')') goto yy107;
              goto yy112;
            } else {
              if (yych == ',') goto yy113;
              goto yy107;
            }
          } else {
            if (yych <= 'D') {
              if (yych <= 'A') goto yy114;
              if (yych <= 'C') goto yy107;
              goto yy116;
            } else {
              if (yych <= 'E') goto yy117;
              if (yych <= 'F') goto yy118;
              if (yych <= 'H') goto yy107;
              goto yy119;
            }
          }
        } else {
          if (yych <= 'd') {
            if (yych <= '`') {
              if (yych == 'W') goto yy120;
              goto yy107;
            } else {
              if (yych <= 'a') goto yy114;
              if (yych <= 'c') goto yy107;
              goto yy116;
            }
          } else {
            if (yych <= 'h') {
              if (yych <= 'e') goto yy117;
              if (yych <= 'f') goto yy118;
              goto yy107;
            } else {
              if (yych <= 'i') goto yy119;
              if (yych == 'w') goto yy120;
              goto yy107;
            }
          }
        }
yy109:
        ++cursor;
        { break; }
yy110:
        yych = *(marker = ++cursor);
        if (yych <= 'I') {
          if (yych <= '@') {
            if (yych <= '*') {
              if (yych <= 0x00) goto yy121;
              if (yych <= ')') goto yy107;
              goto yy122;
            } else {
              if (yych == ',') goto yy123;
              goto yy107;
            }
          } else {
            if (yych <= 'D') {
              if (yych <= 'A') goto yy124;
              if (yych <= 'C') goto yy107;
              goto yy125;
            } else {
              if (yych <= 'E') goto yy126;
              if (yych <= 'F') goto yy127;
              if (yych <= 'H') goto yy107;
              goto yy128;
            }
          }
        } else {
          if (yych <= 'd') {
            if (yych <= '`') {
              if (yych == 'W') goto yy129;
              goto yy107;
            } else {
              if (yych <= 'a') goto yy124;
              if (yych <= 'c') goto yy107;
              goto yy125;
            }
          } else {
            if (yych <= 'h') {
              if (yych <= 'e') goto yy126;
              if (yych <= 'f') goto yy127;
              goto yy107;
            } else {
              if (yych <= 'i') goto yy128;
              if (yych == 'w') goto yy129;
              goto yy107;
            }
          }
        }
yy111:
        ++cursor;
        cursor -= 1;
        { ret = 1; goto lvall; }
yy112:
        ++cursor;
        { ret = 1; goto lvall; }
yy113:
        ++cursor;
        cursor -= 1;
        { ret = 1; goto lvall; }
yy114:
        yych = *++cursor;
        if (yych == 'L') goto yy130;
        if (yych == 'l') goto yy130;
yy115:
        cursor = marker;
        goto yy107;
yy116:
        yych = *++cursor;
        if (yych == 'E') goto yy131;
        if (yych == 'e') goto yy131;
        goto yy115;
yy117:
        yych = *++cursor;
        if (yych == 'R') goto yy132;
        if (yych == 'r') goto yy132;
        goto yy115;
yy118:
        yych = *++cursor;
        if (yych == 'A') goto yy133;
        if (yych == 'a') goto yy133;
        goto yy115;
yy119:
        yych = *++cursor;
        if (yych == 'N') goto yy134;
        if (yych == 'n') goto yy134;
        goto yy115;
yy120:
        yych = *++cursor;
        if (yych == 'A') goto yy135;
        if (yych == 'a') goto yy135;
        goto yy115;
yy121:
        ++cursor;
        cursor -= 1;
        { ret = 0; goto lvall; }
yy122:
        ++cursor;
        { ret = 0; goto lvall; }
yy123:
        ++cursor;
        cursor -= 1;
        { ret = 0; goto lvall; }
yy124:
        yych = *++cursor;
        if (yych == 'L') goto yy136;
        if (yych == 'l') goto yy136;
        goto yy115;
yy125:
        yych = *++cursor;
        if (yych == 'E') goto yy137;
        if (yych == 'e') goto yy137;
        goto yy115;
yy126:
        yych = *++cursor;
        if (yych == 'R') goto yy138;
        if (yych == 'r') goto yy138;
        goto yy115;
yy127:
        yych = *++cursor;
        if (yych == 'A') goto yy139;
        if (yych == 'a') goto yy139;
        goto yy115;
yy128:
        yych = *++cursor;
        if (yych == 'N') goto yy140;
        if (yych == 'n') goto yy140;
        goto yy115;
yy129:
        yych = *++cursor;
        if (yych == 'A') goto yy141;
        if (yych == 'a') goto yy141;
        goto yy115;
yy130:
        yych = *++cursor;
        if (yych == 'L') goto yy112;
        if (yych == 'l') goto yy112;
        goto yy115;
yy131:
        yych = *++cursor;
        if (yych == 'B') goto yy142;
        if (yych == 'b') goto yy142;
        goto yy115;
yy132:
        yych = *++cursor;
        if (yych == 'R') goto yy143;
        if (yych == 'r') goto yy143;
        goto yy115;
yy133:
        yych = *++cursor;
        if (yych == 'T') goto yy144;
        if (yych == 't') goto yy144;
        goto yy115;
yy134:
        yych = *++cursor;
        if (yych == 'F') goto yy145;
        if (yych == 'f') goto yy145;
        goto yy115;
yy135:
        yych = *++cursor;
        if (yych == 'R') goto yy146;
        if (yych == 'r') goto yy146;
        goto yy115;
yy136:
        yych = *++cursor;
        if (yych == 'L') goto yy122;
        if (yych == 'l') goto yy122;
        goto yy115;
yy137:
        yych = *++cursor;
        if (yych == 'B') goto yy147;
        if (yych == 'b') goto yy147;
        goto yy115;
yy138:
        yych = *++cursor;
        if (yych == 'R') goto yy148;
        if (yych == 'r') goto yy148;
        goto yy115;
yy139:
        yych = *++cursor;
        if (yych == 'T') goto yy149;
        if (yych == 't') goto yy149;
        goto yy115;
yy140:
        yych = *++cursor;
        if (yych == 'F') goto yy150;
        if (yych == 'f') goto yy150;
        goto yy115;
yy141:
        yych = *++cursor;
        if (yych == 'R') goto yy151;
        if (yych == 'r') goto yy151;
        goto yy115;
yy142:
        yych = *++cursor;
        if (yych == 'U') goto yy152;
        if (yych == 'u') goto yy152;
        goto yy115;
yy143:
        yych = *++cursor;
        if (yych == 'O') goto yy153;
        if (yych == 'o') goto yy153;
        goto yy115;
yy144:
        yych = *++cursor;
        if (yych == 'A') goto yy154;
        if (yych == 'a') goto yy154;
        goto yy115;
yy145:
        yych = *++cursor;
        if (yych == 'O') goto yy155;
        if (yych == 'o') goto yy155;
        goto yy115;
yy146:
        yych = *++cursor;
        if (yych == 'N') goto yy156;
        if (yych == 'n') goto yy156;
        goto yy115;
yy147:
        yych = *++cursor;
        if (yych == 'U') goto yy157;
        if (yych == 'u') goto yy157;
        goto yy115;
yy148:
        yych = *++cursor;
        if (yych == 'O') goto yy158;
        if (yych == 'o') goto yy158;
        goto yy115;
yy149:
        yych = *++cursor;
        if (yych == 'A') goto yy159;
        if (yych == 'a') goto yy159;
        goto yy115;
yy150:
        yych = *++cursor;
        if (yych == 'O') goto yy160;
        if (yych == 'o') goto yy160;
        goto yy115;
yy151:
        yych = *++cursor;
        if (yych == 'N') goto yy161;
        if (yych == 'n') goto yy161;
        goto yy115;
yy152:
        yych = *++cursor;
        if (yych == 'G') goto yy162;
        if (yych == 'g') goto yy162;
        goto yy115;
yy153:
        yych = *++cursor;
        if (yych == 'R') goto yy163;
        if (yych == 'r') goto yy163;
        goto yy115;
yy154:
        yych = *++cursor;
        if (yych == 'L') goto yy164;
        if (yych == 'l') goto yy164;
        goto yy115;
yy155:
        ++cursor;
        { ret = 1; lvl = CSV_EL_INFO; goto lv1; }
yy156:
        ++cursor;
        { ret = 1; lvl = CSV_EL_WARN; goto lv1; }
yy157:
        yych = *++cursor;
        if (yych == 'G') goto yy165;
        if (yych == 'g') goto yy165;
        goto yy115;
yy158:
        yych = *++cursor;
        if (yych == 'R') goto yy166;
        if (yych == 'r') goto yy166;
        goto yy115;
yy159:
        yych = *++cursor;
        if (yych == 'L') goto yy167;
        if (yych == 'l') goto yy167;
        goto yy115;
yy160:
        ++cursor;
        { ret = 0; lvl = CSV_EL_INFO; goto lv1; }
yy161:
        ++cursor;
        { ret = 0; lvl = CSV_EL_WARN; goto lv1; }
yy162:
        ++cursor;
        { ret = 1; lvl = CSV_EL_DEBUG; goto lv1; }
yy163:
        ++cursor;
        { ret = 1; lvl = CSV_EL_ERROR; goto lv1; }
yy164:
        ++cursor;
        { ret = 1; lvl = CSV_EL_FATAL; goto lv1; }
yy165:
        ++cursor;
        { ret = 0; lvl = CSV_EL_DEBUG; goto lv1; }
yy166:
        ++cursor;
        { ret = 0; lvl = CSV_EL_ERROR; goto lv1; }
yy167:
        ++cursor;
        { ret = 0; lvl = CSV_EL_FATAL; goto lv1; }
      }

      CSVUNREACHABLE();

    lvall:
      if (!apply_rank)
        continue;

      geom_bitarray_element_setall(levels->levels, CSV_EL_MAX, ret);
      continue;

    lv1:
      if (!apply_rank)
        continue;

      geom_bitarray_element_set(levels->levels, lvl, ret);
      continue;
    }
  }
  CSVUNREACHABLE();

end:
  *print_my_rank = print_rank;
  return CSV_ERR_SUCC;

int_overflow:
  csvperrorf("<command line>", 0, 0, CSV_EL_ERROR, flg,
             "Rank number too large.");
  return CSV_ERR_CMDLINE_INVAL;

invalid_rank:
  csvperrorf("<command line>", 0, 0, CSV_EL_ERROR, flg,
             "Failed to parse print rank value or range, format: "
             "`<s>[..<e>]:<levels...>[,...]`");
  return CSV_ERR_CMDLINE_INVAL;

invalid_level:
  csvperrorf("<command line>", 0, 0, CSV_EL_ERROR, flg,
             "Failed to parse level names. It must be sequence of "
             "'[-+]all', '[-+]debug', '[-+]info', '[-+]warn', "
             "'[-+]error' or '[-+]fatal', or `[-+]` for all");
  return CSV_ERR_CMDLINE_INVAL;
}

static csv_error jupiter_parse_print_levels(const char *arg, const char *flg,
                                            jupiter_print_levels *levels)
{
  const char *t1, *t2;
  const char *cursor;
  const char *marker;
  csv_error_level lvl = CSV_EL_MAX;
  int ret;

  cursor = arg;
  for (;;) {
    lvl = CSV_EL_MAX;
    ret = 1;
    t1 = cursor;
    for (;;) {
      
      {
        unsigned char yych;
        yych = *cursor;
        if (yych <= 0x1F) {
          if (yych <= '\n') {
            if (yych <= 0x00) goto yy169;
            if (yych <= 0x08) goto yy170;
            goto yy171;
          } else {
            if (yych == '\r') goto yy171;
            goto yy170;
          }
        } else {
          if (yych <= '+') {
            if (yych <= ' ') goto yy171;
            if (yych <= '*') goto yy170;
            goto yy173;
          } else {
            if (yych == '-') goto yy174;
            goto yy170;
          }
        }
yy169:
        ++cursor;
        { return CSV_ERR_SUCC; }
yy170:
        ++cursor;
        { cursor = t1; break; }
yy171:
        yych = *++cursor;
        if (yych <= '\f') {
          if (yych <= 0x08) goto yy172;
          if (yych <= '\n') goto yy171;
        } else {
          if (yych <= '\r') goto yy171;
          if (yych == ' ') goto yy171;
        }
yy172:
        { t1 = cursor; continue; }
yy173:
        ++cursor;
        { ret = 1; break; }
yy174:
        ++cursor;
        { ret = 0; break; }
      }

    }
    t2 = cursor;
    for (;;) {
      
      {
        unsigned char yych;
        yych = *cursor;
        if (yych <= 'V') {
          if (yych <= 'D') {
            if (yych <= '+') {
              if (yych >= 0x01) goto yy176;
            } else {
              if (yych <= ',') goto yy178;
              if (yych <= 'C') goto yy176;
              goto yy179;
            }
          } else {
            if (yych <= 'F') {
              if (yych <= 'E') goto yy180;
              goto yy181;
            } else {
              if (yych == 'I') goto yy182;
              goto yy176;
            }
          }
        } else {
          if (yych <= 'f') {
            if (yych <= 'c') {
              if (yych <= 'W') goto yy183;
              goto yy176;
            } else {
              if (yych <= 'd') goto yy179;
              if (yych <= 'e') goto yy180;
              goto yy181;
            }
          } else {
            if (yych <= 'i') {
              if (yych <= 'h') goto yy176;
              goto yy182;
            } else {
              if (yych == 'w') goto yy183;
              goto yy176;
            }
          }
        }
        ++cursor;
        { cursor = t2; break; }
yy176:
        ++cursor;
yy177:
        { goto invalid; }
yy178:
        ++cursor;
        { if (t1 == t2) goto invalid; break; }
yy179:
        yych = *(marker = ++cursor);
        if (yych == 'E') goto yy184;
        if (yych == 'e') goto yy184;
        goto yy177;
yy180:
        yych = *(marker = ++cursor);
        if (yych == 'R') goto yy186;
        if (yych == 'r') goto yy186;
        goto yy177;
yy181:
        yych = *(marker = ++cursor);
        if (yych == 'A') goto yy187;
        if (yych == 'a') goto yy187;
        goto yy177;
yy182:
        yych = *(marker = ++cursor);
        if (yych == 'N') goto yy188;
        if (yych == 'n') goto yy188;
        goto yy177;
yy183:
        yych = *(marker = ++cursor);
        if (yych == 'A') goto yy189;
        if (yych == 'a') goto yy189;
        goto yy177;
yy184:
        yych = *++cursor;
        if (yych == 'B') goto yy190;
        if (yych == 'b') goto yy190;
yy185:
        cursor = marker;
        goto yy177;
yy186:
        yych = *++cursor;
        if (yych == 'R') goto yy191;
        if (yych == 'r') goto yy191;
        goto yy185;
yy187:
        yych = *++cursor;
        if (yych == 'T') goto yy192;
        if (yych == 't') goto yy192;
        goto yy185;
yy188:
        yych = *++cursor;
        if (yych == 'F') goto yy193;
        if (yych == 'f') goto yy193;
        goto yy185;
yy189:
        yych = *++cursor;
        if (yych == 'R') goto yy194;
        if (yych == 'r') goto yy194;
        goto yy185;
yy190:
        yych = *++cursor;
        if (yych == 'U') goto yy195;
        if (yych == 'u') goto yy195;
        goto yy185;
yy191:
        yych = *++cursor;
        if (yych == 'O') goto yy196;
        if (yych == 'o') goto yy196;
        goto yy185;
yy192:
        yych = *++cursor;
        if (yych == 'A') goto yy197;
        if (yych == 'a') goto yy197;
        goto yy185;
yy193:
        yych = *++cursor;
        if (yych == 'O') goto yy198;
        if (yych == 'o') goto yy198;
        goto yy185;
yy194:
        yych = *++cursor;
        if (yych == 'N') goto yy199;
        if (yych == 'n') goto yy199;
        goto yy185;
yy195:
        yych = *++cursor;
        if (yych == 'G') goto yy200;
        if (yych == 'g') goto yy200;
        goto yy185;
yy196:
        yych = *++cursor;
        if (yych == 'R') goto yy201;
        if (yych == 'r') goto yy201;
        goto yy185;
yy197:
        yych = *++cursor;
        if (yych == 'L') goto yy202;
        if (yych == 'l') goto yy202;
        goto yy185;
yy198:
        yych = *++cursor;
        if (yych <= '\r') {
          if (yych <= 0x08) {
            if (yych <= 0x00) goto yy203;
            goto yy185;
          } else {
            if (yych <= '\n') goto yy198;
            if (yych <= '\f') goto yy185;
            goto yy198;
          }
        } else {
          if (yych <= ' ') {
            if (yych <= 0x1F) goto yy185;
            goto yy198;
          } else {
            if (yych == ',') goto yy204;
            goto yy185;
          }
        }
yy199:
        yych = *++cursor;
        if (yych <= '\r') {
          if (yych <= 0x08) {
            if (yych <= 0x00) goto yy205;
            goto yy185;
          } else {
            if (yych <= '\n') goto yy199;
            if (yych <= '\f') goto yy185;
            goto yy199;
          }
        } else {
          if (yych <= ' ') {
            if (yych <= 0x1F) goto yy185;
            goto yy199;
          } else {
            if (yych == ',') goto yy206;
            goto yy185;
          }
        }
yy200:
        yych = *++cursor;
        if (yych <= '\r') {
          if (yych <= 0x08) {
            if (yych <= 0x00) goto yy207;
            goto yy185;
          } else {
            if (yych <= '\n') goto yy200;
            if (yych <= '\f') goto yy185;
            goto yy200;
          }
        } else {
          if (yych <= ' ') {
            if (yych <= 0x1F) goto yy185;
            goto yy200;
          } else {
            if (yych == ',') goto yy208;
            goto yy185;
          }
        }
yy201:
        yych = *++cursor;
        if (yych <= '\r') {
          if (yych <= 0x08) {
            if (yych <= 0x00) goto yy209;
            goto yy185;
          } else {
            if (yych <= '\n') goto yy201;
            if (yych <= '\f') goto yy185;
            goto yy201;
          }
        } else {
          if (yych <= ' ') {
            if (yych <= 0x1F) goto yy185;
            goto yy201;
          } else {
            if (yych == ',') goto yy210;
            goto yy185;
          }
        }
yy202:
        yych = *++cursor;
        if (yych <= '\r') {
          if (yych <= 0x08) {
            if (yych <= 0x00) goto yy211;
            goto yy185;
          } else {
            if (yych <= '\n') goto yy202;
            if (yych <= '\f') goto yy185;
            goto yy202;
          }
        } else {
          if (yych <= ' ') {
            if (yych <= 0x1F) goto yy185;
            goto yy202;
          } else {
            if (yych == ',') goto yy212;
            goto yy185;
          }
        }
yy203:
        ++cursor;
        cursor -= 1;
        { lvl = CSV_EL_INFO; break; }
yy204:
        ++cursor;
        { lvl = CSV_EL_INFO; break; }
yy205:
        ++cursor;
        cursor -= 1;
        { lvl = CSV_EL_WARN; break; }
yy206:
        ++cursor;
        { lvl = CSV_EL_WARN; break; }
yy207:
        ++cursor;
        cursor -= 1;
        { lvl = CSV_EL_DEBUG; break; }
yy208:
        ++cursor;
        { lvl = CSV_EL_DEBUG; break; }
yy209:
        ++cursor;
        cursor -= 1;
        { lvl = CSV_EL_ERROR; break; }
yy210:
        ++cursor;
        { lvl = CSV_EL_ERROR; break; }
yy211:
        ++cursor;
        cursor -= 1;
        { lvl = CSV_EL_FATAL; break; }
yy212:
        ++cursor;
        { lvl = CSV_EL_FATAL; break; }
      }

      CSVUNREACHABLE();
    }

    if (lvl == CSV_EL_MAX) {
      geom_bitarray_element_setall(levels->levels, CSV_EL_MAX, ret);
    } else {
      geom_bitarray_element_set(levels->levels, lvl, ret);
    }
  }

  return CSV_ERR_SUCC;

invalid:
  csvperrorf("<command line>", 0, 0, CSV_EL_ERROR, flg,
             "Failed to parse level names. It must be comma separated "
             "'debug', 'info', 'warn', 'error' or 'fatal'");
  return CSV_ERR_CMDLINE_INVAL;
}

static csv_error jupiter_optparse_base(jupiter_options *opts, int *argc,
                                       char ***argv,
                                       jupiter_file_inputs_flags *f,
                                       int accept_others)
{
  const char *token;
  const char *cursor;
  const char *marker;
  int i;
  int r;
  int oargc;
  int nargc;
  char **oargv;
  char **nargv;
  csv_error ret;
  const char *flg;
  const char **floc;
  enum jupiter_file_inputs fi;
  int print_rank_level = 0;

  CSVASSERT(opts);
  CSVASSERT(argc);
  CSVASSERT(argv);

  oargc = *argc;
  oargv = *argv;

  nargc = 0;
  nargv = (char **)calloc(sizeof(char *), oargc);
  if (nargv) {
    nargv[0] = oargv[0];
    nargc++;
  }

  for (i = 1; i < oargc; ++i) {
    cursor = oargv[i];

    for (;;) {
      token = cursor;

      
      {
        unsigned char yych;
        yych = *cursor;
        if (yych == '-') goto yy214;
        ++cursor;
        { break; }
yy214:
        yych = *++cursor;
        if (yych == '-') goto yy215;
        { goto hyphen; }
yy215:
        ++cursor;
        { goto double_hyphen; }
      }

      CSVUNREACHABLE();
    }

    /* Collect non option parameters */
    if (nargv) {
      nargv[nargc] = oargv[i];
      nargc++;
    }
    continue; /* goto next argument */

  double_hyphen:
    for (;;) {
      token = cursor;
      
    {
      unsigned char yych;
      yych = *cursor;
      if (yych >= 0x01) goto yy217;
      ++cursor;
      { goto stop_parse; }
yy217:
      ++cursor;
      { cursor = token; break; }
    }

      CSVUNREACHABLE();
    }

  hyphen:
    for (;;) {
      token = cursor;
      
    {
      unsigned char yych;
      yych = *cursor;
      switch (yych) {
        case 'c': goto yy221;
        case 'f': goto yy222;
        case 'g': goto yy223;
        case 'i': goto yy224;
        case 'p': goto yy225;
        case 'r': goto yy226;
        default: goto yy219;
      }
yy219:
      ++cursor;
yy220:
      { goto invalid; }
yy221:
      yych = *(marker = ++cursor);
      if (yych == 'o') goto yy227;
      goto yy220;
yy222:
      yych = *(marker = ++cursor);
      if (yych == 'l') goto yy229;
      goto yy220;
yy223:
      yych = *(marker = ++cursor);
      if (yych == 'e') goto yy230;
      goto yy220;
yy224:
      yych = *(marker = ++cursor);
      if (yych == 'n') goto yy231;
      goto yy220;
yy225:
      yych = *(marker = ++cursor);
      if (yych <= 'n') {
        if (yych == 'l') goto yy232;
        goto yy220;
      } else {
        if (yych <= 'o') goto yy233;
        if (yych == 'r') goto yy234;
        goto yy220;
      }
yy226:
      yych = *(marker = ++cursor);
      if (yych == 'e') goto yy235;
      goto yy220;
yy227:
      yych = *++cursor;
      if (yych == 'n') goto yy236;
yy228:
      cursor = marker;
      goto yy220;
yy229:
      yych = *++cursor;
      if (yych == 'a') goto yy237;
      goto yy228;
yy230:
      yych = *++cursor;
      if (yych == 'o') goto yy238;
      goto yy228;
yy231:
      yych = *++cursor;
      if (yych == 'p') goto yy239;
      goto yy228;
yy232:
      yych = *++cursor;
      if (yych == 'i') goto yy240;
      goto yy228;
yy233:
      yych = *++cursor;
      if (yych == 's') goto yy241;
      goto yy228;
yy234:
      yych = *++cursor;
      if (yych == 'i') goto yy242;
      goto yy228;
yy235:
      yych = *++cursor;
      if (yych == 's') goto yy243;
      goto yy228;
yy236:
      yych = *++cursor;
      if (yych == 't') goto yy244;
      goto yy228;
yy237:
      yych = *++cursor;
      if (yych == 'g') goto yy245;
      goto yy228;
yy238:
      yych = *++cursor;
      if (yych == 'm') goto yy246;
      goto yy228;
yy239:
      yych = *++cursor;
      if (yych == 'u') goto yy247;
      goto yy228;
yy240:
      yych = *++cursor;
      if (yych == 's') goto yy248;
      goto yy228;
yy241:
      yych = *++cursor;
      if (yych == 't') goto yy249;
      goto yy228;
yy242:
      yych = *++cursor;
      if (yych == 'n') goto yy250;
      goto yy228;
yy243:
      yych = *++cursor;
      if (yych == 't') goto yy251;
      goto yy228;
yy244:
      yych = *++cursor;
      if (yych == 'r') goto yy252;
      goto yy228;
yy245:
      yych = *++cursor;
      if (yych == 's') goto yy253;
      goto yy228;
yy246:
      yych = *++cursor;
      if (yych <= 0x00) goto yy254;
      goto yy228;
yy247:
      yych = *++cursor;
      if (yych == 't') goto yy255;
      goto yy228;
yy248:
      yych = *++cursor;
      if (yych == 't') goto yy256;
      goto yy228;
yy249:
      yych = *++cursor;
      if (yych <= 0x00) goto yy257;
      goto yy228;
yy250:
      yych = *++cursor;
      if (yych == 't') goto yy258;
      goto yy228;
yy251:
      yych = *++cursor;
      if (yych == 'a') goto yy259;
      goto yy228;
yy252:
      yych = *++cursor;
      if (yych == 'o') goto yy260;
      goto yy228;
yy253:
      yych = *++cursor;
      if (yych <= 0x00) goto yy261;
      goto yy228;
yy254:
      ++cursor;
      cursor -= 1;
      { goto geom_file; }
yy255:
      yych = *++cursor;
      if (yych <= 0x00) goto yy262;
      goto yy228;
yy256:
      yych = *++cursor;
      if (yych <= 0x00) goto yy263;
      goto yy228;
yy257:
      ++cursor;
      cursor -= 1;
      { goto post; }
yy258:
      yych = *++cursor;
      if (yych == '_') goto yy264;
      goto yy228;
yy259:
      yych = *++cursor;
      if (yych == 'r') goto yy265;
      goto yy228;
yy260:
      yych = *++cursor;
      if (yych == 'l') goto yy266;
      goto yy228;
yy261:
      ++cursor;
      cursor -= 1;
      { goto flags_file; }
yy262:
      ++cursor;
      cursor -= 1;
      { goto input_file; }
yy263:
      ++cursor;
      cursor -= 1;
      { goto plist_file; }
yy264:
      yych = *++cursor;
      if (yych == 'l') goto yy267;
      if (yych == 'r') goto yy268;
      goto yy228;
yy265:
      yych = *++cursor;
      if (yych == 't') goto yy269;
      goto yy228;
yy266:
      yych = *++cursor;
      if (yych <= 0x00) goto yy270;
      goto yy228;
yy267:
      yych = *++cursor;
      if (yych == 'e') goto yy271;
      goto yy228;
yy268:
      yych = *++cursor;
      if (yych == 'a') goto yy272;
      goto yy228;
yy269:
      yych = *++cursor;
      if (yych <= 0x00) goto yy273;
      if (yych == '_') goto yy274;
      goto yy228;
yy270:
      ++cursor;
      cursor -= 1;
      { goto control_file; }
yy271:
      yych = *++cursor;
      if (yych == 'v') goto yy275;
      goto yy228;
yy272:
      yych = *++cursor;
      if (yych == 'n') goto yy276;
      goto yy228;
yy273:
      ++cursor;
      cursor -= 1;
      { goto restart; }
yy274:
      yych = *++cursor;
      if (yych == 'j') goto yy277;
      goto yy228;
yy275:
      yych = *++cursor;
      if (yych == 'e') goto yy278;
      goto yy228;
yy276:
      yych = *++cursor;
      if (yych == 'k') goto yy279;
      goto yy228;
yy277:
      yych = *++cursor;
      if (yych == 'o') goto yy280;
      goto yy228;
yy278:
      yych = *++cursor;
      if (yych == 'l') goto yy281;
      goto yy228;
yy279:
      yych = *++cursor;
      if (yych <= 0x00) goto yy282;
      goto yy228;
yy280:
      yych = *++cursor;
      if (yych == 'b') goto yy283;
      goto yy228;
yy281:
      yych = *++cursor;
      if (yych <= 0x00) goto yy284;
      goto yy228;
yy282:
      ++cursor;
      cursor -= 1;
      { goto print_rank; }
yy283:
      yych = *++cursor;
      if (yych <= 0x00) goto yy285;
      goto yy228;
yy284:
      ++cursor;
      cursor -= 1;
      { goto print_level; }
yy285:
      ++cursor;
      cursor -= 1;
      { goto restart_job; }
    }

      CSVUNREACHABLE();
    }
    continue; /* goto next argument */

  flags_file:
    fi = JUPITER_INPUT_FILE_FLAGS;
    floc = &opts->flags_file;
    goto set_file;

  input_file:
    fi = JUPITER_INPUT_FILE_PARAMS;
    floc = &opts->param_file;
    goto set_file;

  plist_file:
    fi = JUPITER_INPUT_FILE_PLIST;
    floc = &opts->plist_file;
    goto set_file;

  geom_file:
    fi = JUPITER_INPUT_FILE_GEOM;
    floc = &opts->geom_file;
    goto set_file;

  control_file:
    fi = JUPITER_INPUT_FILE_CONTROL;
    floc = &opts->control_file;
    goto set_file;

  set_file:
    if (!geom_bitarray_element_get(f->f, fi))
      goto invalid;

    if (i + 1 >= oargc) {
      csvperrorf("<command line>", 0, 0, CSV_EL_ERROR,
                 NULL, "A file name required after `%s`", oargv[i]);
      ret = CSV_ERR_CMDLINE_INVAL;
      goto clean;
    }
    ++i;
    *floc = oargv[i];
    continue;

  restart_job:
    if (!accept_others)
      goto invalid;

    opts->restart_job = 1;
    continue;

  restart:
    if (!accept_others)
      goto invalid;

    {
      flg = oargv[i];

      ++i;
      r = jupiter_parse_int_array(flg, oargc - i, &oargv[i],
                                  1, &opts->restart);
      if (r == 0) return -1;
      if (opts->restart <= 0) {
        csvperrorf("<command line>", 0, 0, CSV_EL_ERROR, flg,
                   "Must be positive value: %d", opts->restart);
        opts->restart = -1;
        ret = CSV_ERR_CMDLINE_RANGE;
        goto clean;
      }
      i += r - 1;
    }
    continue;

  post:
    if (!accept_others)
      goto invalid;

    {
      flg = oargv[i];

      ++i;
      r = jupiter_parse_int_array(flg, oargc - i, &oargv[i],
                                  2, &opts->post_s, &opts->post_e);
      if (r == 0) return -1;
      if (opts->post_s < 0) {
        csvperrorf("<command line>", 0, 0, CSV_EL_ERROR, flg,
                   "Must be positive value or zero: %d", opts->post_s);
        opts->post_s = -1;
        opts->post_e = -1;
        ret = CSV_ERR_CMDLINE_RANGE;
        goto clean;
      }
      if (opts->post_e < opts->post_s) {
        csvperrorf("<command line>", 0, 0, CSV_EL_ERROR, flg,
                   "Last point must be greater than start: [%d, %d]",
                   opts->post_s, opts->post_e);
        opts->post_s = -1;
        opts->post_e = -1;
        ret = CSV_ERR_CMDLINE_RANGE;
        goto clean;
      }
      i += r - 1;
    }
    continue;

  print_rank:
    /*
     * Accepts only if MPI enabled.
     */
#ifdef JUPITER_MPI
    flg = oargv[i];
    ++i;
    if (i >= oargc) {
      csvperrorf("<command line>", 0, 0, CSV_EL_ERROR, flg,
                 "Missing print_rank specifier");
      ret = -1;
      goto clean;
    }
    ret = jupiter_parse_print_rank(oargv[i], flg, &opts->print_my_rank,
                                   &opts->print_levels);
    if (ret != CSV_ERR_SUCC)
      goto clean;

    print_rank_level = 1;
    continue;
#endif
    goto invalid;

  print_level:
    flg = oargv[i];
    ++i;
    if (i >= oargc) {
      csvperrorf("<command line>", 0, 0, CSV_EL_ERROR, flg,
                 "Missing print_level specifier");
      ret = -1;
      goto clean;
    }

    ret = jupiter_parse_print_levels(oargv[i], flg, &opts->print_levels);
    if (ret != CSV_ERR_SUCC)
      goto clean;

    print_rank_level = 1;
    continue;
  }

 stop_parse:
  if (!print_rank_level) {
    jupiter_parse_print_rank(opts->print_rank, "<defaults>",
                             &opts->print_my_rank, &opts->print_levels);
  }
  set_jupiter_print_levels(opts->print_levels);
  set_jupiter_print_rank(opts->print_my_rank);

  if (nargv) {
    for (++i; i < oargc; ++i) {
      nargv[nargc] = oargv[i];
      ++nargc;
    }
    for (i = 0; i < nargc; ++i) {
      oargv[i] = nargv[i];
    }
    free(nargv);
    *argc = nargc;
  } else {
    return CSV_ERR_NOMEM;
  }
  return CSV_ERR_SUCC;

 invalid:
  csvperrorf("<command line>", 0, 0, CSV_EL_ERROR,
             NULL, "Invalid argument: %s", oargv[i]);
  ret = CSV_ERR_CMDLINE_INVAL;
  goto clean;

 clean:
  free(nargv);
  return ret;
 }

csv_error jupiter_optparse(jupiter_options *opts, int *argc, char ***argv)
{
  jupiter_file_inputs_flags f = jupiter_file_inputs_flags_all();
  return jupiter_optparse_base(opts, argc, argv, &f, 1);
}

csv_error jupiter_optparse_files(jupiter_options *opts, int *argc, char ***argv,
                                 jupiter_file_inputs_flags *accepts)
{
  return jupiter_optparse_base(opts, argc, argv, accepts, 0);
}
