#ifndef HEADER_PCGBLOCK3DRESLOWTYPE
#define HEADER_PCGBLOCK3DRESLOWTYPE

__global__ void calc_sres_block3D_unable_bound_core_cuda_lowtype_kernel(
						     low_type* A,
						     low_type* x,low_type* r,type* b,
						     const  int block_m,
						      int *block_nxs, int *block_nxe, 
						      int *block_nys, int *block_nye, 
						      int *block_nzs, int *block_nze,
						     int *stride_xp,int *stride_xm,
						     int *stride_yp,int *stride_ym,
						     int *stride_zp,int *stride_zm,
						     type *block_West_filter,type *block_East_filter,
						     type *block_South_filter,type *block_North_filter,
						     type *block_Bottom_filter,type *block_Top_filter,
						     const int nxblock,const int nyblock,const int nzblock,
						     const int mxdivblock,const int mydivblock,const int mzdivblock,
						     const int nxdivblock,const int nydivblock,const int nzdivblock);
__global__ void calc_sres_block3D_unable_bound_South_cuda_lowtype_kernel(
						     low_type* A,low_type* x,low_type* r,type* b,
						     const  int block_m,
						      int *block_nxs, int *block_nxe, 
						      int *block_nys, int *block_nye, 
						      int *block_nzs, int *block_nze,
						     int *stride_xp,int *stride_xm,
						     int *stride_yp,int *stride_ym,
						     int *stride_zp,int *stride_zm,
						     type *block_West_filter,type *block_East_filter,
						     type *block_South_filter,type *block_North_filter,
						     type *block_Bottom_filter,type *block_Top_filter,
						     const int nxblock,const int nyblock,const int nzblock,
						     const int mxdivblock,const int mydivblock,const int mzdivblock,
						     const int nxdivblock,const int nydivblock,const int nzdivblock);
__global__ void calc_sres_block3D_unable_bound_North_lowtype_cuda_kernel(
						     low_type* A,low_type* x,low_type* r,type* b,
						     const  int block_m,
						      int *block_nxs, int *block_nxe, 
						      int *block_nys, int *block_nye, 
						      int *block_nzs, int *block_nze,
						     int *stride_xp,int *stride_xm,
						     int *stride_yp,int *stride_ym,
						     int *stride_zp,int *stride_zm,
						     type *block_West_filter,type *block_East_filter,
						     type *block_South_filter,type *block_North_filter,
						     type *block_Bottom_filter,type *block_Top_filter,
						     const int nxblock,const int nyblock,const int nzblock,
						     const int mxdivblock,const int mydivblock,const int mzdivblock,
						     const int nxdivblock,const int nydivblock,const int nzdivblock);
__global__ void calc_sres_block3D_unable_bound_Bottom_lowtype_cuda_kernel(
						     low_type* A,low_type* x,low_type* r,type* b,
						     const  int block_m,
						      int *block_nxs, int *block_nxe, 
						      int *block_nys, int *block_nye, 
						      int *block_nzs, int *block_nze,
						     int *stride_xp,int *stride_xm,
						     int *stride_yp,int *stride_ym,
						     int *stride_zp,int *stride_zm,
						     type *block_West_filter,type *block_East_filter,
						     type *block_South_filter,type *block_North_filter,
						     type *block_Bottom_filter,type *block_Top_filter,
						     const int nxblock,const int nyblock,const int nzblock,
						     const int mxdivblock,const int mydivblock,const int mzdivblock,
						     const int nxdivblock,const int nydivblock,const int nzdivblock);
__global__ void calc_sres_block3D_unable_bound_Top_lowtype_cuda_kernel(
						     low_type* A,low_type* x,low_type* r,type* b,
						     const  int block_m,
						      int *block_nxs, int *block_nxe, 
						      int *block_nys, int *block_nye, 
						      int *block_nzs, int *block_nze,
						     int *stride_xp,int *stride_xm,
						     int *stride_yp,int *stride_ym,
						     int *stride_zp,int *stride_zm,
						     type *block_West_filter,type *block_East_filter,
						     type *block_South_filter,type *block_North_filter,
						     type *block_Bottom_filter,type *block_Top_filter,
						     const int nxblock,const int nyblock,const int nzblock,
						     const int mxdivblock,const int mydivblock,const int mzdivblock,
						     const int nxdivblock,const int nydivblock,const int nzdivblock);
__global__ void calc_sres_block3D_able_South_cuda_kernel(
						     low_type* A,low_type* x,low_type* r,type* b,
						     low_type* rb_s,
						     const  int block_m,  
						     int *block_nys,
						     int *block_nxs, int *block_nxe, 
						     int *block_nzs, int *block_nze,  
						     int *stride_ym,
						     const int nxblock,const int nyblock,const int nzblock,
						     const int mxdivblock,const int mydivblock,const int mzdivblock,
						     const int nxdivblock,const int nydivblock,const int nzdivblock);
__global__ void calc_sres_block3D_able_North_cuda_kernel(
						     low_type* A,low_type* x,low_type* r,type* b,
						     low_type* rb_n,						     
						     const  int block_m,
						     int *block_nye,
						     int *block_nxs, int *block_nxe, 
						     int *block_nzs, int *block_nze,  
						     int *stride_yp,						     
						     const int nxblock,const int nyblock,const int nzblock,
						     const int mxdivblock,const int mydivblock,const int mzdivblock,
						     const int nxdivblock,const int nydivblock,const int nzdivblock);
__global__ void calc_sres_block3D_able_Bottom_cuda_kernel(
						     low_type* A,low_type* x,low_type* r,type* b,
						     low_type* rb_b,
						     const  int block_m,
						     int *block_nzs,
						     int *block_nxs, int *block_nxe, 
						     int *block_nys, int *block_nye,  
						     int *stride_zm,
						     const int nxblock,const int nyblock,const int nzblock,
						     const int mxdivblock,const int mydivblock,const int mzdivblock,
						     const int nxdivblock,const int nydivblock,const int nzdivblock);
__global__ void calc_sres_block3D_able_Top_cuda_kernel(
						     low_type* A,low_type* x,low_type* r,type* b,
						     low_type* rb_t,						     
						     const  int block_m,
						     int *block_nze,
						     int *block_nxs, int *block_nxe, 
						     int *block_nys, int *block_nye,  
						     int *stride_zp,
						     const int nxblock,const int nyblock,const int nzblock,
						     const int mxdivblock,const int mydivblock,const int mzdivblock,
						     const int nxdivblock,const int nydivblock,const int nzdivblock);

#endif
