#ifndef HEADER_PCGBLOCK3DPRECONLOWTYPECUDA
#define HEADER_PCGBLOCK3DPRECONLOWTYPECUDA

__global__ void solve_pre_subdividing_mat2_local_ILU_1_block3D_core_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s,type *q,
								      type alpha,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);

__global__ void solve_pre_subdividing_mat2_local_ILU_1_block3D_South_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s,type *q,
								      type alpha,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);

__global__ void solve_pre_subdividing_mat2_local_ILU_1_block3D_North_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s,type *q,
								      type alpha,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);

__global__ void solve_pre_subdividing_mat2_local_ILU_1_block3D_Bottom_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s,type *q,
								      type alpha,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);


__global__ void solve_pre_subdividing_mat2_local_ILU_1_block3D_Top_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s,type *q,
								      type alpha,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);


__global__ void calc_res_solve_pre_subdividing_mat2_local_ILU_2_block3D_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s_in, type *s_out,
								      low_type *z,
								      type *sr_dot_local,type *rr_dot_local,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);

__global__ void calc_res_solve_pre_subdividing_mat2_local_ILU_2_block3D_core_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s_in, type *s_out,
								      low_type *z,
								      type *sr_dot_local,type *rr_dot_local,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);

__global__ void calc_res_solve_pre_subdividing_mat2_local_ILU_2_block3D_unable_core_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s_in, type *s_out,
								      low_type *z,
								      type *sr_dot_local,type *rr_dot_local,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
						     type *block_West_filter,type *block_East_filter,
						     type *block_South_filter,type *block_North_filter,
						     type *block_Bottom_filter,type *block_Top_filter,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);

__global__ void calc_res_solve_pre_subdividing_mat2_local_ILU_2_Bottom_block3D_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s_lowtype, type *s,
								      low_type *z_lowtype,
								      type *sr_dot_local,type *rr_dot_local,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);

__global__ void calc_res_solve_pre_subdividing_mat2_local_ILU_2_Top_block3D_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s_lowtype, type *s,
								      low_type *z_lowtype,
								      type *sr_dot_local,type *rr_dot_local,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);

__global__ void calc_solve_pre_subdividing_mat2_local_ILU_2_block3D_South_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s_in, type *s_out,
								      low_type *z,
								      type *sr_dot_local,type *rr_dot_local,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);

__global__ void calc_res_solve_pre_subdividing_mat2_local_ILU_2_block3D_North_lowtype_cuda_kernel(
								      low_type* A,low_type* Dinv,
								      type *r, low_type *s_in, type *s_out,
								      low_type *z,
								      type *sr_dot_local,type *rr_dot_local,
								      int *block_nxs, int *block_nxe, 
								      int *block_nys, int *block_nye, 
								      int *block_nzs, int *block_nze,
								      int *stride_xp, int *stride_xm,
								      int *stride_yp, int *stride_ym,
								      int *stride_zp, int *stride_zm,
								      type *block_xfilterL,type *block_xfilterU,
								      type *block_yfilterL,type *block_yfilterU,
								      type *block_zfilterL,type *block_zfilterU,
								      const  int block_m,
								      const int nxblock,const int nyblock,const int nzblock,
								      const int mxdivblock,const int mydivblock,const int mzdivblock,
								      const int nxdivblock,const int nydivblock,const int nzdivblock);

JUPITER_DECL
int solve_pre_subdividing_mat0_local_block3D_lowtype_cuda(
				   mpi_prm prm,low_type* A,low_type* Dinv,
				   type *r, type *s,
				   type* cuda_buf,
				   low_type* cuda_lowtype_buf,
				   low_type *sb_b ,low_type *rb_b ,low_type *sb_t ,low_type *rb_t ,
				   low_type *sb_s ,low_type *rb_s ,low_type *sb_n ,low_type *rb_n ,
				   low_type *sb_w ,low_type *rb_w ,low_type *sb_e ,low_type *rb_e ,
				   int *block_nxs, int *block_nxe, 
				   int *block_nys, int *block_nye, 
				   int *block_nzs, int *block_nze,
				   int *stride_xp, int *stride_xm,
				   int *stride_yp, int *stride_ym,
				   int *stride_zp, int *stride_zm,
				   type *block_xfilterL,type *block_xfilterU,
				   type *block_yfilterL,type *block_yfilterU,
				   type *block_zfilterL,type *block_zfilterU,
				   type *block_West_filter,type *block_East_filter,
				   type *block_South_filter,type *block_North_filter,
				   type *block_Bottom_filter,type *block_Top_filter,				   
				   cudaStream_t *cudaStream_Hi_Priority 
							  );
JUPITER_DECL
int solve_pre_subdividing_mat2_local_OVL2_block3D_lowtype_cuda(
				   mpi_prm prm,low_type* A,low_type* Dinv,
				   type *r, type *s,type *q,
				   type alpha,
				   type* cuda_buf,
				   low_type* cuda_lowtype_buf,
				   low_type *sb_b ,low_type *rb_b ,low_type *sb_t ,low_type *rb_t ,
				   low_type *sb_s ,low_type *rb_s ,low_type *sb_n ,low_type *rb_n ,
				   low_type *sb_w ,low_type *rb_w ,low_type *sb_e ,low_type *rb_e ,
				   int *block_nxs, int *block_nxe, 
				   int *block_nys, int *block_nye, 
				   int *block_nzs, int *block_nze,
				   int *stride_xp, int *stride_xm,
				   int *stride_yp, int *stride_ym,
				   int *stride_zp, int *stride_zm,
				   type *block_xfilterL,type *block_xfilterU,
				   type *block_yfilterL,type *block_yfilterU,
				   type *block_zfilterL,type *block_zfilterU,
				   type *block_West_filter,type *block_East_filter,
				   type *block_South_filter,type *block_North_filter,
				   type *block_Bottom_filter,type *block_Top_filter,				   
				   cudaStream_t *cudaStream_Hi_Priority ,
				   cudaStream_t *cudaStream_Low_Priority ,
				   cudaEvent_t *cudaEvent_OVL,		       
				   double *time
							       );

JUPITER_DECL
int solve_pre_subdividing_mat2_local_block3D_lowtype_cuda(
				   mpi_prm prm,low_type* A,low_type* Dinv,
				   type *r, type *s,type *q,
				   type alpha,
				   type* cuda_buf,
				   low_type* cuda_lowtype_buf,
				   low_type *sb_b ,low_type *rb_b ,low_type *sb_t ,low_type *rb_t ,
				   low_type *sb_s ,low_type *rb_s ,low_type *sb_n ,low_type *rb_n ,
				   low_type *sb_w ,low_type *rb_w ,low_type *sb_e ,low_type *rb_e ,
				   int *block_nxs, int *block_nxe, 
				   int *block_nys, int *block_nye, 
				   int *block_nzs, int *block_nze,
				   int *stride_xp, int *stride_xm,
				   int *stride_yp, int *stride_ym,
				   int *stride_zp, int *stride_zm,
				   type *block_xfilterL,type *block_xfilterU,
				   type *block_yfilterL,type *block_yfilterU,
				   type *block_zfilterL,type *block_zfilterU,
				   type *block_West_filter,type *block_East_filter,
				   type *block_South_filter,type *block_North_filter,
				   type *block_Bottom_filter,type *block_Top_filter,				   
				   cudaStream_t *cudaStream_Hi_Priority 
							  );
    
#endif
