/* This is -*- c -*- header (not Fortran) */
/**
 * @file LPTbnd.h
 * @brief Declarations of binding functions and miscellaneous functions
 */

#ifndef JUPITER_LPT_BND_H
#define JUPITER_LPT_BND_H

#include "LPTdefs.h"

#ifdef JUPITER_LPT_USE_MPI
#include <mpi.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Allocates LPT-related memory region
 * @param iset Allocation category
 * @param npta Number of particles to allocate
 * @param nx   Number of cells in X-axis
 * @param ny   Number of cells in Y-axis
 * @param nz   Number of cells in Z-axis
 * @param istat Sets to non-zero value when errors occured, if given
 *
 * @p iset is currently accepts 1 or 2. For 1, allocates basic parameters
 * of LPT data. For 2, allocates node data of velocities. Other @p iset
 * values are just ignored and this function does nothing.
 *
 * Number of particles must equal or greater then the sum of particles
 * in each particle sets.
 *
 * Numbers of cells are the numbers without stencils, current rank.
 */
JUPITER_LPT_DECL
void cLPTalloc(int iset, int npta, int nx, int ny, int nz, int *istat);

/**
 * @brief Deallocates LPT-related memory region
 * @param iset Allocation category
 *
 * @p iset is currently accepts 0, 1 or 2. For 0, deallocates data
 * used for binding C and Fortran. For 1, deallocates basic parameters
 * of LPT data. For 2, deallocates node data of velocities. Other @p
 * iset values are just ignored and this function does nothing.
 */
JUPITER_LPT_DECL
void cLPTdealloc(int iset);

/**
 * @brief Retrieve unit number for error output (i.e., stderr)
 * @return Fortran unit number for error output
 *
 * Returned unit number may be no longer associated to `stderr`,
 * when any fortran code opens a file for the unit number.
 */
JUPITER_LPT_DECL
int cLPTget_error_unit(void);

/**
 * @brief Retrieve unit number for standard output (i.e., stdout)
 * @return Fortran unit number for standard output
 *
 * Returned unit number may be no longer associated to `stderr`,
 * when any fortran code opens a file for the unit number.
 */
JUPITER_LPT_DECL
int cLPTget_output_unit(void);

/**
 * @brief Opens the LPT logfile
 * @param iun The fortran unit number to be used for
 * @param lpath The buffer size of the @p cpathptr
 * @param cpathptr Path name to be used for
 * @param iappend Whether open with appending to the file (non-0), or
 *                discarding the old content (0).
 * @param istat Sets non-zero value when error orccured, if given.
 *
 * @p iun allows to be negative. If so, the LPT's default unit number is
 * used. It's specified by cLPTalloc(1, ...), or any Fortran code can
 * modify it.
 *
 * If @p iun is non-negative value, let LPT library to use that unit
 * number.
 *
 * If the specified or default unit number is equal to the return
 * value of cLPTget_output_unit() or cLPTget_error_unit(), this
 * function does nothing except for setting the unit number.
 *
 * If given @p cpathptr is NULL or an empty string, this function uses
 * the Fortran default (typically fort.nnn). And then returns actually
 * opened filename to @p cpathptr, upto @p lpath - 1 bytes, if @p
 * cpathptr is not NULL and that information is available. @p cpathptr
 * will be unchanged (i.e., empty string) if opened default file name
 * is unavailable.
 *
 * If any file associated to the specified unit number, it will be
 * closed before openning.
 *
 * This method is not MPI collective. You must give different path
 * names to avoid file collision. But currently, the messages only
 * be written by the rank 0 of specified MPI communicator.
 *
 * @note The NUL character is set at the trimmed length, for the
 *       default name obtained to @p cpathptr.
 *
 * @note The default name obtained to @p cpathptr might be truncated
 *       even if the string length of @p cpathptr is not equal to @p
 *       lpath - 1. Usually, each OS defines OS-dependent maximum
 *       length of path, which can avoid truncation. But this does not
 *       resolve the problem that @p cpathptr might not point *real*
 *       file name, which ends with spaces for example. Therefore, the
 *       default name obtained to @p cpathptr is not available for
 *       another file operations, such as rename, remove, or open on
 *       C-side.
 */
JUPITER_LPT_DECL
void cLPTopenlogfile(int iun, int lpath, char *cpathptr, int iappend, int *istat);

#ifdef JUPITER_LPT_USE_MPI
/**
 * @brief Setup LPT to use specifed communicator
 * @param icomm communicator to be used
 *
 * @p icomm needs to be converted MPI_Comm_c2f() for setting
 * communicators generated by MPI C API.
 */
JUPITER_LPT_DECL
void cLPTsetmpivars(MPI_Fint icomm);

/**
 * @brief Setup LPT to use specifed communicator
 * @param comm communicator to be used
 */
static inline void cLPTsetmpicomm(MPI_Comm comm)
{
  MPI_Fint fcomm;

  fcomm = MPI_Comm_c2f(comm);
  cLPTsetmpivars(fcomm);
}
#endif

/**
 * @brief Setup rank connection on continuous domain
 * @param zm Neighbor MPI rank number on Z-, or -1 if not applicable
 * @param zp Neighbor MPI rank number on Z+, or -1 if not applicable
 * @param ym Neighbor MPI rank number on Y-, or -1 if not applicable
 * @param yp Neighbor MPI rank number on Y+, or -1 if not applicable
 * @param zm Neighbor MPI rank number on X-, or -1 if not applicable
 * @param zp Neighbor MPI rank number on X+, or -1 if not applicable
 *
 * LPT uses these values informational only. Consistency will not be
 * checked and not used for communications.
 */
JUPITER_LPT_DECL
void cLPTsetmpineighbors(int zm, int zp, int ym, int yp, int xm, int xp);

/**
 * @brief Maximum number of allowable particle sets
 * @return maximum number of allowable particle sets, -1 if error
 *
 * The value is constant, and cannot be modified (at runtime).
 */
JUPITER_LPT_DECL
int cLPTmxpset(void);

JUPITER_LPT_DECL
int cLPTgetnpset(void);

JUPITER_LPT_DECL
void cLPTsetnpset(int npset, int *stat);

JUPITER_LPT_DECL
int cLPTgetnpt(void);

JUPITER_LPT_DECL
int cLPTgetipttim(void);

JUPITER_LPT_DECL
void cLPTsetipttim(int ipt);

JUPITER_LPT_DECL
LPT_type cLPTgettip(void);

JUPITER_LPT_DECL
void cLPTsettip(LPT_type tip);

JUPITER_LPT_DECL
LPT_type cLPTgettimprn(void);

JUPITER_LPT_DECL
void cLPTsettimprn(LPT_type prn);

JUPITER_LPT_DECL
int cLPTgetwbcal(void);

JUPITER_LPT_DECL
void cLPTsetwbcal(int ival);

/**
 * @brief Sets the parameters of a particle set
 * @param iset The index of a particle set to set
 * @param npt  Number of particles to generate on the set
 * @param itr  Whether generate particles randomly on the time-domain
 * @param xs   Start point of X-axis of generating region [m]
 * @param xe   End point of X-axis of generating region [m]
 * @param ys   Start point of Y-axis of generating region [m]
 * @param ye   End point of Y-axis of generating region [m]
 * @param zs   Start point of Z-axis of generating region [m]
 * @param ze   End point of Z-axis of generating region [m]
 * @param tms  Start time [s]
 * @param tme  End time [s]
 * @param di   Diameter of particles [m]
 * @param ri   Density of particles [m]
 * @param ux   Initial X-velocity [m/s]
 * @param uy   Initial Y-velocity [m/s]
 * @param uz   Initial Z-velocity [m/s]
 * @param istat Sets non-zero value when error occured, if given
 *
 * The valid indices for @p iset is from 1 to the return value of
 * cLPTmxpset(), inclusive.
 */
JUPITER_LPT_DECL
void cLPTsetpset(int iset, int npt, int itr,
                 LPT_type xs, LPT_type xe, LPT_type ys, LPT_type ye,
                 LPT_type zs, LPT_type ze, LPT_type tms, LPT_type tme,
                 LPT_type di, LPT_type ri,
                 LPT_type ux, LPT_type uy, LPT_type uz, int *istat);

/**
 * @brief Gets the parameters of a particle set
 * @param iset The index of a particle set to get
 * @param npt  Sets Number of particles to generate on the set
 * @param itr  Sets Whether generate particles randomly on the time-domain
 * @param xs   Sets Start point of X-axis of generating region [m]
 * @param xe   Sets End point of X-axis of generating region [m]
 * @param ys   Sets Start point of Y-axis of generating region [m]
 * @param ye   Sets End point of Y-axis of generating region [m]
 * @param zs   Sets Start point of Z-axis of generating region [m]
 * @param ze   Sets End point of Z-axis of generating region [m]
 * @param tms  Sets Start time [s]
 * @param tme  Sets End time [s]
 * @param di   Sets Diameter of particles [m]
 * @param ri   Sets Density of particles [m]
 * @param ux   Sets Initial X-velocity [m/s]
 * @param uy   Sets Initial Y-velocity [m/s]
 * @param uz   Sets Initial Z-velocity [m/s]
 * @param istat Sets non-zero value when error occured, if given
 *
 * All arguments are optional. The values will return only for
 * non-NULL arguments.
 */
JUPITER_LPT_DECL
void cLPTgetpset(int iset, int *npt, int *itr,
                 LPT_type *xs, LPT_type *xe, LPT_type *ys, LPT_type *ye,
                 LPT_type *zs, LPT_type *ze, LPT_type *tms, LPT_type *tme,
                 LPT_type *di, LPT_type *ri,
                 LPT_type *ux, LPT_type *uy, LPT_type *uz, int *istat);

/**
 * @brief Clear particle set parameters.
 * @param iset The index of particle sets to clear.
 *
 * This function just calls cLPTsetpset() with all zero arguments.
 */
static inline void cLPTclearpset(int iset)
{
  int istat;
  cLPTsetpset(iset, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
              0.0, 0.0, 0.0, 0.0, &istat);
}

/**
 * @brief Initialize LPT_pset struct with all zero
 * @param set particle set to initialize
 */
static inline void cLPTpset_init(LPT_pset *set)
{
  LPT_range rzero = { 0.0, 0.0 };
  LPT_vector vzero = { 0.0, 0.0, 0.0 };
  set->itrdm = 0;
  set->nistpt = 0;
  set->x = rzero;
  set->y = rzero;
  set->z = rzero;
  set->tm = rzero;
  set->u = vzero;
  set->di = 0.0;
  set->ri = 0.0;
}

/**
 * @brief Set particle set parameters via LPT_pset struct
 * @param iset The index number to set parameters.
 * @param set Parameters to set
 * @return 0 if success, otherwise an error occured
 */
static inline int cLPTsetpsetm(int iset, const LPT_pset *set)
{
  int istat = 0;
  cLPTsetpset(iset, set->nistpt, set->itrdm, set->x.start, set->x.end,
              set->y.start, set->y.end, set->z.start, set->z.end,
              set->tm.start, set->tm.end, set->di, set->ri,
              set->u.x, set->u.y, set->u.z, &istat);
  return istat;
}

/**
 * @brief Get particle set parameters to LPT_pset struct
 * @param iset The index number to get parameters.
 * @param istat Set non-zero value when errors occured, if given
 * @return Read parameters
 *
 * The content of returned value is undefined when errors occured.
 */
static inline LPT_pset cLPTgetpsetm(int iset, int *istat)
{
  LPT_pset set;
  cLPTgetpset(iset, &set.nistpt, &set.itrdm, &set.x.start, &set.x.end,
              &set.y.start, &set.y.end, &set.z.start, &set.z.end,
              &set.tm.start, &set.tm.end, &set.di, &set.ri,
              &set.u.x, &set.u.y, &set.u.z, istat);
  return set;
}

static inline
int cLPTset_fp2soa(LPT_particles *p, enum LPT_realptval val, LPT_type *v)
{
  switch(val) {
  case LPT_FP_UXF:   p->uxf = v; break;
  case LPT_FP_UYF:   p->uyf = v; break;
  case LPT_FP_UZF:   p->uzf = v; break;
  case LPT_FP_XPT:   p->xpt = v; break;
  case LPT_FP_YPT:   p->ypt = v; break;
  case LPT_FP_ZPT:   p->zpt = v; break;
  case LPT_FP_UXPT:  p->uxpt = v; break;
  case LPT_FP_UYPT:  p->uypt = v; break;
  case LPT_FP_UZPT:  p->uzpt = v; break;
  case LPT_FP_TIMPT: p->timpt = v; break;
  case LPT_FP_RHOPT: p->rhopt = v; break;
  case LPT_FP_DIAPT: p->diapt = v; break;
  case LPT_FP_FUXPT: p->fuxpt = v; break;
  case LPT_FP_FUYPT: p->fuypt = v; break;
  case LPT_FP_FUZPT: p->fuzpt = v; break;
  case LPT_FP_FDUXT: p->fduxt = v; break;
  case LPT_FP_FDUYT: p->fduyt = v; break;
  case LPT_FP_FDUZT: p->fduzt = v; break;
  case LPT_FP_INVALID:
  default:
    return 1;
  }
  return 0;
}

static inline
int cLPTset_ip2soa(LPT_particles *p, enum LPT_intptval val, int *v)
{
  switch(val) {
  case LPT_IP_ICFPT:  p->icfpt = v; break;
  case LPT_IP_JCFPT:  p->jcfpt = v; break;
  case LPT_IP_KCFPT:  p->kcfpt = v; break;
  case LPT_IP_IFPSRD: p->ifpsrd = v; break;
  case LPT_IP_IWPSRD: p->iwpsrd = v; break;
  case LPT_IP_INVALID:
  default:
    return 1;
  }
  return 0;
}

static inline
LPT_particles cLPTnull_pts_soa(void)
{
  LPT_particles pts = { 0 };
  return pts;
}

/**
 * @brief Bulk set multiple particle data
 * @param nidxs Number of elements in idxs array
 * @param idxs  Array of index ranges
 *
 * If @p nidxs is 1, sets the values to the each given variables for
 * the index of the value in single element array @p idxs.
 *
 * If @p nidxs is greater than 1, @p nidxs is treated as an array of
 * pair of start and end indices. If @p nidxs is odd, the last element
 * will be ignored.
 *
 * Null given variables will be skipped for setting.
 *
 * @note `size_t` arguments are treated as signed integer in Fortran
 *       routine. I believe that signed counter part in Fortran
 *       language, same size to `size_t` is used. Negative values
 *       on the evaluation of `size_t` variable returns error.
 */
JUPITER_LPT_DECL
void cLPTsetpts(size_t nidxs, size_t *idxs,
                LPT_type *uxf, LPT_type *uyf, LPT_type *uzf,
                LPT_type *xpt, LPT_type *ypt, LPT_type *zpt,
                LPT_type *uxpt, LPT_type *uypt, LPT_type *uzpt,
                LPT_type *timpt, LPT_type *rhopt, LPT_type *diapt,
                LPT_type *fuxpt, LPT_type *fuypt, LPT_type *fuzpt,
                LPT_type *fduxt, LPT_type *fduyt, LPT_type *fduzt,
                int *icpt, int *jcpt, int *kcpt, int *ifps, int *iwps,
                int *istat);

static inline
int cLPTsetpts_soa(size_t nidxs, size_t *idxs, LPT_particles *pts)
{
  int stat;
  stat = 0;
  cLPTsetpts(nidxs, idxs, pts->uxf, pts->uyf, pts->uzf,
             pts->xpt, pts->ypt, pts->zpt,
             pts->uxpt, pts->uypt, pts->uzpt,
             pts->timpt, pts->rhopt, pts->diapt,
             pts->fuxpt, pts->fuypt, pts->fuzpt,
             pts->fduxt, pts->fduyt, pts->fduzt,
             pts->icfpt, pts->jcfpt, pts->kcfpt, pts->ifpsrd, pts->iwpsrd,
             &stat);
  return stat;
}

static inline
int cLPTsetpts_aos_1(size_t idx, LPT_particle pt)
{
  int stat;
  stat = 0;
  cLPTsetpts(1, &idx, &pt.uf.x, &pt.uf.y, &pt.uf.z,
             &pt.pt.x, &pt.pt.y, &pt.pt.z, &pt.upt.x, &pt.upt.y, &pt.upt.z,
             &pt.timpt, &pt.rhopt, &pt.diapt,
             &pt.fupt.x, &pt.fupt.y, &pt.fupt.z,
             &pt.fdut.x, &pt.fdut.y, &pt.fdut.z,
             &pt.icfpt, &pt.jcfpt, &pt.kcfpt, &pt.ifpsrd, &pt.iwpsrd, &stat);
  return stat;
}

static inline
int cLPTsetpts_1f(enum LPT_realptval val, size_t nidxs, size_t *idxs, LPT_type *v)
{
  LPT_particles pts = { 0 };
  if (cLPTset_fp2soa(&pts, val, v)) return 1;
  return cLPTsetpts_soa(nidxs, idxs, &pts);
}

static inline
int cLPTsetpts_1i(enum LPT_intptval val, size_t nidxs, size_t *idxs, int *v)
{
  LPT_particles pts = { 0 };
  if (cLPTset_ip2soa(&pts, val, v)) return 1;
  return cLPTsetpts_soa(nidxs, idxs, &pts);
}

/**
 * @brief Bulk get multiple particle data
 * @param nidxs Number of elements in idxs array
 * @param idxs  Array of index ranges
 *
 * If @p nidxs is 1, sets the values to the each given variables for
 * the index of the value in single element array @p idxs.
 *
 * If @p nidxs is greater than 1, @p nidxs is treated as an array of
 * pair of start and end indices. If @p nidxs is odd, the last element
 * will be ignored.
 *
 * Null given variables will be skipped for getting.
 *
 * @note `size_t` arguments are treated as signed integer in Fortran
 *       routine. I believe that signed counter part in Fortran
 *       language, same size to `size_t` is used. Negative values
 *       on the evaluation of `size_t` variable returns error.
 */
JUPITER_LPT_DECL
void cLPTgetpts(size_t nidxs, size_t *idxs,
                LPT_type *uxf, LPT_type *uyf, LPT_type *uzf,
                LPT_type *xpt, LPT_type *ypt, LPT_type *zpt,
                LPT_type *uxpt, LPT_type *uypt, LPT_type *uzpt,
                LPT_type *timpt, LPT_type *rhopt, LPT_type *diapt,
                LPT_type *fuxpt, LPT_type *fuypt, LPT_type *fuzpt,
                LPT_type *fduxt, LPT_type *fduyt, LPT_type *fduzt,
                int *icpt, int *jcpt, int *kcpt, int *ifps, int *iwps,
                int *istat);

/**
 * @brief Get partcle data to given SOA structure
 * @param nidxs Number of elements in idxs
 * @param idxs  Array of particle indices
 * @param pts   SOA structure
 * @return 0 if success, otherwise error.
 *
 * @warning This function does not check whether allocated memory
 * for each entries in @p pts is enough to store the result data.
 */
static inline
int cLPTgetpts_soa(size_t nidxs, size_t *idxs, LPT_particles *pts)
{
  int stat;
  stat = 0;
  cLPTgetpts(nidxs, idxs, pts->uxf, pts->uyf, pts->uzf,
             pts->xpt, pts->ypt, pts->zpt, pts->uxpt, pts->uypt, pts->uzpt,
             pts->timpt, pts->rhopt, pts->diapt,
             pts->fuxpt, pts->fuypt, pts->fuzpt,
             pts->fduxt, pts->fduyt, pts->fduzt,
             pts->icfpt, pts->jcfpt, pts->kcfpt, pts->ifpsrd, pts->iwpsrd,
             &stat);
  return stat;
}

/**
 * @brief Get single partcle data to given AOS structure
 * @param idx   Index particle to obtain
 * @param pts   SOA structure
 * @return 0 if success, otherwise error.
 */
static inline
int cLPTgetpts_aos_1(size_t idx, LPT_particle *pt)
{
  int stat;
  stat = 0;
  cLPTgetpts(1, &idx, &pt->uf.x, &pt->uf.y, &pt->uf.z,
             &pt->pt.x, &pt->pt.y, &pt->pt.z,
             &pt->upt.x, &pt->upt.y, &pt->upt.z,
             &pt->timpt, &pt->rhopt, &pt->rhopt,
             &pt->fupt.x, &pt->fupt.y, &pt->fupt.z,
             &pt->fdut.x, &pt->fdut.y, &pt->fdut.z,
             &pt->icfpt, &pt->jcfpt, &pt->kcfpt, &pt->ifpsrd, &pt->iwpsrd,
             &stat);
  return stat;
}

static inline
int cLPTgetpts_1f(enum LPT_realptval val, size_t nidxs, size_t *idxs, LPT_type *v)
{
  LPT_particles pts = { 0 };
  if (cLPTset_fp2soa(&pts, val, v)) return 1;
  return cLPTgetpts_soa(nidxs, idxs, &pts);
}

static inline
int cLPTgetpts_3f(enum LPT_realptval val1, enum LPT_realptval val2,
                  enum LPT_realptval val3, size_t nidxs, size_t *idxs,
                  LPT_type *v1, LPT_type *v2, LPT_type *v3)
{
  LPT_particles pts = { 0 };
  if (cLPTset_fp2soa(&pts, val1, v1)) return 1;
  if (cLPTset_fp2soa(&pts, val2, v2)) return 1;
  if (cLPTset_fp2soa(&pts, val3, v3)) return 1;
  return cLPTgetpts_soa(nidxs, idxs, &pts);
}

static inline
int cLPTgetpts_1i(enum LPT_intptval val, size_t nidxs, size_t *idxs, int *v)
{
  LPT_particles pts = { 0 };
  if (cLPTset_ip2soa(&pts, val, v)) return 1;
  return cLPTgetpts_soa(nidxs, idxs, &pts);
}

JUPITER_LPT_DECL
void cLPTsetfield_unchecked(int ivar, void *input, int nx, int ny, int nz,
                            int stm, int stp, int *idxs, int nidxs,
                            int *istat);

static inline
void cLPTsetfield_r(enum LPT_realfield fvar, LPT_type *input,
                    int nx, int ny, int nz, int stm, int stp,
                    int *idxs, int nidxs, int *istat)
{
  cLPTsetfield_unchecked(fvar, input, nx, ny, nz, stm, stp, idxs, nidxs,
                         istat);
}

static inline
void cLPTsetfield_i(enum LPT_intfield fvar, LPT_type *input,
                    int nx, int ny, int nz, int stm, int stp,
                    int *idxs, int nidxs, int *istat)
{
  cLPTsetfield_unchecked(fvar, input, nx, ny, nz, stm, stp, idxs, nidxs,
                         istat);
}

JUPITER_LPT_DECL
void cLPTcal0(LPT_type *xfgrid, LPT_type *yfgrid, LPT_type *zfgrid,
              LPT_type time, int nx, int ny, int nz, int stm, int stp,
              int *istat);

JUPITER_LPT_DECL
void cLPTcal(int istep,
             LPT_type *vxf1, LPT_type *vyf1, LPT_type *vzf1,
             LPT_type *vxf2, LPT_type *vyf2, LPT_type *vzf2,
             LPT_type *rhof1, LPT_type *rhof2,
             LPT_type *vmuf1, LPT_type *vmuf2,
             LPT_type *xfgrid, LPT_type *yfgrid, LPT_type *zfgrid,
             LPT_type gx, LPT_type gy, LPT_type gz, LPT_type dt,
             LPT_type time, int nx, int ny, int nz, int stm, int stp,
             int *istat);

/**
 * @brief Sets error callback function
 * @param func function pointer to set callback
 * @param arg  extra data to be passed to @p func
 *
 * Windows note: function must be cdecl calling convention
 */
JUPITER_LPT_DECL
void cLPTset_error_callback(LPT_error_callback *func, void *arg);

/**
 * @brief Sets udwbc callback function
 * @param func function pointer to set callback
 * @param arg  extra data to be passed to @p func
 *
 * Windows note: function must be cdecl calling convention
 */
JUPITER_LPT_DECL
void cLPTset_udwbc_callback(LPT_udwbc_callback *func, void *arg);

#ifdef __cplusplus
}
#endif

#endif
