/* Generated by re2c 4.5 */
/* This is -*- c -*- source. */
/* This is vim: set ft=c: source. */
/**
 * @addtogroup cmake_doxygen_filter
 * @{
 * @file cmake-doxygen-filter.c
 * @brief Filters CMake source to Doxygen input.
 *
 * Filters CMake source to Doxygen input by formatting like Javascript.
 * (i.e., use Javascript parser for CMake files in your Doxyfile)
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <stddef.h>
#include <stdarg.h>
#include <limits.h>
#include <assert.h>
#include <stdint.h>
#include <inttypes.h>

#define DEFAULT_PROG_NAME "cmake-doxygen-filter"

#include "doxygen-filter.h"

#include <jupiter/re2c_lparser/re2c_lparser.h>

static int cmake_doxygen_filter(FILE *input, const char *ifname,
                                FILE *output, const char *ofname);

/**
 * @brief Main function of CMake to Doxygen filter
 */
int main(int argc, char **argv)
{
  int iarg;

  if (argc > 0) {
    set_prog_name(argv[0]);
  } else {
    set_prog_name("");
  }

  if (argc <= 1) {
    print_error("No file name given");
    return 1;
  }

  for(iarg = 1; iarg < argc; ++iarg) {
    FILE *fp;
    int ret;
    errno = 0;
    fp = fopen(argv[iarg], "rb");
    if (!fp) {
      if (errno != 0) {
        print_error("cannot open %s: %s", argv[iarg], strerror(errno));
      } else {
        print_error("cannot open %s", argv[iarg]);
      }
      return 1;
    }
    ret = cmake_doxygen_filter(fp, argv[iarg], stdout, "<stdout>");
    fclose(fp);
    if (ret) return ret;
  }
  return 0;
}



static int cmake_doxygen_filter(FILE *input, const char *ifname,
                                FILE *output, const char *ofname)
{
  int ret;
  int cont_of_doxcomment;
  int indent;
  int i;
  struct re2c_lparser pp;
  struct re2c_lparser *p = &pp;

  re2c_lparser_init(p);
  if (re2c_lparser_fill(p, input, ifname, 0, NULL) < 0) {
    return 1;
  }

  ret = 0;
  indent = 0;
  cont_of_doxcomment = 0;

  while (!re2c_lparser_eof(p)) {
    re2c_lparser_start_token(p);
    /* debug_parser(p); */

    
    {
      unsigned char yych;
      unsigned int yyaccept = 0;
      if ((p->lim - p->cur) < 6) { if (re2c_lparser_fill(p, input, ifname, 6, NULL) < 0) goto error; }
      yych = *p->cur;
      if (yych <= '#') {
        if (yych <= '\f') {
          if (yych <= 0x08) goto yy1;
          if (yych <= '\t') goto yy2;
          if (yych <= '\n') goto yy3;
        } else {
          if (yych <= 0x1F) {
            if (yych <= '\r') goto yy5;
          } else {
            if (yych <= ' ') goto yy2;
            if (yych >= '#') goto yy6;
          }
        }
      } else {
        if (yych <= 0xE0) {
          if (yych <= 0x7F) goto yy1;
          if (yych <= 0xC1) goto yy8;
          if (yych <= 0xDF) goto yy10;
          goto yy11;
        } else {
          if (yych <= 0xF0) {
            if (yych <= 0xEF) goto yy12;
            goto yy13;
          } else {
            if (yych <= 0xF3) goto yy14;
            if (yych <= 0xF4) goto yy15;
            goto yy8;
          }
        }
      }
yy1:
      ++p->cur;
      { p->cur = p->tok; cont_of_doxcomment = 0; goto command; }
yy2:
      ++p->cur;
      { re2c_lparser_loc_upd_utf8(p); continue; }
yy3:
      ++p->cur;
yy4:
      { re2c_lparser_loc_upd_utf8(p); goto newline; }
yy5:
      yych = *++p->cur;
      if (yych == '\n') goto yy3;
      goto yy4;
yy6:
      yyaccept = 0;
      yych = *(p->mrk = ++p->cur);
      if (yych == '#') goto yy16;
yy7:
      { re2c_lparser_loc_upd_utf8(p); goto comment; }
yy8:
      ++p->cur;
yy9:
      { goto invalid_utf8; }
yy10:
      yych = *++p->cur;
      if (yych <= 0x7F) goto yy9;
      if (yych <= 0xBF) goto yy1;
      goto yy9;
yy11:
      yyaccept = 1;
      yych = *(p->mrk = ++p->cur);
      if (yych <= 0x9F) goto yy9;
      if (yych <= 0xBF) goto yy18;
      goto yy9;
yy12:
      yyaccept = 1;
      yych = *(p->mrk = ++p->cur);
      if (yych <= 0x7F) goto yy9;
      if (yych <= 0xBF) goto yy18;
      goto yy9;
yy13:
      yyaccept = 1;
      yych = *(p->mrk = ++p->cur);
      if (yych <= 0x8F) goto yy9;
      if (yych <= 0xBF) goto yy19;
      goto yy9;
yy14:
      yyaccept = 1;
      yych = *(p->mrk = ++p->cur);
      if (yych <= 0x7F) goto yy9;
      if (yych <= 0xBF) goto yy19;
      goto yy9;
yy15:
      yyaccept = 1;
      yych = *(p->mrk = ++p->cur);
      if (yych <= 0x7F) goto yy9;
      if (yych <= 0x8F) goto yy19;
      goto yy9;
yy16:
      yych = *++p->cur;
      if (yych <= 0xDF) {
        if (yych <= '#') {
          if (yych <= '"') {
            p->ctxmrk = p->cur;
            goto yy20;
          }
        } else {
          if (yych <= 0x7F) {
            p->ctxmrk = p->cur;
            goto yy20;
          }
          if (yych >= 0xC2) {
            p->ctxmrk = p->cur;
            goto yy21;
          }
        }
      } else {
        if (yych <= 0xF0) {
          if (yych <= 0xE0) {
            p->ctxmrk = p->cur;
            goto yy22;
          }
          if (yych <= 0xEF) {
            p->ctxmrk = p->cur;
            goto yy23;
          }
          p->ctxmrk = p->cur;
          goto yy24;
        } else {
          if (yych <= 0xF3) {
            p->ctxmrk = p->cur;
            goto yy25;
          }
          if (yych <= 0xF4) {
            p->ctxmrk = p->cur;
            goto yy26;
          }
        }
      }
yy17:
      p->cur = p->mrk;
      if (yyaccept == 0) goto yy7;
      else goto yy9;
yy18:
      yych = *++p->cur;
      if (yych <= 0x7F) goto yy17;
      if (yych <= 0xBF) goto yy1;
      goto yy17;
yy19:
      yych = *++p->cur;
      if (yych <= 0x7F) goto yy17;
      if (yych <= 0xBF) goto yy18;
      goto yy17;
yy20:
      ++p->cur;
      p->cur = p->ctxmrk;
      { re2c_lparser_loc_upd_utf8(p); goto doxycomment; }
yy21:
      yych = *++p->cur;
      if (yych <= 0x7F) goto yy17;
      if (yych <= 0xBF) goto yy20;
      goto yy17;
yy22:
      yych = *++p->cur;
      if (yych <= 0x9F) goto yy17;
      if (yych <= 0xBF) goto yy21;
      goto yy17;
yy23:
      yych = *++p->cur;
      if (yych <= 0x7F) goto yy17;
      if (yych <= 0xBF) goto yy21;
      goto yy17;
yy24:
      yych = *++p->cur;
      if (yych <= 0x8F) goto yy17;
      if (yych <= 0xBF) goto yy23;
      goto yy17;
yy25:
      yych = *++p->cur;
      if (yych <= 0x7F) goto yy17;
      if (yych <= 0xBF) goto yy23;
      goto yy17;
yy26:
      yych = *++p->cur;
      if (yych <= 0x7F) goto yy17;
      if (yych <= 0x8F) goto yy23;
      goto yy17;
    }


  newline:
    re2c_lparser_copy_token(p, output);
    cont_of_doxcomment = 0;
    continue;

  comment:
    if (cont_of_doxcomment) {
      for(i = indent; i > 0; i--) fprintf(output, "  ");
#ifdef PYTHON_OUTPUT
      fprintf(output, "#");
#else
      fprintf(output, "///");
#endif
      goto doxcomment_cont;
    }
    while(!re2c_lparser_eof(p)) {
      re2c_lparser_start_token(p);
      
      {
        unsigned char yych;
        if ((p->lim - p->cur) < 4) { if (re2c_lparser_fill(p, input, ifname, 4, NULL) < 0) goto error; }
        yych = *p->cur;
        if (yych <= 0xC1) {
          if (yych <= '\f') {
            if (yych == '\n') goto yy29;
          } else {
            if (yych <= '\r') goto yy31;
            if (yych >= 0x80) goto yy32;
          }
        } else {
          if (yych <= 0xEF) {
            if (yych <= 0xDF) goto yy34;
            if (yych <= 0xE0) goto yy35;
            goto yy36;
          } else {
            if (yych <= 0xF0) goto yy37;
            if (yych <= 0xF3) goto yy38;
            if (yych <= 0xF4) goto yy39;
            goto yy32;
          }
        }
yy28:
        ++p->cur;
        {
          re2c_lparser_loc_upd_utf8(p);
          continue;
        }
yy29:
        ++p->cur;
yy30:
        {
          re2c_lparser_loc_upd_utf8(p);
          re2c_lparser_copy_token(p, output);
          break;
        }
yy31:
        yych = *++p->cur;
        if (yych == '\n') goto yy29;
        goto yy30;
yy32:
        ++p->cur;
yy33:
        { goto invalid_utf8; }
yy34:
        yych = *++p->cur;
        if (yych <= 0x7F) goto yy33;
        if (yych <= 0xBF) goto yy28;
        goto yy33;
yy35:
        yych = *(p->mrk = ++p->cur);
        if (yych <= 0x9F) goto yy33;
        if (yych <= 0xBF) goto yy40;
        goto yy33;
yy36:
        yych = *(p->mrk = ++p->cur);
        if (yych <= 0x7F) goto yy33;
        if (yych <= 0xBF) goto yy40;
        goto yy33;
yy37:
        yych = *(p->mrk = ++p->cur);
        if (yych <= 0x8F) goto yy33;
        if (yych <= 0xBF) goto yy42;
        goto yy33;
yy38:
        yych = *(p->mrk = ++p->cur);
        if (yych <= 0x7F) goto yy33;
        if (yych <= 0xBF) goto yy42;
        goto yy33;
yy39:
        yych = *(p->mrk = ++p->cur);
        if (yych <= 0x7F) goto yy33;
        if (yych <= 0x8F) goto yy42;
        goto yy33;
yy40:
        yych = *++p->cur;
        if (yych <= 0x7F) goto yy41;
        if (yych <= 0xBF) goto yy28;
yy41:
        p->cur = p->mrk;
        goto yy33;
yy42:
        yych = *++p->cur;
        if (yych <= 0x7F) goto yy41;
        if (yych <= 0xBF) goto yy40;
        goto yy41;
      }

    }
    continue;

  doxycomment:
    cont_of_doxcomment = 1;
    for(i = indent; i > 0; i--) fprintf(output, "  ");
#ifdef PYTHON_OUTPUT
    fprintf(output, "##");
#else
    fprintf(output, "///");
#endif
  doxcomment_cont:
    while (!re2c_lparser_eof(p)) {
      re2c_lparser_start_token(p);
      
      {
        unsigned char yych;
        if ((p->lim - p->cur) < 4) { if (re2c_lparser_fill(p, input, ifname, 4, NULL) < 0) goto error; }
        yych = *p->cur;
        if (yych <= 0xC1) {
          if (yych <= '\f') {
            if (yych == '\n') goto yy45;
          } else {
            if (yych <= '\r') goto yy47;
            if (yych >= 0x80) goto yy48;
          }
        } else {
          if (yych <= 0xEF) {
            if (yych <= 0xDF) goto yy50;
            if (yych <= 0xE0) goto yy51;
            goto yy52;
          } else {
            if (yych <= 0xF0) goto yy53;
            if (yych <= 0xF3) goto yy54;
            if (yych <= 0xF4) goto yy55;
            goto yy48;
          }
        }
yy44:
        ++p->cur;
        {
          re2c_lparser_loc_upd_utf8(p);
          re2c_lparser_copy_token(p, output);
          continue;
        }
yy45:
        ++p->cur;
yy46:
        {
          re2c_lparser_loc_upd_utf8(p);
          re2c_lparser_copy_token(p, output);
          break;
        }
yy47:
        yych = *++p->cur;
        if (yych == '\n') goto yy45;
        goto yy46;
yy48:
        ++p->cur;
yy49:
        { goto invalid_utf8; }
yy50:
        yych = *++p->cur;
        if (yych <= 0x7F) goto yy49;
        if (yych <= 0xBF) goto yy44;
        goto yy49;
yy51:
        yych = *(p->mrk = ++p->cur);
        if (yych <= 0x9F) goto yy49;
        if (yych <= 0xBF) goto yy56;
        goto yy49;
yy52:
        yych = *(p->mrk = ++p->cur);
        if (yych <= 0x7F) goto yy49;
        if (yych <= 0xBF) goto yy56;
        goto yy49;
yy53:
        yych = *(p->mrk = ++p->cur);
        if (yych <= 0x8F) goto yy49;
        if (yych <= 0xBF) goto yy58;
        goto yy49;
yy54:
        yych = *(p->mrk = ++p->cur);
        if (yych <= 0x7F) goto yy49;
        if (yych <= 0xBF) goto yy58;
        goto yy49;
yy55:
        yych = *(p->mrk = ++p->cur);
        if (yych <= 0x7F) goto yy49;
        if (yych <= 0x8F) goto yy58;
        goto yy49;
yy56:
        yych = *++p->cur;
        if (yych <= 0x7F) goto yy57;
        if (yych <= 0xBF) goto yy44;
yy57:
        p->cur = p->mrk;
        goto yy49;
yy58:
        yych = *++p->cur;
        if (yych <= 0x7F) goto yy57;
        if (yych <= 0xBF) goto yy56;
        goto yy57;
      }

    }
    continue;

  command:
    {
      int cnt_paren;
      int narg;
      const char *cur_save;
      enum command_name {
        others,
        option, dep_option, function, endfunction, cmake_foreach, endforeach,
        cmake_if, endif, cmake_while, endwhile,
        set, macro, endmacro,
      } command;

      p->lexeme = p->tok;
      do {
        re2c_lparser_start_token(p);
        
        {
          unsigned char yych;
          unsigned int yyaccept = 0;
          if ((p->lim - p->cur) < 4) { if (re2c_lparser_fill(p, input, ifname, 4, NULL) < 0) goto error; }
          yych = *p->cur;
          if (yych <= 0x7F) {
            if (yych <= '^') {
              if (yych <= ' ') goto yy60;
              if (yych <= '@') goto yy62;
              if (yych <= 'Z') goto yy64;
              goto yy62;
            } else {
              if (yych == '`') goto yy62;
              if (yych <= 'z') goto yy64;
              goto yy62;
            }
          } else {
            if (yych <= 0xEF) {
              if (yych <= 0xC1) goto yy60;
              if (yych <= 0xDF) goto yy65;
              if (yych <= 0xE0) goto yy66;
              goto yy67;
            } else {
              if (yych <= 0xF0) goto yy68;
              if (yych <= 0xF3) goto yy69;
              if (yych <= 0xF4) goto yy70;
            }
          }
yy60:
          ++p->cur;
yy61:
          { goto invalid_utf8; }
yy62:
          ++p->cur;
yy63:
          { p->cur = p->tok; goto need_ident; }
yy64:
          yyaccept = 0;
          yych = *(p->mrk = ++p->cur);
          if (yych <= '@') {
            if (yych <= '(') {
              if (yych <= ' ') goto yy75;
              if (yych <= '\'') goto yy63;
              goto yy75;
            } else {
              if (yych <= '/') goto yy63;
              if (yych <= '9') goto yy75;
              goto yy63;
            }
          } else {
            if (yych <= '_') {
              if (yych <= 'Z') goto yy75;
              if (yych <= '^') goto yy63;
              goto yy75;
            } else {
              if (yych <= '`') goto yy63;
              if (yych <= 'z') goto yy75;
              goto yy63;
            }
          }
yy65:
          yych = *++p->cur;
          if (yych <= 0x7F) goto yy61;
          if (yych <= 0xBF) goto yy62;
          goto yy61;
yy66:
          yyaccept = 1;
          yych = *(p->mrk = ++p->cur);
          if (yych <= 0x9F) goto yy61;
          if (yych <= 0xBF) goto yy77;
          goto yy61;
yy67:
          yyaccept = 1;
          yych = *(p->mrk = ++p->cur);
          if (yych <= 0x7F) goto yy61;
          if (yych <= 0xBF) goto yy77;
          goto yy61;
yy68:
          yyaccept = 1;
          yych = *(p->mrk = ++p->cur);
          if (yych <= 0x8F) goto yy61;
          if (yych <= 0xBF) goto yy78;
          goto yy61;
yy69:
          yyaccept = 1;
          yych = *(p->mrk = ++p->cur);
          if (yych <= 0x7F) goto yy61;
          if (yych <= 0xBF) goto yy78;
          goto yy61;
yy70:
          yyaccept = 1;
          yych = *(p->mrk = ++p->cur);
          if (yych <= 0x7F) goto yy61;
          if (yych <= 0x8F) goto yy78;
          goto yy61;
yy71:
          ++p->cur;
yy72:
          p->cur = p->ctxmrk;
          { re2c_lparser_loc_upd_utf8(p); p->lexeme = p->tok; break; }
yy73:
          yych = *++p->cur;
          if (yych == '\n') goto yy71;
          goto yy72;
yy74:
          ++p->cur;
          if ((p->lim - p->cur) < 2) { if (re2c_lparser_fill(p, input, ifname, 2, NULL) < 0) goto error; }
          yych = *p->cur;
yy75:
          if (yych <= '9') {
            if (yych <= ' ') {
              if (yych == '\r') {
                p->ctxmrk = p->cur;
                goto yy73;
              }
              p->ctxmrk = p->cur;
              goto yy71;
            } else {
              if (yych == '(') {
                p->ctxmrk = p->cur;
                goto yy71;
              }
              if (yych >= '0') goto yy74;
            }
          } else {
            if (yych <= '^') {
              if (yych <= '@') goto yy76;
              if (yych <= 'Z') goto yy74;
            } else {
              if (yych == '`') goto yy76;
              if (yych <= 'z') goto yy74;
            }
          }
yy76:
          p->cur = p->mrk;
          if (yyaccept == 0) goto yy63;
          else goto yy61;
yy77:
          yych = *++p->cur;
          if (yych <= 0x7F) goto yy76;
          if (yych <= 0xBF) goto yy62;
          goto yy76;
yy78:
          yych = *++p->cur;
          if (yych <= 0x7F) goto yy76;
          if (yych <= 0xBF) goto yy77;
          goto yy76;
        }

      } while(0);
      if (re2c_lparser_eof(p)) goto req_paren;
      cur_save = p->cur;
      p->cur = p->lexeme;
      for(;;) {
        
        {
          unsigned char yych;
          yych = *p->cur;
          switch (yych) {
            case 'C':
            case 'c': goto yy82;
            case 'E':
            case 'e': goto yy83;
            case 'F':
            case 'f': goto yy84;
            case 'I':
            case 'i': goto yy85;
            case 'M':
            case 'm': goto yy86;
            case 'O':
            case 'o': goto yy87;
            case 'S':
            case 's': goto yy88;
            case 'W':
            case 'w': goto yy89;
            default: goto yy80;
          }
yy80:
          ++p->cur;
yy81:
          { command = others; break; }
yy82:
          yych = *(p->mrk = ++p->cur);
          if (yych == 'M') goto yy90;
          if (yych == 'm') goto yy90;
          goto yy81;
yy83:
          yych = *(p->mrk = ++p->cur);
          if (yych == 'N') goto yy92;
          if (yych == 'n') goto yy92;
          goto yy81;
yy84:
          yych = *(p->mrk = ++p->cur);
          if (yych <= 'U') {
            if (yych == 'O') goto yy93;
            if (yych <= 'T') goto yy81;
            goto yy94;
          } else {
            if (yych <= 'o') {
              if (yych <= 'n') goto yy81;
              goto yy93;
            } else {
              if (yych == 'u') goto yy94;
              goto yy81;
            }
          }
yy85:
          yych = *++p->cur;
          if (yych == 'F') goto yy95;
          if (yych == 'f') goto yy95;
          goto yy81;
yy86:
          yych = *(p->mrk = ++p->cur);
          if (yych == 'A') goto yy96;
          if (yych == 'a') goto yy96;
          goto yy81;
yy87:
          yych = *(p->mrk = ++p->cur);
          if (yych == 'P') goto yy97;
          if (yych == 'p') goto yy97;
          goto yy81;
yy88:
          yych = *(p->mrk = ++p->cur);
          if (yych == 'E') goto yy98;
          if (yych == 'e') goto yy98;
          goto yy81;
yy89:
          yych = *(p->mrk = ++p->cur);
          if (yych == 'H') goto yy99;
          if (yych == 'h') goto yy99;
          goto yy81;
yy90:
          yych = *++p->cur;
          if (yych == 'A') goto yy100;
          if (yych == 'a') goto yy100;
yy91:
          p->cur = p->mrk;
          goto yy81;
yy92:
          yych = *++p->cur;
          if (yych == 'D') goto yy101;
          if (yych == 'd') goto yy101;
          goto yy91;
yy93:
          yych = *++p->cur;
          if (yych == 'R') goto yy102;
          if (yych == 'r') goto yy102;
          goto yy91;
yy94:
          yych = *++p->cur;
          if (yych == 'N') goto yy103;
          if (yych == 'n') goto yy103;
          goto yy91;
yy95:
          ++p->cur;
          { command = cmake_if; break; }
yy96:
          yych = *++p->cur;
          if (yych == 'C') goto yy104;
          if (yych == 'c') goto yy104;
          goto yy91;
yy97:
          yych = *++p->cur;
          if (yych == 'T') goto yy105;
          if (yych == 't') goto yy105;
          goto yy91;
yy98:
          yych = *++p->cur;
          if (yych == 'T') goto yy106;
          if (yych == 't') goto yy106;
          goto yy91;
yy99:
          yych = *++p->cur;
          if (yych == 'I') goto yy107;
          if (yych == 'i') goto yy107;
          goto yy91;
yy100:
          yych = *++p->cur;
          if (yych == 'K') goto yy108;
          if (yych == 'k') goto yy108;
          goto yy91;
yy101:
          yych = *++p->cur;
          if (yych <= 'W') {
            if (yych <= 'I') {
              if (yych == 'F') goto yy109;
              if (yych <= 'H') goto yy91;
              goto yy110;
            } else {
              if (yych == 'M') goto yy111;
              if (yych <= 'V') goto yy91;
              goto yy112;
            }
          } else {
            if (yych <= 'i') {
              if (yych == 'f') goto yy109;
              if (yych <= 'h') goto yy91;
              goto yy110;
            } else {
              if (yych <= 'm') {
                if (yych <= 'l') goto yy91;
                goto yy111;
              } else {
                if (yych == 'w') goto yy112;
                goto yy91;
              }
            }
          }
yy102:
          yych = *++p->cur;
          if (yych == 'E') goto yy113;
          if (yych == 'e') goto yy113;
          goto yy91;
yy103:
          yych = *++p->cur;
          if (yych == 'C') goto yy114;
          if (yych == 'c') goto yy114;
          goto yy91;
yy104:
          yych = *++p->cur;
          if (yych == 'R') goto yy115;
          if (yych == 'r') goto yy115;
          goto yy91;
yy105:
          yych = *++p->cur;
          if (yych == 'I') goto yy116;
          if (yych == 'i') goto yy116;
          goto yy91;
yy106:
          ++p->cur;
          { command = set; break; }
yy107:
          yych = *++p->cur;
          if (yych == 'L') goto yy117;
          if (yych == 'l') goto yy117;
          goto yy91;
yy108:
          yych = *++p->cur;
          if (yych == 'E') goto yy118;
          if (yych == 'e') goto yy118;
          goto yy91;
yy109:
          yych = *++p->cur;
          if (yych <= 'U') {
            if (yych == 'O') goto yy119;
            if (yych <= 'T') goto yy91;
            goto yy120;
          } else {
            if (yych <= 'o') {
              if (yych <= 'n') goto yy91;
              goto yy119;
            } else {
              if (yych == 'u') goto yy120;
              goto yy91;
            }
          }
yy110:
          yych = *++p->cur;
          if (yych == 'F') goto yy121;
          if (yych == 'f') goto yy121;
          goto yy91;
yy111:
          yych = *++p->cur;
          if (yych == 'A') goto yy122;
          if (yych == 'a') goto yy122;
          goto yy91;
yy112:
          yych = *++p->cur;
          if (yych == 'H') goto yy123;
          if (yych == 'h') goto yy123;
          goto yy91;
yy113:
          yych = *++p->cur;
          if (yych == 'A') goto yy124;
          if (yych == 'a') goto yy124;
          goto yy91;
yy114:
          yych = *++p->cur;
          if (yych == 'T') goto yy125;
          if (yych == 't') goto yy125;
          goto yy91;
yy115:
          yych = *++p->cur;
          if (yych == 'O') goto yy126;
          if (yych == 'o') goto yy126;
          goto yy91;
yy116:
          yych = *++p->cur;
          if (yych == 'O') goto yy127;
          if (yych == 'o') goto yy127;
          goto yy91;
yy117:
          yych = *++p->cur;
          if (yych == 'E') goto yy128;
          if (yych == 'e') goto yy128;
          goto yy91;
yy118:
          yych = *++p->cur;
          if (yych == '_') goto yy129;
          goto yy91;
yy119:
          yych = *++p->cur;
          if (yych == 'R') goto yy130;
          if (yych == 'r') goto yy130;
          goto yy91;
yy120:
          yych = *++p->cur;
          if (yych == 'N') goto yy131;
          if (yych == 'n') goto yy131;
          goto yy91;
yy121:
          ++p->cur;
          { command = endif; break; }
yy122:
          yych = *++p->cur;
          if (yych == 'C') goto yy132;
          if (yych == 'c') goto yy132;
          goto yy91;
yy123:
          yych = *++p->cur;
          if (yych == 'I') goto yy133;
          if (yych == 'i') goto yy133;
          goto yy91;
yy124:
          yych = *++p->cur;
          if (yych == 'C') goto yy134;
          if (yych == 'c') goto yy134;
          goto yy91;
yy125:
          yych = *++p->cur;
          if (yych == 'I') goto yy135;
          if (yych == 'i') goto yy135;
          goto yy91;
yy126:
          ++p->cur;
          { command = macro; break; }
yy127:
          yych = *++p->cur;
          if (yych == 'N') goto yy136;
          if (yych == 'n') goto yy136;
          goto yy91;
yy128:
          ++p->cur;
          { command = cmake_while; break; }
yy129:
          yych = *++p->cur;
          if (yych == 'D') goto yy137;
          if (yych == 'd') goto yy137;
          goto yy91;
yy130:
          yych = *++p->cur;
          if (yych == 'E') goto yy138;
          if (yych == 'e') goto yy138;
          goto yy91;
yy131:
          yych = *++p->cur;
          if (yych == 'C') goto yy139;
          if (yych == 'c') goto yy139;
          goto yy91;
yy132:
          yych = *++p->cur;
          if (yych == 'R') goto yy140;
          if (yych == 'r') goto yy140;
          goto yy91;
yy133:
          yych = *++p->cur;
          if (yych == 'L') goto yy141;
          if (yych == 'l') goto yy141;
          goto yy91;
yy134:
          yych = *++p->cur;
          if (yych == 'H') goto yy142;
          if (yych == 'h') goto yy142;
          goto yy91;
yy135:
          yych = *++p->cur;
          if (yych == 'O') goto yy143;
          if (yych == 'o') goto yy143;
          goto yy91;
yy136:
          ++p->cur;
          { command = option; break; }
yy137:
          yych = *++p->cur;
          if (yych == 'E') goto yy144;
          if (yych == 'e') goto yy144;
          goto yy91;
yy138:
          yych = *++p->cur;
          if (yych == 'A') goto yy145;
          if (yych == 'a') goto yy145;
          goto yy91;
yy139:
          yych = *++p->cur;
          if (yych == 'T') goto yy146;
          if (yych == 't') goto yy146;
          goto yy91;
yy140:
          yych = *++p->cur;
          if (yych == 'O') goto yy147;
          if (yych == 'o') goto yy147;
          goto yy91;
yy141:
          yych = *++p->cur;
          if (yych == 'E') goto yy148;
          if (yych == 'e') goto yy148;
          goto yy91;
yy142:
          ++p->cur;
          { command = cmake_foreach; break; }
yy143:
          yych = *++p->cur;
          if (yych == 'N') goto yy149;
          if (yych == 'n') goto yy149;
          goto yy91;
yy144:
          yych = *++p->cur;
          if (yych == 'P') goto yy150;
          if (yych == 'p') goto yy150;
          goto yy91;
yy145:
          yych = *++p->cur;
          if (yych == 'C') goto yy151;
          if (yych == 'c') goto yy151;
          goto yy91;
yy146:
          yych = *++p->cur;
          if (yych == 'I') goto yy152;
          if (yych == 'i') goto yy152;
          goto yy91;
yy147:
          ++p->cur;
          { command = endmacro; break; }
yy148:
          ++p->cur;
          { command = endwhile; break; }
yy149:
          ++p->cur;
          { command = function; break; }
yy150:
          yych = *++p->cur;
          if (yych == 'E') goto yy153;
          if (yych == 'e') goto yy153;
          goto yy91;
yy151:
          yych = *++p->cur;
          if (yych == 'H') goto yy154;
          if (yych == 'h') goto yy154;
          goto yy91;
yy152:
          yych = *++p->cur;
          if (yych == 'O') goto yy155;
          if (yych == 'o') goto yy155;
          goto yy91;
yy153:
          yych = *++p->cur;
          if (yych == 'N') goto yy156;
          if (yych == 'n') goto yy156;
          goto yy91;
yy154:
          ++p->cur;
          { command = endforeach; break; }
yy155:
          yych = *++p->cur;
          if (yych == 'N') goto yy157;
          if (yych == 'n') goto yy157;
          goto yy91;
yy156:
          yych = *++p->cur;
          if (yych == 'D') goto yy158;
          if (yych == 'd') goto yy158;
          goto yy91;
yy157:
          ++p->cur;
          { command = endfunction; break; }
yy158:
          yych = *++p->cur;
          if (yych == 'E') goto yy159;
          if (yych != 'e') goto yy91;
yy159:
          yych = *++p->cur;
          if (yych == 'N') goto yy160;
          if (yych != 'n') goto yy91;
yy160:
          yych = *++p->cur;
          if (yych == 'T') goto yy161;
          if (yych != 't') goto yy91;
yy161:
          yych = *++p->cur;
          if (yych != '_') goto yy91;
          yych = *++p->cur;
          if (yych == 'O') goto yy162;
          if (yych != 'o') goto yy91;
yy162:
          yych = *++p->cur;
          if (yych == 'P') goto yy163;
          if (yych != 'p') goto yy91;
yy163:
          yych = *++p->cur;
          if (yych == 'T') goto yy164;
          if (yych != 't') goto yy91;
yy164:
          yych = *++p->cur;
          if (yych == 'I') goto yy165;
          if (yych != 'i') goto yy91;
yy165:
          yych = *++p->cur;
          if (yych == 'O') goto yy166;
          if (yych != 'o') goto yy91;
yy166:
          yych = *++p->cur;
          if (yych == 'N') goto yy167;
          if (yych != 'n') goto yy91;
yy167:
          ++p->cur;
          { command = dep_option; break; }
        }

        
      }
      switch(command) {
      case cmake_if:
      case cmake_while:
      case cmake_foreach:
      case function:
      case macro:
        indent += 1;
        break;
      case endif:
      case endwhile:
      case endforeach:
      case endfunction:
      case endmacro:
        indent -= 1;
        if (indent < 0) indent = 0;
        break;
      default:
        /* nop */
        break;
      }

      p->cur = cur_save;
      p->lexeme = NULL;
      while(!re2c_lparser_eof(p)) {
        re2c_lparser_start_token(p);
        
        {
          unsigned char yych;
          if ((p->lim - p->cur) < 4) { if (re2c_lparser_fill(p, input, ifname, 4, NULL) < 0) goto error; }
          yych = *p->cur;
          if (yych <= '(') {
            if (yych <= '\r') {
              if (yych == '\t') goto yy171;
              if (yych >= '\r') goto yy172;
            } else {
              if (yych == ' ') goto yy171;
              if (yych >= '(') goto yy173;
            }
          } else {
            if (yych <= 0xE0) {
              if (yych <= 0x7F) goto yy169;
              if (yych <= 0xC1) goto yy174;
              if (yych <= 0xDF) goto yy176;
              goto yy177;
            } else {
              if (yych <= 0xF0) {
                if (yych <= 0xEF) goto yy178;
                goto yy179;
              } else {
                if (yych <= 0xF3) goto yy180;
                if (yych <= 0xF4) goto yy181;
                goto yy174;
              }
            }
          }
yy169:
          ++p->cur;
yy170:
          { goto req_paren; }
yy171:
          ++p->cur;
          { re2c_lparser_loc_upd_utf8(p); continue; }
yy172:
          yych = *++p->cur;
          if (yych == '\n') goto yy169;
          goto yy170;
yy173:
          ++p->cur;
          { re2c_lparser_loc_upd_utf8(p); break; }
yy174:
          ++p->cur;
yy175:
          { goto invalid_utf8; }
yy176:
          yych = *++p->cur;
          if (yych <= 0x7F) goto yy175;
          if (yych <= 0xBF) goto yy169;
          goto yy175;
yy177:
          yych = *(p->mrk = ++p->cur);
          if (yych <= 0x9F) goto yy175;
          if (yych <= 0xBF) goto yy182;
          goto yy175;
yy178:
          yych = *(p->mrk = ++p->cur);
          if (yych <= 0x7F) goto yy175;
          if (yych <= 0xBF) goto yy182;
          goto yy175;
yy179:
          yych = *(p->mrk = ++p->cur);
          if (yych <= 0x8F) goto yy175;
          if (yych <= 0xBF) goto yy184;
          goto yy175;
yy180:
          yych = *(p->mrk = ++p->cur);
          if (yych <= 0x7F) goto yy175;
          if (yych <= 0xBF) goto yy184;
          goto yy175;
yy181:
          yych = *(p->mrk = ++p->cur);
          if (yych <= 0x7F) goto yy175;
          if (yych <= 0x8F) goto yy184;
          goto yy175;
yy182:
          yych = *++p->cur;
          if (yych <= 0x7F) goto yy183;
          if (yych <= 0xBF) goto yy169;
yy183:
          p->cur = p->mrk;
          goto yy175;
yy184:
          yych = *++p->cur;
          if (yych <= 0x7F) goto yy183;
          if (yych <= 0xBF) goto yy182;
          goto yy183;
        }

      }
      if (re2c_lparser_eof(p)) goto req_paren;
      narg = 1;
      for(cnt_paren = 1; cnt_paren > 0; ) {
        const char *lastp;
        int quote_used;
        quote_used = 0;

        for(;;) {
          re2c_lparser_start_token(p);
          
          {
            unsigned char yych;
            if ((p->lim - p->cur) < 2) { if (re2c_lparser_fill(p, input, ifname, 2, NULL) < 0) goto error; }
            yych = *p->cur;
            if (yych <= '\f') {
              if (yych <= 0x08) goto yy186;
              if (yych <= '\n') goto yy187;
            } else {
              if (yych <= '\r') goto yy189;
              if (yych == ' ') goto yy187;
            }
yy186:
            ++p->cur;
            { break; }
yy187:
            ++p->cur;
yy188:
            { re2c_lparser_loc_upd_utf8(p); continue; }
yy189:
            yych = *++p->cur;
            if (yych == '\n') goto yy187;
            goto yy188;
          }

        }
        p->cur = p->tok;
        p->line = p->tokline;
        p->col = p->tokcol;
        p->lexeme = p->cur;

        lastp = NULL;
        while(!re2c_lparser_eof(p)) {
          re2c_lparser_start_token(p);
          
          {
            unsigned char yych;
            if ((p->lim - p->cur) < 4) { if (re2c_lparser_fill(p, input, ifname, 4, NULL) < 0) goto error; }
            yych = *p->cur;
            if (yych <= ')') {
              if (yych <= '!') {
                if (yych == '\r') goto yy193;
                if (yych >= '!') goto yy194;
              } else {
                if (yych <= '"') goto yy195;
                if (yych <= '\'') goto yy194;
                if (yych <= '(') goto yy196;
                goto yy197;
              }
            } else {
              if (yych <= 0xE0) {
                if (yych <= 0x7F) goto yy194;
                if (yych <= 0xC1) goto yy198;
                if (yych <= 0xDF) goto yy200;
                goto yy201;
              } else {
                if (yych <= 0xF0) {
                  if (yych <= 0xEF) goto yy202;
                  goto yy203;
                } else {
                  if (yych <= 0xF3) goto yy204;
                  if (yych <= 0xF4) goto yy205;
                  goto yy198;
                }
              }
            }
yy191:
            ++p->cur;
yy192:
            { p->cur = p->tok; lastp = p->cur; break; }
yy193:
            yych = *++p->cur;
            if (yych == '\n') goto yy191;
            goto yy192;
yy194:
            ++p->cur;
            { re2c_lparser_loc_upd_utf8(p); continue; }
yy195:
            ++p->cur;
            { re2c_lparser_loc_upd_utf8(p); goto arg_quote; }
yy196:
            ++p->cur;
            { re2c_lparser_loc_upd_utf8(p); goto open_paren; }
yy197:
            ++p->cur;
            { re2c_lparser_loc_upd_utf8(p); goto close_paren; }
yy198:
            ++p->cur;
yy199:
            { goto invalid_utf8; }
yy200:
            yych = *++p->cur;
            if (yych <= 0x7F) goto yy199;
            if (yych <= 0xBF) goto yy194;
            goto yy199;
yy201:
            yych = *(p->mrk = ++p->cur);
            if (yych <= 0x9F) goto yy199;
            if (yych <= 0xBF) goto yy206;
            goto yy199;
yy202:
            yych = *(p->mrk = ++p->cur);
            if (yych <= 0x7F) goto yy199;
            if (yych <= 0xBF) goto yy206;
            goto yy199;
yy203:
            yych = *(p->mrk = ++p->cur);
            if (yych <= 0x8F) goto yy199;
            if (yych <= 0xBF) goto yy208;
            goto yy199;
yy204:
            yych = *(p->mrk = ++p->cur);
            if (yych <= 0x7F) goto yy199;
            if (yych <= 0xBF) goto yy208;
            goto yy199;
yy205:
            yych = *(p->mrk = ++p->cur);
            if (yych <= 0x7F) goto yy199;
            if (yych <= 0x8F) goto yy208;
            goto yy199;
yy206:
            yych = *++p->cur;
            if (yych <= 0x7F) goto yy207;
            if (yych <= 0xBF) goto yy194;
yy207:
            p->cur = p->mrk;
            goto yy199;
yy208:
            yych = *++p->cur;
            if (yych <= 0x7F) goto yy207;
            if (yych <= 0xBF) goto yy206;
            goto yy207;
          }


        arg_quote:
          quote_used = 1;
          if (p->tok > p->lexeme) {
          in_middle_quote:
            print_error("%s(%ld,%ld): This program cannot handle in-middle quotes correctly",
                        ifname, p->tokline, p->tokcol);
            continue;
          } else {
            p->lexeme = p->cur;
          }
          while (!re2c_lparser_eof(p)) {
            re2c_lparser_start_token(p);
            
            {
              unsigned char yych;
              if ((p->lim - p->cur) < 4) { if (re2c_lparser_fill(p, input, ifname, 4, NULL) < 0) goto error; }
              yych = *p->cur;
              if (yych <= 0x7F) {
                if (yych <= '!') {
                  if (yych == '\r') goto yy212;
                } else {
                  if (yych <= '"') goto yy213;
                  if (yych == '\\') goto yy214;
                }
              } else {
                if (yych <= 0xEF) {
                  if (yych <= 0xC1) goto yy215;
                  if (yych <= 0xDF) goto yy217;
                  if (yych <= 0xE0) goto yy218;
                  goto yy219;
                } else {
                  if (yych <= 0xF0) goto yy220;
                  if (yych <= 0xF3) goto yy221;
                  if (yych <= 0xF4) goto yy222;
                  goto yy215;
                }
              }
yy210:
              ++p->cur;
yy211:
              { re2c_lparser_loc_upd_utf8(p); continue; }
yy212:
              yych = *++p->cur;
              if (yych == '\n') goto yy210;
              goto yy211;
yy213:
              ++p->cur;
              { re2c_lparser_loc_upd_utf8(p); break; }
yy214:
              yych = *++p->cur;
              if (yych == '"') goto yy223;
              goto yy211;
yy215:
              ++p->cur;
yy216:
              { goto invalid_utf8; }
yy217:
              yych = *++p->cur;
              if (yych <= 0x7F) goto yy216;
              if (yych <= 0xBF) goto yy210;
              goto yy216;
yy218:
              yych = *(p->mrk = ++p->cur);
              if (yych <= 0x9F) goto yy216;
              if (yych <= 0xBF) goto yy224;
              goto yy216;
yy219:
              yych = *(p->mrk = ++p->cur);
              if (yych <= 0x7F) goto yy216;
              if (yych <= 0xBF) goto yy224;
              goto yy216;
yy220:
              yych = *(p->mrk = ++p->cur);
              if (yych <= 0x8F) goto yy216;
              if (yych <= 0xBF) goto yy226;
              goto yy216;
yy221:
              yych = *(p->mrk = ++p->cur);
              if (yych <= 0x7F) goto yy216;
              if (yych <= 0xBF) goto yy226;
              goto yy216;
yy222:
              yych = *(p->mrk = ++p->cur);
              if (yych <= 0x7F) goto yy216;
              if (yych <= 0x8F) goto yy226;
              goto yy216;
yy223:
              ++p->cur;
              { re2c_lparser_loc_upd_utf8(p); continue; }
yy224:
              yych = *++p->cur;
              if (yych <= 0x7F) goto yy225;
              if (yych <= 0xBF) goto yy210;
yy225:
              p->cur = p->mrk;
              goto yy216;
yy226:
              yych = *++p->cur;
              if (yych <= 0x7F) goto yy225;
              if (yych <= 0xBF) goto yy224;
              goto yy225;
            }

          }
          if (re2c_lparser_eof(p)) goto unexp_eof;
          lastp = p->tok;
          re2c_lparser_start_token(p);
          
          {
            unsigned char yych;
            if ((p->lim - p->cur) < 4) { if (re2c_lparser_fill(p, input, ifname, 4, NULL) < 0) goto error; }
            yych = *p->cur;
            if (yych <= 0xC1) {
              if (yych <= ' ') {
                if (yych == '\r') goto yy230;
              } else {
                if (yych <= '\'') goto yy231;
                if (yych <= ')') goto yy232;
                if (yych <= 0x7F) goto yy231;
                goto yy233;
              }
            } else {
              if (yych <= 0xEF) {
                if (yych <= 0xDF) goto yy235;
                if (yych <= 0xE0) goto yy236;
                goto yy237;
              } else {
                if (yych <= 0xF0) goto yy238;
                if (yych <= 0xF3) goto yy239;
                if (yych <= 0xF4) goto yy240;
                goto yy233;
              }
            }
yy228:
            ++p->cur;
yy229:
            { p->cur = p->tok; break; }
yy230:
            yych = *++p->cur;
            if (yych == '\n') goto yy228;
            goto yy229;
yy231:
            ++p->cur;
            { p->cur = p->tok; goto in_middle_quote; }
yy232:
            ++p->cur;
            { p->cur = p->tok; continue; }
yy233:
            ++p->cur;
yy234:
            { goto invalid_utf8; }
yy235:
            yych = *++p->cur;
            if (yych <= 0x7F) goto yy234;
            if (yych <= 0xBF) goto yy231;
            goto yy234;
yy236:
            yych = *(p->mrk = ++p->cur);
            if (yych <= 0x9F) goto yy234;
            if (yych <= 0xBF) goto yy241;
            goto yy234;
yy237:
            yych = *(p->mrk = ++p->cur);
            if (yych <= 0x7F) goto yy234;
            if (yych <= 0xBF) goto yy241;
            goto yy234;
yy238:
            yych = *(p->mrk = ++p->cur);
            if (yych <= 0x8F) goto yy234;
            if (yych <= 0xBF) goto yy243;
            goto yy234;
yy239:
            yych = *(p->mrk = ++p->cur);
            if (yych <= 0x7F) goto yy234;
            if (yych <= 0xBF) goto yy243;
            goto yy234;
yy240:
            yych = *(p->mrk = ++p->cur);
            if (yych <= 0x7F) goto yy234;
            if (yych <= 0x8F) goto yy243;
            goto yy234;
yy241:
            yych = *++p->cur;
            if (yych <= 0x7F) goto yy242;
            if (yych <= 0xBF) goto yy231;
yy242:
            p->cur = p->mrk;
            goto yy234;
yy243:
            yych = *++p->cur;
            if (yych <= 0x7F) goto yy242;
            if (yych <= 0xBF) goto yy241;
            goto yy242;
          }

          assert(0 && "Unreachable reached");

          /* parentheses creates one arguement independently */
        open_paren:
          cnt_paren += 1;
          if (!lastp) lastp = p->tok;
          break;

        close_paren:
          cnt_paren -= 1;
          if (!lastp) lastp = p->tok;
          break;
        }
        if (re2c_lparser_eof(p)) {
          if (cnt_paren > 0) goto unexp_eof;
        }

        /* no argument */
        if (!quote_used) {
          if (!lastp || lastp <= p->lexeme) continue;
        }

        switch(command) {
        case option:
        case dep_option:
          switch(narg) {
          case 1:
            for (i = indent; i > 0; --i) {
              fprintf(output, "  ");
            }
            fprintf(output, "%.*s", (int)(lastp - p->lexeme), p->lexeme);
            break;
          case 3:
            fprintf(output, " = \"%.*s\"", (int)(lastp - p->lexeme), p->lexeme);
            break;
          }
          break;
        case function:
        case macro:
          if (narg == 1) {
            for (i = indent; i > 0; --i) {
              fprintf(output, "  ");
            }
#ifdef PYTHON_OUTPUT
            fprintf(output, "def ");
#else
#if 0
            if (command == macro) {
              fprintf(output, "cmake_macro ");
            } else {
              fprintf(output, "cmake_function ");
            }
#else
            if (command == macro) {
              fprintf(output, "macro ");
            } else {
              fprintf(output, "function ");
            }
#endif
#endif
            fprintf(output, "%.*s(", (int)(lastp - p->lexeme), p->lexeme);
          } else {
            if (narg > 2) {
              fprintf(output, ", ");
            }
#ifndef PYTHON_OUTPUT
            //fprintf(output, "cmake_value ");
#endif
            fprintf(output, "%.*s", (int)(lastp - p->lexeme), p->lexeme);
          }
          break;
        default:
          /* nop */
          break;
        }

        narg++;
      }
      if (command == function || command == macro) {
        fprintf(output, ")");
#ifdef PYTHON_OUTPUT
        fprintf(output, ":");
#else
#if 1
        fprintf(output, " {}");
#endif
#endif
      }
      if (command == option || command == dep_option) {
#ifndef PYTHON_OUTPUT
        fprintf(output, ";");
#endif
      }
    }
    continue;
  }

 clean:
  free(p->buf);
  return ret;

 req_paren:
  if (!re2c_lparser_eof(p)) {
    p->cur = p->tok;
    p->line = p->tokline;
    p->col  = p->tokcol;
    for (;;) {
      re2c_lparser_start_token(p);
      
    {
      unsigned char yych;
      if ((p->lim - p->cur) < 2) { if (re2c_lparser_fill(p, input, ifname, 2, NULL) < 0) goto error; }
      yych = *p->cur;
      if (yych == '\n') goto yy245;
      if (yych == '\r') goto yy247;
      ++p->cur;
      {
          print_error("%s(%ld,%ld): Requires '(', but found '%.*s'",
          ifname, p->tokline, p->tokcol, (int)(p->cur - p->tok), p->tok);
          break;
        }
yy245:
      ++p->cur;
yy246:
      {
          print_error("%s(%ld,%ld): Requires '(', but found newline",
          ifname, p->tokline, p->tokcol);
          break;
        }
yy247:
      yych = *++p->cur;
      if (yych == '\n') goto yy245;
      goto yy246;
    }

    }
  } else {
    print_error("%s(%ld,%ld): Requires '(', but reached EOF",
                ifname, p->tokline, p->tokcol);
  }
  goto error;

 unexp_eof:
  print_error("%s(%ld,%ld): Unexpected EOF reached",
              ifname, p->tokline, p->tokcol);
  goto error;

 need_ident:
  do {
    
    {
      unsigned char yych;
      unsigned int yyaccept = 0;
      if ((p->lim - p->cur) < 2) { if (re2c_lparser_fill(p, input, ifname, 2, NULL) < 0) goto error; }
      yych = *p->cur;
      if (yych <= 0xE0) {
        if (yych <= 0x7F) {
          if (yych >= '!') goto yy251;
        } else {
          if (yych <= 0xC1) goto yy249;
          if (yych <= 0xDF) goto yy253;
          goto yy254;
        }
      } else {
        if (yych <= 0xF0) {
          if (yych <= 0xEF) goto yy255;
          goto yy256;
        } else {
          if (yych <= 0xF3) goto yy257;
          if (yych <= 0xF4) goto yy258;
        }
      }
yy249:
      ++p->cur;
yy250:
      { break; }
yy251:
      yyaccept = 0;
      p->mrk = ++p->cur;
      if (p->lim <= p->cur) { if (re2c_lparser_fill(p, input, ifname, 1, NULL) < 0) goto error; }
      yych = *p->cur;
      if (yych <= 0xE0) {
        if (yych <= 0x7F) {
          if (yych >= '!') goto yy251;
        } else {
          if (yych <= 0xC1) goto yy252;
          if (yych <= 0xDF) goto yy259;
          goto yy261;
        }
      } else {
        if (yych <= 0xF0) {
          if (yych <= 0xEF) goto yy262;
          goto yy263;
        } else {
          if (yych <= 0xF3) goto yy264;
          if (yych <= 0xF4) goto yy265;
        }
      }
yy252:
      { break; }
yy253:
      yych = *++p->cur;
      if (yych <= 0x7F) goto yy250;
      if (yych <= 0xBF) goto yy251;
      goto yy250;
yy254:
      yyaccept = 1;
      yych = *(p->mrk = ++p->cur);
      if (yych <= 0x9F) goto yy250;
      if (yych <= 0xBF) goto yy259;
      goto yy250;
yy255:
      yyaccept = 1;
      yych = *(p->mrk = ++p->cur);
      if (yych <= 0x7F) goto yy250;
      if (yych <= 0xBF) goto yy259;
      goto yy250;
yy256:
      yyaccept = 1;
      yych = *(p->mrk = ++p->cur);
      if (yych <= 0x8F) goto yy250;
      if (yych <= 0xBF) goto yy262;
      goto yy250;
yy257:
      yyaccept = 1;
      yych = *(p->mrk = ++p->cur);
      if (yych <= 0x7F) goto yy250;
      if (yych <= 0xBF) goto yy262;
      goto yy250;
yy258:
      yyaccept = 1;
      yych = *(p->mrk = ++p->cur);
      if (yych <= 0x7F) goto yy250;
      if (yych <= 0x8F) goto yy262;
      goto yy250;
yy259:
      ++p->cur;
      if (p->lim <= p->cur) { if (re2c_lparser_fill(p, input, ifname, 1, NULL) < 0) goto error; }
      yych = *p->cur;
      if (yych <= 0x7F) goto yy260;
      if (yych <= 0xBF) goto yy251;
yy260:
      p->cur = p->mrk;
      if (yyaccept == 0) goto yy252;
      else goto yy250;
yy261:
      ++p->cur;
      if (p->lim <= p->cur) { if (re2c_lparser_fill(p, input, ifname, 1, NULL) < 0) goto error; }
      yych = *p->cur;
      if (yych <= 0x9F) goto yy260;
      if (yych <= 0xBF) goto yy259;
      goto yy260;
yy262:
      ++p->cur;
      if (p->lim <= p->cur) { if (re2c_lparser_fill(p, input, ifname, 1, NULL) < 0) goto error; }
      yych = *p->cur;
      if (yych <= 0x7F) goto yy260;
      if (yych <= 0xBF) goto yy259;
      goto yy260;
yy263:
      ++p->cur;
      if (p->lim <= p->cur) { if (re2c_lparser_fill(p, input, ifname, 1, NULL) < 0) goto error; }
      yych = *p->cur;
      if (yych <= 0x8F) goto yy260;
      if (yych <= 0xBF) goto yy262;
      goto yy260;
yy264:
      ++p->cur;
      if (p->lim <= p->cur) { if (re2c_lparser_fill(p, input, ifname, 1, NULL) < 0) goto error; }
      yych = *p->cur;
      if (yych <= 0x7F) goto yy260;
      if (yych <= 0xBF) goto yy262;
      goto yy260;
yy265:
      ++p->cur;
      if (p->lim <= p->cur) { if (re2c_lparser_fill(p, input, ifname, 1, NULL) < 0) goto error; }
      yych = *p->cur;
      if (yych <= 0x7F) goto yy260;
      if (yych <= 0x8F) goto yy262;
      goto yy260;
    }

  } while(0);
  print_error("%s(%ld,%ld): Requires identifier, but found '%.*s'",
              ifname, p->tokline, p->tokcol, (int)(p->cur - p->tok), p->tok);
  goto error;

 invalid_utf8:
  print_error("%s(%ld,%ld): Invalid utf-8 sequence",
              ifname, p->tokline, p->tokcol);
  goto error;

 error:
  if (p->readerr) {
    print_error("%s(%ld,%ld): Read error: %s",
                ifname, p->tokline, p->tokcol, strerror(p->readerr));
  }
  ret = 1;
  goto clean;
}

/** @} */
